import { useEffect, useState } from 'react';
import { FileXls, MagnifyingGlass, WarningCircle } from '@phosphor-icons/react';
import { operationsFetch, operationsQuery } from '../api';
import { exportExcel } from '../excel';
import { useOperationsMeta } from '../OperationsLayout';
import type { VehicleRow } from '../types';
import { VehicleTable } from '../components/VehicleTable';
import { OperationsModal } from '../components/OperationsModal';

export function AllVehiclesPage(){const meta=useOperationsMeta();const [rows,setRows]=useState<VehicleRow[]>([]);const [total,setTotal]=useState(0);const [search,setSearch]=useState('');const [location,setLocation]=useState('');const [status,setStatus]=useState('');const [selected,setSelected]=useState<VehicleRow|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
async function load(){setLoading(true);setError('');try{const payload=await operationsFetch<any>(`/api/operations${operationsQuery({resource:'vehicles',search,location,status,archived:'all',page:1,pageSize:5000})}`);setRows(payload.rows||[]);setTotal(payload.total||0);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل جميع السيارات');}finally{setLoading(false);}}
useEffect(()=>{void load();},[]);
function exportRows(){exportExcel('جميع-السيارات',['رقم الهيكل','السيارة','البيان','الموديل','داخلي','خارجي','المكان','الحالة','الفرع','مؤرشفة'],rows.map((row)=>[row.vin,row.car_name,row.statement,row.model_year,row.interior_color,row.exterior_color,row.location_name,row.status_name,row.branch_name,row.archived_at?'نعم':'لا']));}
return <div className="module-page operations-page"><section className="panel operations-toolbar"><div className="operations-search"><MagnifyingGlass size={18}/><input value={search} onChange={(e)=>setSearch(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter')void load();}} placeholder="بحث"/></div><select value={location} onChange={(e)=>setLocation(e.target.value)}><option value="">كل الأماكن</option>{meta.locations.map((item)=><option key={item.id} value={item.code}>{item.name}</option>)}</select><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">كل الحالات</option>{meta.statuses.map((item)=><option key={item.code} value={item.code}>{item.name}</option>)}</select><button onClick={()=>void load()}><MagnifyingGlass size={17}/>بحث</button><button className="secondary" onClick={exportRows}><FileXls size={17}/>تصدير Excel</button></section>{error?<div className="connection-banner"><WarningCircle size={20}/><span>{error}</span></div>:null}<section className="panel operations-list-panel"><div className="operations-panel-title"><div><h2>جميع السيارات</h2><p>تقرير كامل يشمل السيارات النشطة والمؤرشفة وفق صلاحية الفروع.</p></div><strong>{total}</strong></div><VehicleTable rows={rows} onOpen={setSelected}/>{loading?<div className="operations-loading">جاري التحميل...</div>:null}</section><OperationsModal open={Boolean(selected)} title={selected?selected.vin:''} onClose={()=>setSelected(null)}>{selected?<div className="vehicle-detail-grid"><div><small>السيارة</small><strong>{selected.car_name||'—'}</strong></div><div><small>البيان</small><strong>{selected.statement||'—'}</strong></div><div><small>الموديل</small><strong>{selected.model_year||'—'}</strong></div><div><small>المكان</small><strong>{selected.location_name||'—'}</strong></div><div><small>الحالة</small><strong>{selected.status_name||'—'}</strong></div><div><small>الأرشيف</small><strong>{selected.archived_at?'مؤرشفة':'نشطة'}</strong></div></div>:null}</OperationsModal></div>;}
