import { useEffect, useState } from 'react';
import { CheckCircle, MagnifyingGlass, WarningCircle, XCircle } from '@phosphor-icons/react';
import { formatDate, operationsFetch, operationsQuery } from '../api';
import { useOperationsMeta } from '../OperationsLayout';
import type { ApprovalRow } from '../types';
import { OperationsModal } from '../components/OperationsModal';

export function ApprovalsPage(){
  const meta=useOperationsMeta();const [rows,setRows]=useState<ApprovalRow[]>([]);const [filter,setFilter]=useState('');const [search,setSearch]=useState('');const [selected,setSelected]=useState<ApprovalRow|null>(null);const [financialNote,setFinancialNote]=useState('');const [administrativeNote,setAdministrativeNote]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  const canFinancial=meta.systemAdmin||meta.permissions.includes('operations.approvals.financial');const canAdministrative=meta.systemAdmin||meta.permissions.includes('operations.approvals.administrative');const canReset=meta.systemAdmin||meta.permissions.includes('operations.approvals.reset');
  async function load(){setLoading(true);setError('');try{const payload=await operationsFetch<any>(`/api/operations${operationsQuery({resource:'approvals',filter,search})}`);setRows(payload.rows||[]);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل الموافقات');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[filter]);
  function open(row:ApprovalRow){setSelected(row);setFinancialNote(row.financial_note||'');setAdministrativeNote(row.administrative_note||'');}
  async function act(type:'financial'|'administrative'|'all',action:'approve'|'revert'|'note'|'reset',note=''){if(!selected)return;setLoading(true);setError('');try{const payload=await operationsFetch<any>('/api/operations',{method:'POST',body:JSON.stringify({action:'approval',vehicleId:selected.vehicle_id,type,approvalAction:action,note})});setMessage(payload.message);setSelected(null);await load();}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ الموافقة');}finally{setLoading(false);}}
  return <div className="module-page operations-page">
    <section className="panel approval-filter-card"><div className="approval-filters"><button className={!filter?'active':''} onClick={()=>setFilter('')}>كل السيارات</button><button className={filter==='missing_financial'?'active':''} onClick={()=>setFilter('missing_financial')}>ناقص مالي</button><button className={filter==='missing_administrative'?'active':''} onClick={()=>setFilter('missing_administrative')}>ناقص إداري</button><button className={filter==='completed'?'active':''} onClick={()=>setFilter('completed')}>مكتملة</button></div><div className="operations-search approval-search"><MagnifyingGlass size={18}/><input value={search} onChange={(e)=>setSearch(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter')void load();}} placeholder="بحث برقم الهيكل أو السيارة"/><button onClick={()=>void load()}>بحث</button></div></section>
    {error?<div className="connection-banner"><WarningCircle size={20}/><span>{error}</span></div>:null}{message?<div className="success-banner"><span>{message}</span></div>:null}
    <section className="panel operations-list-panel"><div className="operations-panel-title"><div><h2>الموافقات المالية والإدارية</h2><p>السيارات بحالة مباع تحت التسليم فقط.</p></div><strong>{rows.length}</strong></div><div className="operations-table-scroll"><table className="operations-table"><thead><tr><th>رقم الهيكل</th><th>السيارة</th><th>البيان</th><th>المكان</th><th>المالية</th><th>الإدارية</th><th>الإجراء</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={7} className="table-empty">لا توجد سيارات مطابقة</td></tr>:rows.map((row)=><tr key={row.vehicle_id}><td>{row.vin}</td><td>{row.car_name||'—'}</td><td>{row.statement||'—'}</td><td>{row.location_name||'—'}</td><td><span className={row.financial_approved?'approval-ok':'approval-missing'}>{row.financial_approved?'تم':'لم يتم'}</span></td><td><span className={row.administrative_approved?'approval-ok':'approval-missing'}>{row.administrative_approved?'تم':'لم يتم'}</span></td><td><button className="small-action" onClick={()=>open(row)}>فتح الموافقات</button></td></tr>)}</tbody></table></div>{loading?<div className="operations-loading">جاري التحميل...</div>:null}</section>
    <OperationsModal open={Boolean(selected)} title={selected?`موافقات السيارة — ${selected.vin}`:''} onClose={()=>setSelected(null)} className="operations-wide-modal">{selected?<div className="approval-modal-grid"><article className={selected.financial_approved?'approval-card approved':'approval-card'}><header><h3>الموافقة المالية</h3>{selected.financial_approved?<CheckCircle size={24}/>:<XCircle size={24}/>}</header><p>الحالة: <strong>{selected.financial_approved?'تمت':'لم تتم'}</strong></p><small>{selected.financial_approved_at?`${formatDate(selected.financial_approved_at)} — ${selected.financial_approved_by_name||'—'}`:'لم تنفذ بعد'}</small><label><span>الملاحظة المالية</span><textarea value={financialNote} onChange={(e)=>setFinancialNote(e.target.value)}/></label><div className="approval-actions">{canFinancial?<><button onClick={()=>void act('financial','note',financialNote)}>حفظ الملاحظة</button>{!selected.financial_approved?<button onClick={()=>void act('financial','approve',financialNote)}>موافقة مالية</button>:<button className="danger" onClick={()=>void act('financial','revert',financialNote)}>تراجع</button>}</>:null}</div></article><article className={selected.administrative_approved?'approval-card approved':'approval-card'}><header><h3>الموافقة الإدارية</h3>{selected.administrative_approved?<CheckCircle size={24}/>:<XCircle size={24}/>}</header><p>الحالة: <strong>{selected.administrative_approved?'تمت':'لم تتم'}</strong></p><small>{selected.administrative_approved_at?`${formatDate(selected.administrative_approved_at)} — ${selected.administrative_approved_by_name||'—'}`:'لم تنفذ بعد'}</small><label><span>الملاحظة الإدارية</span><textarea value={administrativeNote} onChange={(e)=>setAdministrativeNote(e.target.value)}/></label><div className="approval-actions">{canAdministrative?<><button onClick={()=>void act('administrative','note',administrativeNote)}>حفظ الملاحظة</button>{!selected.administrative_approved?<button onClick={()=>void act('administrative','approve',administrativeNote)}>موافقة إدارية</button>:<button className="danger" onClick={()=>void act('administrative','revert',administrativeNote)}>تراجع</button>}</>:null}</div></article>{canReset?<div className="approval-reset-row"><button className="danger" onClick={()=>{const reason=window.prompt('اكتب سبب مسح الموافقات');if(reason)void act('all','reset',reason);}}>إلغاء الطلب (مسح الموافقات)</button></div>:null}</div>:null}</OperationsModal>
  </div>;
}
