import { useEffect, useMemo, useState } from 'react';
import { Archive, ArrowClockwise, FileXls, MagnifyingGlass, Trash, WarningCircle } from '@phosphor-icons/react';
import { operationsFetch, operationsQuery, formatDate } from '../api';
import { exportExcel } from '../excel';
import type { VehicleRow } from '../types';
import { useOperationsMeta } from '../OperationsLayout';
import { VehicleTable } from '../components/VehicleTable';
import { OperationsModal } from '../components/OperationsModal';

type ListResponse={ok:boolean;rows:VehicleRow[];total:number;page:number;pageSize:number};
export function InventoryPage(){
  const meta=useOperationsMeta();const [rows,setRows]=useState<VehicleRow[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [location,setLocation]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [selected,setSelected]=useState<VehicleRow|null>(null);const [detail,setDetail]=useState<any>(null);const [detailLoading,setDetailLoading]=useState(false);const [deleteOpen,setDeleteOpen]=useState(false);const [deleteReason,setDeleteReason]=useState('');
  const canDelete=meta.systemAdmin||meta.permissions.includes('operations.vehicle.delete');const canArchive=meta.systemAdmin||meta.permissions.includes('operations.archive.manage');
  async function load(nextPage=page){setLoading(true);setError('');try{const payload=await operationsFetch<ListResponse>(`/api/operations${operationsQuery({resource:'vehicles',search,status,location,page:nextPage,pageSize:25})}`);setRows(payload.rows);setTotal(payload.total);setPage(payload.page);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل المخزون');}finally{setLoading(false);}}
  useEffect(()=>{void load(1);},[]);
  async function openVehicle(row:VehicleRow){setSelected(row);setDetailLoading(true);setDetail(null);try{const payload=await operationsFetch<any>(`/api/operations${operationsQuery({resource:'vehicle',id:row.id})}`);setDetail(payload);}catch(e){setError(e instanceof Error?e.message:'تعذر فتح تفاصيل السيارة');setSelected(null);}finally{setDetailLoading(false);}}
  async function exportRows(){setLoading(true);try{const payload=await operationsFetch<ListResponse>(`/api/operations${operationsQuery({resource:'vehicles',search,status,location,page:1,pageSize:5000})}`);exportExcel('مخزون-السيارات',['رقم الهيكل','السيارة','البيان','الموديل','داخلي','خارجي','المكان','الحالة','الوكيل','اللوحة'],payload.rows.map((row)=>[row.vin,row.car_name,row.statement,row.model_year,row.interior_color,row.exterior_color,row.location_name,row.status_name,row.agent_name,row.plate_no]));}catch(e){setError(e instanceof Error?e.message:'تعذر التصدير');}finally{setLoading(false);}}
  async function archiveVehicle(action:'archive'|'restore'){if(!selected)return;const reason=window.prompt(action==='archive'?'اكتب سبب الأرشفة':'اكتب سبب الاستعادة');if(!reason)return;try{const payload=await operationsFetch<any>('/api/operations',{method:'POST',body:JSON.stringify({action,vehicleId:selected.id,reason})});setMessage(payload.message);setSelected(null);await load();}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ الأرشفة');}}
  async function deleteVehicle(){if(!selected||!deleteReason.trim())return;try{const payload=await operationsFetch<any>('/api/operations',{method:'POST',body:JSON.stringify({action:'delete_vehicle',vehicleId:selected.id,reason:deleteReason})});setMessage(payload.message);setDeleteOpen(false);setSelected(null);setDeleteReason('');await load();}catch(e){setError(e instanceof Error?e.message:'تعذر مسح السيارة');}}
  const totalPages=Math.max(1,Math.ceil(total/25));
  const approvalLabel=useMemo(()=>detail?.approvals?.find((item:any)=>item.is_current)||null,[detail]);
  return <div className="module-page operations-page">
    <section className="panel operations-toolbar"><div className="operations-search"><MagnifyingGlass size={19}/><input value={search} onChange={(e)=>setSearch(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter')void load(1);}} placeholder="بحث جزئي برقم الهيكل أو السيارة أو البيان"/></div><select value={location} onChange={(e)=>setLocation(e.target.value)}><option value="">كل الأماكن</option>{meta.locations.map((item)=><option key={item.id} value={item.code}>{item.name}</option>)}</select><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">كل الحالات</option>{meta.statuses.map((item)=><option key={item.code} value={item.code}>{item.name}</option>)}</select><button type="button" onClick={()=>void load(1)}><MagnifyingGlass size={17}/>بحث</button><button type="button" className="secondary" onClick={()=>void exportRows()}><FileXls size={18}/>تصدير Excel</button><button type="button" className="secondary" onClick={()=>void load()}><ArrowClockwise size={18} className={loading?'spin':''}/>تحديث</button></section>
    {error?<div className="connection-banner"><WarningCircle size={20}/><span>{error}</span></div>:null}{message?<div className="success-banner"><span>{message}</span></div>:null}
    <section className="panel operations-list-panel"><div className="operations-panel-title"><div><h2>مخزون السيارات</h2><p>المصدر الفعلي للسيارات والحالات والمواقع وارتباط التراكينج.</p></div><strong>{total.toLocaleString('ar-SA')}</strong></div><VehicleTable rows={rows} onOpen={(row)=>void openVehicle(row)}/>{loading?<div className="operations-loading">جاري التحميل...</div>:null}<div className="operations-pagination"><button disabled={page<=1} onClick={()=>void load(page-1)}>السابق</button><span>{page} / {totalPages}</span><button disabled={page>=totalPages} onClick={()=>void load(page+1)}>التالي</button></div></section>
    <OperationsModal open={Boolean(selected)} title={selected?`تفاصيل السيارة — ${selected.vin}`:''} onClose={()=>{setSelected(null);setDetail(null);}} className="operations-wide-modal">{detailLoading?<div className="operations-loading">جاري تحميل التفاصيل...</div>:detail?<div className="vehicle-detail-content"><section className="vehicle-detail-grid"><div><small>رقم الهيكل</small><strong>{detail.vehicle.vin}</strong></div><div><small>السيارة</small><strong>{detail.vehicle.car_name||'—'}</strong></div><div><small>البيان</small><strong>{detail.vehicle.statement||'—'}</strong></div><div><small>الوكيل</small><strong>{detail.vehicle.agent_name||'—'}</strong></div><div><small>الموديل</small><strong>{detail.vehicle.model_year||'—'}</strong></div><div><small>المكان</small><strong>{detail.vehicle.location_name||'—'}</strong></div><div><small>الحالة</small><strong>{detail.vehicle.status_name||'—'}</strong></div><div><small>الفرع</small><strong>{detail.vehicle.branch_name||'—'}</strong></div><div><small>الموافقة المالية</small><strong>{approvalLabel?.financial_approved?'تمت':'لم تتم'}</strong></div><div><small>الموافقة الإدارية</small><strong>{approvalLabel?.administrative_approved?'تمت':'لم تتم'}</strong></div></section><section className="detail-subsection"><h3>سجل الحركات</h3>{detail.movements?.length?<div className="simple-history">{detail.movements.slice(0,12).map((item:any)=><div key={item.id}><strong>{item.from_location_name||'—'} ← {item.to_location_name||'—'}</strong><span>{formatDate(item.created_at)} — {item.performed_by_name||'—'}</span></div>)}</div>:<p className="empty-note">لا توجد حركات.</p>}</section><section className="detail-subsection"><h3>طلبات التراكينج</h3>{detail.tracking?.length?<div className="simple-history">{detail.tracking.map((item:any)=><div key={item.id}><strong>{item.sales_order_no}</strong><span>{item.status} — {formatDate(item.updated_at)}</span></div>)}</div>:<p className="empty-note">لا يوجد طلب تراكينج.</p>}</section><div className="operations-detail-actions">{canArchive?<button type="button" onClick={()=>void archiveVehicle(detail.vehicle.archived_at?'restore':'archive')}><Archive size={18}/>{detail.vehicle.archived_at?'استعادة من الأرشيف':'أرشفة السيارة'}</button>:null}{canDelete?<button type="button" className="danger" onClick={()=>setDeleteOpen(true)}><Trash size={18}/>مسح السيارة</button>:null}</div></div>:null}</OperationsModal>
    <OperationsModal open={deleteOpen} title="تأكيد مسح السيارة" onClose={()=>setDeleteOpen(false)}><div className="danger-confirm"><Trash size={42}/><p>سيتم حذف السيارة <strong>{selected?.vin}</strong> حذفًا فيزيائيًا فقط إذا لم يكن لها أي تاريخ تشغيلي.</p><label><span>سبب المسح</span><textarea value={deleteReason} onChange={(e)=>setDeleteReason(e.target.value)} /></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setDeleteOpen(false)}>إلغاء</button><button type="button" className="danger" disabled={!deleteReason.trim()} onClick={()=>void deleteVehicle()}>تأكيد المسح</button></div></div></OperationsModal>
  </div>;
}
