import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { DownloadSimple, Funnel, MagnifyingGlass, SpinnerGap } from "@phosphor-icons/react";
import { downloadExcel, formatOperationsDate, operationsFetch, operationsQuery, statusLabel } from "../api";
import type { OperationsMeta, VehicleRow } from "../types";
import { StickyHorizontalScroll } from "../components/StickyHorizontalScroll";
import { VehicleDetailDrawer } from "../components/VehicleDetailDrawer";

type Props={archivedOnly?:boolean;compact?:boolean};
export function InventoryPage({archivedOnly=false,compact=false}:Props){
  const [meta,setMeta]=useState<OperationsMeta>({locations:[],statuses:[],checklist:[]});const[rows,setRows]=useState<VehicleRow[]>([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(1);const[pageSize]=useState(50);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[selectedVehicleId,setSelectedVehicleId]=useState<string|null>(null);const[exporting,setExporting]=useState(false);
  const [filters,setFilters]=useState({search:"",location:"",status:"",model:"",agent:""});const tableRef=useRef<HTMLDivElement|null>(null);
  useEffect(()=>{operationsFetch<OperationsMeta&{ok:boolean}>("/api/operations?resource=meta").then(setMeta).catch((e)=>setError((e as Error).message));},[]);
  const query=useMemo(()=>({resource:"vehicles",...filters,archived:archivedOnly,page,pageSize}),[filters,archivedOnly,page,pageSize]);
  const load=useCallback(()=>{setLoading(true);setError("");operationsFetch<{rows:VehicleRow[];total:number}>(`/api/operations${operationsQuery(query)}`).then((p)=>{setRows(p.rows);setTotal(p.total);}).catch((e)=>setError((e as Error).message)).finally(()=>setLoading(false));},[JSON.stringify(query)]);
  useEffect(()=>{const timer=window.setTimeout(load,filters.search?300:0);return()=>window.clearTimeout(timer);},[load,filters.search]);
  const updateFilter=(key:keyof typeof filters,value:string)=>{setPage(1);setFilters((current)=>({...current,[key]:value}));};
  const exportCurrent=async()=>{setExporting(true);setError("");try{const payload=await operationsFetch<{rows:VehicleRow[]}>(`/api/operations${operationsQuery({resource:"vehicles",...filters,archived:archivedOnly,exportAll:true,page:1,pageSize:200})}`);downloadExcel(`MZJ-Operations-${archivedOnly?"Archive":"Inventory"}-${new Date().toISOString().slice(0,10)}`,compact?["VIN","السيارة","الوصف","الموديل","المكان","الحالة"]:["VIN","السيارة","البيان","الوكيل","اللون الداخلي","اللون الخارجي","الموديل","اللوحة","اسم الدفعة بالتاريخ","المكان","ملاحظات في السيارة","حجز - نواقص - تحديد مكان","الحالة","Tracking","الموافقة المالية","الموافقة الإدارية","الأرشيف"],payload.rows.map((row)=>compact?[row.vin,row.car_name,row.statement,row.model_year,row.location_name,row.status_name||statusLabel(row.status_code)]:[row.vin,row.car_name,row.statement,row.agent_name,row.interior_color,row.exterior_color,row.model_year,row.plate_no,row.batch_no,row.location_name,row.notes,row.missing_reservation_location,row.status_name||statusLabel(row.status_code),row.tracking_order_id?`${row.tracking_status} - ${row.tracking_progress||0}%`:"لا يوجد طلب",row.financial_approved?"تمت":"لم تتم",row.administrative_approved?"تمت":"لم تتم",row.is_archived?"مؤرشفة":"نشطة"]));}catch(e){setError((e as Error).message);}finally{setExporting(false);}};
  const pages=Math.max(1,Math.ceil(total/pageSize));
  return <section className="operations-page panel">
    <header className="operations-page-title"><div><span>{archivedOnly?"السجلات المحفوظة":compact?"تقرير مجمع":"المخزون التشغيلي"}</span><h2>{archivedOnly?"أرشيف السيارات":compact?"جميع السيارات":"مخزون السيارات"}</h2><p>{archivedOnly?"عرض السيارات المؤرشفة دون حذف تاريخها.":"بحث وفلترة من السيرفر مع حالة التراكينج والموافقات."}</p></div><button type="button" className="operations-primary-button" onClick={()=>void exportCurrent()} disabled={exporting}><DownloadSimple size={18}/>{exporting?"جاري التصدير...":"تصدير النتائج الحالية إلى Excel"}</button></header>
    <div className="operations-filter-bar"><label className="wide"><MagnifyingGlass size={17}/><input value={filters.search} onChange={(e)=>updateFilter("search",e.target.value)} placeholder="VIN أو السيارة أو الوصف أو الموديل أو اللون"/></label><label><Funnel size={16}/><select value={filters.location} onChange={(e)=>updateFilter("location",e.target.value)}><option value="">كل الأماكن</option>{meta.locations.map((item)=><option key={item.id} value={item.code}>{item.name}</option>)}</select></label><label><select value={filters.status} onChange={(e)=>updateFilter("status",e.target.value)}><option value="">كل الحالات</option>{meta.statuses.map((item)=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label><label><input value={filters.model} onChange={(e)=>updateFilter("model",e.target.value)} placeholder="الموديل"/></label><label><input value={filters.agent} onChange={(e)=>updateFilter("agent",e.target.value)} placeholder="الوكيل"/></label></div>
    <div className="operations-list-meta"><b>{total.toLocaleString("ar-SA")} نتيجة</b><span>صفحة {page.toLocaleString("ar-SA")} من {pages.toLocaleString("ar-SA")}</span></div>
    {error?<div className="operations-error">{error}</div>:null}
    <StickyHorizontalScroll targetRef={tableRef}/>
    <div className="operations-table-wrap" ref={tableRef}><table className={compact?"operations-table compact":"operations-table inventory-table"}><thead><tr>{compact?<><th>VIN</th><th>السيارة</th><th>الوصف</th><th>الموديل</th><th>المكان</th><th>الحالة</th></>:<><th>VIN</th><th>السيارة</th><th>البيان</th><th>الوكيل</th><th>اللون الداخلي</th><th>اللون الخارجي</th><th>الموديل</th><th>اللوحة</th><th>اسم الدفعة بالتاريخ</th><th>المكان</th><th>ملاحظات في السيارة</th><th>حجز - نواقص - تحديد مكان</th><th>الحالة</th><th>Tracking</th><th>الموافقات</th><th>التشيك</th><th>طلبات النقل</th><th>الأرشيف</th></>}</tr></thead><tbody>{loading?<tr><td colSpan={compact?6:18}><div className="operations-loading"><SpinnerGap className="spin" size={22}/>جاري تحميل السيارات...</div></td></tr>:rows.length?rows.map((row)=><tr key={row.id}>
      <td><button type="button" className="vin-link" onClick={()=>setSelectedVehicleId(row.id)}>{row.vin}</button></td><td>{row.car_name||"—"}</td><td>{row.statement||"—"}</td>{compact?null:<><td>{row.agent_name||"—"}</td><td>{row.interior_color||"—"}</td><td>{row.exterior_color||"—"}</td></>}<td>{row.model_year||"—"}</td>{compact?null:<><td>{row.plate_no||"—"}</td><td>{row.batch_no||"—"}</td></>}<td>{row.location_name||"—"}</td>{compact?null:<><td className="notes-cell">{row.notes||"—"}</td><td className="notes-cell">{row.missing_reservation_location||"—"}</td></>}<td><span className={`operations-status status-${row.status_code}`}>{row.status_name||statusLabel(row.status_code)}</span></td>{compact?null:<><td>{row.tracking_order_id?<button type="button" className="tracking-pill" onClick={()=>setSelectedVehicleId(row.id)}><b>{row.tracking_progress||0}%</b><span>{row.tracking_status||"—"}</span></button>:<span className="operations-muted-pill">لا يوجد طلب</span>}</td><td><div className="approval-dots"><span className={row.financial_approved?"done":""}>مالي</span><span className={row.administrative_approved?"done":""}>إداري</span></div></td><td><button type="button" className="operations-link-button" onClick={()=>setSelectedVehicleId(row.id)}>عرض</button></td><td><button type="button" className="operations-link-button" onClick={()=>setSelectedVehicleId(row.id)}>الطلبات</button></td><td>{row.is_archived?<span className="operations-status archived">{formatOperationsDate(row.archived_at)}</span>:"—"}</td></>}</tr>):<tr><td colSpan={compact?6:18}><div className="operations-empty-inline">لا توجد سيارات مطابقة للفلاتر.</div></td></tr>}</tbody></table></div>
    <div className="operations-pagination"><button type="button" disabled={page<=1||loading} onClick={()=>setPage((v)=>v-1)}>السابق</button><span>{page} / {pages}</span><button type="button" disabled={page>=pages||loading} onClick={()=>setPage((v)=>v+1)}>التالي</button></div>
    <VehicleDetailDrawer vehicleId={selectedVehicleId} onClose={()=>setSelectedVehicleId(null)} onArchived={load}/>
  </section>;
}
