import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowsCounterClockwise, DownloadSimple, Funnel, MagnifyingGlass, SpinnerGap, Trash, WarningCircle, X } from "@phosphor-icons/react";
import { useEscapeToClose } from "../../components/useEscapeToClose";
import { useAuth } from "../../auth/AuthContext";
import { downloadExcel, formatOperationsDate, notifyOperationsChanged, OperationsApiError, operationsFetch, operationsQuery, statusLabel } from "../api";
import type { OperationsMeta, VehicleRow } from "../types";
import { StickyHorizontalScroll } from "../components/StickyHorizontalScroll";
import { VehicleDetailDrawer } from "../components/VehicleDetailDrawer";
import { type ResizableColumnDefinition, useResizableColumns } from "../components/useResizableColumns";

type Props={archivedOnly?:boolean;compact?:boolean};
const fullColumns:ResizableColumnDefinition[]=[
  {key:"vin",label:"VIN",defaultWidth:175,minWidth:125,maxWidth:340},{key:"car",label:"السيارة",defaultWidth:150,minWidth:100,maxWidth:300},{key:"statement",label:"البيان",defaultWidth:170,minWidth:110,maxWidth:360},{key:"agent",label:"الوكيل",defaultWidth:130,minWidth:90,maxWidth:260},{key:"interior",label:"اللون الداخلي",defaultWidth:115,minWidth:85,maxWidth:220},{key:"exterior",label:"اللون الخارجي",defaultWidth:115,minWidth:85,maxWidth:220},{key:"model",label:"الموديل",defaultWidth:90,minWidth:75,maxWidth:160},{key:"plate",label:"اللوحة",defaultWidth:120,minWidth:90,maxWidth:220},{key:"batch",label:"اسم الدفعة بالتاريخ",defaultWidth:165,minWidth:120,maxWidth:320},{key:"location",label:"المكان",defaultWidth:120,minWidth:90,maxWidth:220},{key:"notes",label:"ملاحظات في السيارة",defaultWidth:210,minWidth:130,maxWidth:440},{key:"missing",label:"حجز - نواقص - تحديد مكان",defaultWidth:210,minWidth:140,maxWidth:440},{key:"status",label:"الحالة",defaultWidth:145,minWidth:110,maxWidth:240},{key:"tracking",label:"Tracking",defaultWidth:150,minWidth:115,maxWidth:260},{key:"approvals",label:"الموافقات",defaultWidth:135,minWidth:110,maxWidth:230},{key:"check",label:"التشيك",defaultWidth:90,minWidth:75,maxWidth:150},{key:"requests",label:"طلبات النقل",defaultWidth:105,minWidth:90,maxWidth:180},{key:"archive",label:"الأرشيف",defaultWidth:130,minWidth:100,maxWidth:230},{key:"actions",label:"الإجراءات",defaultWidth:135,minWidth:110,maxWidth:220},
];
const compactColumns:ResizableColumnDefinition[]=[
  {key:"vin",label:"VIN",defaultWidth:180,minWidth:125,maxWidth:340},{key:"car",label:"السيارة",defaultWidth:180,minWidth:110,maxWidth:320},{key:"statement",label:"الوصف",defaultWidth:220,minWidth:130,maxWidth:420},{key:"model",label:"الموديل",defaultWidth:100,minWidth:75,maxWidth:160},{key:"location",label:"المكان",defaultWidth:140,minWidth:95,maxWidth:240},{key:"status",label:"الحالة",defaultWidth:150,minWidth:110,maxWidth:240},
];

export function InventoryPage({archivedOnly=false,compact=false}:Props){
  const{user}=useAuth();const canDelete=!archivedOnly&&!compact&&Boolean(user?.isSystemAdmin||user?.permissions.includes("operations.vehicle.delete"));
  const[meta,setMeta]=useState<OperationsMeta>({locations:[],statuses:[],checklist:[]});const[rows,setRows]=useState<VehicleRow[]>([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(1);const[pageSize]=useState(50);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[selectedVehicleId,setSelectedVehicleId]=useState<string|null>(null);const[exporting,setExporting]=useState(false);const[deleteVehicle,setDeleteVehicle]=useState<VehicleRow|null>(null);
  const[filters,setFilters]=useState({search:"",location:"",status:"",model:"",agent:""});const tableRef=useRef<HTMLDivElement|null>(null);
  const columns=useMemo(()=>compact?compactColumns:canDelete?fullColumns:fullColumns.filter((column)=>column.key!=="actions"),[compact,canDelete]);
  const{widths,totalWidth,beginResize,autoFit,resetWidths}=useResizableColumns(`mzj.operations.inventory.columns.${compact?"compact":archivedOnly?"archive":"main"}`,columns,tableRef);
  useEffect(()=>{operationsFetch<OperationsMeta&{ok:boolean}>("/api/operations?resource=meta").then(setMeta).catch((e)=>setError((e as Error).message));},[]);
  const query=useMemo(()=>({resource:"vehicles",...filters,archived:archivedOnly,page,pageSize}),[filters,archivedOnly,page,pageSize]);
  const load=useCallback(()=>{setLoading(true);setError("");operationsFetch<{rows:VehicleRow[];total:number}>(`/api/operations${operationsQuery(query)}`).then((payload)=>{setRows(payload.rows);setTotal(payload.total);}).catch((e)=>setError((e as Error).message)).finally(()=>setLoading(false));},[JSON.stringify(query)]);
  useEffect(()=>{const timer=window.setTimeout(load,filters.search?300:0);return()=>window.clearTimeout(timer);},[load,filters.search]);
  const updateFilter=(key:keyof typeof filters,value:string)=>{setPage(1);setFilters((current)=>({...current,[key]:value}));};
  const exportCurrent=async()=>{setExporting(true);setError("");try{const payload=await operationsFetch<{rows:VehicleRow[]}>(`/api/operations${operationsQuery({resource:"vehicles",...filters,archived:archivedOnly,exportAll:true,page:1,pageSize:200})}`);downloadExcel(`MZJ-Operations-${archivedOnly?"Archive":"Inventory"}-${new Date().toISOString().slice(0,10)}`,compact?["VIN","السيارة","الوصف","الموديل","المكان","الحالة"]:["VIN","السيارة","البيان","الوكيل","اللون الداخلي","اللون الخارجي","الموديل","اللوحة","اسم الدفعة بالتاريخ","المكان","ملاحظات في السيارة","حجز - نواقص - تحديد مكان","الحالة","Tracking","الموافقة المالية","الموافقة الإدارية","الأرشيف"],payload.rows.map((row)=>compact?[row.vin,row.car_name,row.statement,row.model_year,row.location_name,row.status_name||statusLabel(row.status_code)]:[row.vin,row.car_name,row.statement,row.agent_name,row.interior_color,row.exterior_color,row.model_year,row.plate_no,row.batch_no,row.location_name,row.notes,row.missing_reservation_location,row.status_name||statusLabel(row.status_code),row.tracking_order_id?`${row.tracking_status} - ${row.tracking_progress||0}%`:"لا يوجد طلب",row.financial_approved?"تمت":"لم تتم",row.administrative_approved?"تمت":"لم تتم",row.is_archived?"مؤرشفة":"نشطة"]));}catch(e){setError((e as Error).message);}finally{setExporting(false);}};
  const pages=Math.max(1,Math.ceil(total/pageSize));
  const cell=(key:string,content:React.ReactNode,className?:string)=><td data-column-key={key} className={className}>{content}</td>;
  return <section className="operations-page panel inventory-page">
    <header className="operations-page-title"><div><span>{archivedOnly?"السجلات المحفوظة":compact?"تقرير مجمع":"المخزون التشغيلي"}</span><h2>{archivedOnly?"أرشيف السيارات":compact?"جميع السيارات":"مخزون السيارات"}</h2><p>{archivedOnly?"عرض السيارات المؤرشفة دون حذف تاريخها.":"بحث وفلترة من السيرفر مع حالة التراكينج والموافقات."}</p></div><div className="operations-title-actions"><button type="button" className="operations-secondary-button" onClick={resetWidths}><ArrowsCounterClockwise size={17}/>إعادة ضبط الأعمدة</button><button type="button" className="operations-primary-button" onClick={()=>void exportCurrent()} disabled={exporting}><DownloadSimple size={18}/>{exporting?"جاري التصدير...":"تصدير النتائج الحالية إلى Excel"}</button></div></header>
    <div className="operations-sticky-filter-stack"><div className="operations-filter-bar"><label className="wide"><MagnifyingGlass size={17}/><input value={filters.search} onChange={(e)=>updateFilter("search",e.target.value)} placeholder="VIN أو السيارة أو الوصف أو الموديل أو اللون"/></label><label><Funnel size={16}/><select value={filters.location} onChange={(e)=>updateFilter("location",e.target.value)}><option value="">كل الأماكن</option>{meta.locations.map((item)=><option key={item.id} value={item.code}>{item.name}</option>)}</select></label><label><select value={filters.status} onChange={(e)=>updateFilter("status",e.target.value)}><option value="">كل الحالات</option>{meta.statuses.map((item)=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label><label><input value={filters.model} onChange={(e)=>updateFilter("model",e.target.value)} placeholder="الموديل"/></label><label><input value={filters.agent} onChange={(e)=>updateFilter("agent",e.target.value)} placeholder="الوكيل"/></label></div><div className="operations-list-meta"><b>{total.toLocaleString("ar-SA")} نتيجة</b><span>صفحة {page.toLocaleString("ar-SA")} من {pages.toLocaleString("ar-SA")}</span></div><StickyHorizontalScroll targetRef={tableRef}/></div>
    {error?<div className="operations-error">{error}</div>:null}
    <div className="operations-table-wrap inventory-scroll-area" ref={tableRef}><table className={compact?"operations-table compact resizable-table":"operations-table inventory-table resizable-table"} style={{width:totalWidth,minWidth:totalWidth}}><colgroup>{columns.map((column)=><col key={column.key} style={{width:widths[column.key]}}/>)}</colgroup><thead><tr>{columns.map((column)=><th key={column.key} data-column-key={column.key} style={{width:widths[column.key],minWidth:column.minWidth,maxWidth:column.maxWidth}}><span>{column.label}</span><i role="separator" aria-label={`تغيير عرض عمود ${column.label}`} className="column-resize-handle" onPointerDown={(event)=>beginResize(event,column.key)} onDoubleClick={()=>autoFit(column.key)}/></th>)}</tr></thead><tbody>{loading?<tr><td colSpan={columns.length}><div className="operations-loading"><SpinnerGap className="spin" size={22}/>جاري تحميل السيارات...</div></td></tr>:rows.length?rows.map((row)=><tr key={row.id}>
      {cell("vin",<button type="button" className="vin-link" onClick={()=>setSelectedVehicleId(row.id)}>{row.vin}</button>)}{cell("car",row.car_name||"—")}{cell("statement",row.statement||"—",compact?undefined:"notes-cell")}{compact?null:<>{cell("agent",row.agent_name||"—")}{cell("interior",row.interior_color||"—")}{cell("exterior",row.exterior_color||"—")}</>}{cell("model",row.model_year||"—")}{compact?null:<>{cell("plate",row.plate_no||"—")}{cell("batch",row.batch_no||"—")}</>}{cell("location",row.location_name||"—")}{compact?null:<>{cell("notes",row.notes||"—","notes-cell")}{cell("missing",row.missing_reservation_location||"—","notes-cell")}</>}{cell("status",<span className={`operations-status status-${row.status_code}`}>{row.status_name||statusLabel(row.status_code)}</span>)}{compact?null:<>{cell("tracking",row.tracking_order_id?<button type="button" className="tracking-pill" onClick={()=>setSelectedVehicleId(row.id)}><b>{row.tracking_progress||0}%</b><span>{row.tracking_status||"—"}</span></button>:<span className="operations-muted-pill">لا يوجد طلب</span>)}{cell("approvals",<div className="approval-dots"><span className={row.financial_approved?"done":""}>مالي</span><span className={row.administrative_approved?"done":""}>إداري</span></div>)}{cell("check",<button type="button" className="operations-link-button" onClick={()=>setSelectedVehicleId(row.id)}>عرض</button>)}{cell("requests",<button type="button" className="operations-link-button" onClick={()=>setSelectedVehicleId(row.id)}>الطلبات</button>)}{cell("archive",row.is_archived?<span className="operations-status archived">{formatOperationsDate(row.archived_at)}</span>:"—")}{canDelete?cell("actions",<button type="button" className="vehicle-delete-action" onClick={()=>setDeleteVehicle(row)}><Trash size={15}/>مسح السيارة</button>):null}</>}</tr>):<tr><td colSpan={columns.length}><div className="operations-empty-inline">لا توجد سيارات مطابقة للفلاتر.</div></td></tr>}</tbody></table></div>
    <div className="operations-pagination"><button type="button" disabled={page<=1||loading} onClick={()=>setPage((value)=>value-1)}>السابق</button><span>{page} / {pages}</span><button type="button" disabled={page>=pages||loading} onClick={()=>setPage((value)=>value+1)}>التالي</button></div>
    <VehicleDetailDrawer vehicleId={selectedVehicleId} onClose={()=>setSelectedVehicleId(null)} onArchived={()=>{void load();notifyOperationsChanged({entity:"vehicle"});}}/>
    {deleteVehicle?<DeleteVehicleModal vehicle={deleteVehicle} onClose={()=>setDeleteVehicle(null)} onDeleted={()=>{setDeleteVehicle(null);void load();notifyOperationsChanged({entity:"vehicle",action:"deleted"});}}/>:null}
  </section>;
}

function DeleteVehicleModal({vehicle,onClose,onDeleted}:{vehicle:VehicleRow;onClose:()=>void;onDeleted:()=>void}){
  const[reason,setReason]=useState("");const[confirmed,setConfirmed]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[relations,setRelations]=useState<Array<{label:string;count:number}>>([]);useEscapeToClose(!saving,onClose);
  const submit=async()=>{setSaving(true);setError("");setRelations([]);try{await operationsFetch("/api/operations",{method:"POST",body:JSON.stringify({action:"delete_vehicle",vehicleId:vehicle.id,reason})});onDeleted();}catch(failure){const apiError=failure as OperationsApiError;setError(apiError.message);const raw=apiError.details?.relations;if(Array.isArray(raw))setRelations(raw.filter((item):item is {label:string;count:number}=>Boolean(item)&&typeof item==="object"&&"label" in item&&"count" in item));}finally{setSaving(false);}};
  return <div className="drawer-backdrop" onMouseDown={saving?undefined:onClose}><div className="operations-confirm-modal vehicle-delete-modal" onMouseDown={(event)=>event.stopPropagation()}><header><div><WarningCircle size={28}/><span><small>إجراء نهائي عالي الخطورة</small><h2>مسح السيارة</h2></span></div><button type="button" className="icon-button" onClick={onClose} disabled={saving}><X size={20}/></button></header><div className="operations-confirm-body"><div className="delete-vehicle-identity"><small>VIN</small><strong>{vehicle.vin}</strong><small>السيارة</small><strong>{vehicle.car_name||"—"}</strong></div><p>يسمح السيرفر بالمسح الفيزيائي فقط إذا لم توجد أي حركات أو موافقات أو طلبات نقل أو Tracking أو أرشيف أو سجلات تشغيلية مرتبطة. عند وجود أي سجل سيُرفض المسح ويجب استخدام الأرشفة.</p>{error?<div className="operations-error">{error}</div>:null}{relations.length?<div className="vehicle-delete-relations">{relations.map((relation)=><span key={relation.label}>{relation.label}<b>{relation.count}</b></span>)}</div>:null}<label><span>سبب المسح *</span><textarea value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="اكتب سببًا واضحًا ليظهر في Audit Trail"/></label><label className="danger-confirm-check"><input type="checkbox" checked={confirmed} onChange={(event)=>setConfirmed(event.target.checked)}/><span>أؤكد أنني أريد مسح هذه السيارة نهائيًا بعد تحقق السيرفر من عدم وجود أي تاريخ مرتبط.</span></label></div><footer><button type="button" className="operations-secondary-button" onClick={onClose} disabled={saving}>إلغاء</button><button type="button" className="operations-danger-button" disabled={saving||!confirmed||!reason.trim()} onClick={()=>void submit()}>{saving?<SpinnerGap className="spin" size={18}/>:<Trash size={18}/>} {saving?"جاري التحقق والمسح...":"تأكيد مسح السيارة"}</button></footer></div></div>;
}
