import { useMemo,useState } from "react";
import { ArrowsLeftRight,Stack,WarningCircle } from "@phosphor-icons/react";
import { operationsFetch } from "../api";
import type { OperationsMeta,VehicleRow } from "../types";
import { VehicleSearchPicker } from "../components/VehicleSearchPicker";

type Draft={note:string;statusNote:string;shortageNote:string;placeNote:string;checks:Record<string,boolean>};
const createDraft=(vehicle:VehicleRow):Draft=>({note:"",statusNote:"",shortageNote:vehicle.booking_shortage_location_notes||"",placeNote:vehicle.place_notes||"",checks:{...(vehicle.check_items||{})}});
export function MovementPage({bulk,meta,notify}:{bulk:boolean;meta:OperationsMeta;notify:(message:string,error?:boolean)=>void}){
  const [selected,setSelected]=useState<VehicleRow[]>([]);const [drafts,setDrafts]=useState<Record<string,Draft>>({});const [destinationLocationId,setDestinationLocationId]=useState("");const [statusCode,setStatusCode]=useState("");const [generalNote,setGeneralNote]=useState("");const [saving,setSaving]=useState(false);
  const status=useMemo(()=>meta.statuses.find(item=>item.code===statusCode),[meta.statuses,statusCode]);
  function add(vehicle:VehicleRow){if(!bulk&&selected.length)return notify("الحركة الفردية تقبل سيارة واحدة فقط",true);if(selected.some(item=>item.id===vehicle.id))return;setSelected([...selected,vehicle]);setDrafts({...drafts,[vehicle.id]:createDraft(vehicle)});}
  function remove(id:string){setSelected(selected.filter(item=>item.id!==id));const next={...drafts};delete next[id];setDrafts(next)}
  function update(id:string,patch:Partial<Draft>){setDrafts(current=>({...current,[id]:{...current[id],...patch}}))}
  async function submit(){if(!selected.length||!destinationLocationId||!statusCode)return notify("اختر السيارة والمكان الجديد والحالة الجديدة",true);for(const vehicle of selected){if(statusCode==="has_notes"&&!drafts[vehicle.id]?.statusNote.trim())return notify(`ملاحظات الحالة مطلوبة للسيارة ${vehicle.vin}`,true)}setSaving(true);try{const payload=await operationsFetch<{message:string}>("movements",{method:"POST",body:JSON.stringify({destinationLocationId,statusCode,generalNote,idempotencyKey:crypto.randomUUID(),items:selected.map(vehicle=>({vehicleId:vehicle.id,version:vehicle.version,...drafts[vehicle.id]}))})});notify(payload.message);setSelected([]);setDrafts({});setDestinationLocationId("");setStatusCode("");setGeneralNote("");}catch(err){notify(err instanceof Error?err.message:"فشلت الحركة",true)}finally{setSaving(false)}}
  return <div className="operations-page"><header className="operations-page-toolbar"><div><h2>{bulk?"إنشاء حركة لأكثر من سيارة إلى مكان واحد":"حركة سيارة"}</h2><p>{bulk?"كل سيارة لها State وتشيك وملاحظات مستقلة، وفشل سيارة واحدة يلغي الحركة كلها.":"ابحث عن السيارة بجزء من VIN ثم نفّذ الحركة داخل Transaction واحدة."}</p></div>{bulk?<Stack size={30}/>:<ArrowsLeftRight size={30}/>}</header>
    <section className="operations-panel"><VehicleSearchPicker selected={selected} onAdd={add} onRemove={remove} multiple={bulk}/></section>
    {selected.length?<><section className="operations-panel operations-form"><div className="operations-form-grid"><label><span>المكان الجديد لجميع السيارات *</span><select value={destinationLocationId} onChange={e=>setDestinationLocationId(e.target.value)}><option value="">اختر المكان</option>{meta.locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>الحالة الجديدة *</span><select value={statusCode} onChange={e=>setStatusCode(e.target.value)}><option value="">اختر الحالة</option>{meta.statuses.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label><label className="wide"><span>ملاحظات عامة للحركة</span><textarea rows={3} value={generalNote} onChange={e=>setGeneralNote(e.target.value)}/></label></div>{status?.requires_approvals||status?.is_final?<div className="operations-info"><WarningCircle size={18}/>سيعيد الـAPI التحقق من الموافقة المالية والإدارية لكل سيارة قبل التنفيذ.</div>:null}</section>
      <div className="operations-movement-cards">{selected.map(vehicle=>{const draft=drafts[vehicle.id]||createDraft(vehicle);const agency=vehicle.location_code==="agency";return <article key={vehicle.id} className="operations-panel movement-card"><header><div><strong>{vehicle.vin}</strong><span>{vehicle.car_name||"—"} • {vehicle.statement||"—"}</span></div><div><small>المكان الحالي</small><b>{vehicle.location_name||"—"}</b><small>الحالة الحالية</small><b>{vehicle.status_name||"—"}</b></div></header><div className="operations-form-grid"><label className="wide"><span>ملاحظة هذه السيارة</span><textarea rows={2} value={draft.note} onChange={e=>update(vehicle.id,{note:e.target.value})}/></label>{statusCode==="has_notes"?<label className="wide"><span>ملاحظات الحالة لهذه السيارة *</span><textarea required rows={2} value={draft.statusNote} onChange={e=>update(vehicle.id,{statusNote:e.target.value})}/></label>:null}<label><span>حجز - نواقص - تحديد مكان</span><textarea rows={2} value={draft.shortageNote} onChange={e=>update(vehicle.id,{shortageNote:e.target.value})}/></label><label><span>ملاحظات المكان</span><textarea rows={2} value={draft.placeNote} onChange={e=>update(vehicle.id,{placeNote:e.target.value})}/></label></div>{agency?<div><h4>تشيك مستقل للسيارة — مكانها الحالي الوكالة</h4><div className="operations-check-grid">{meta.checkItems.map(item=><label key={item.code}><input type="checkbox" checked={Boolean(draft.checks[item.code])} onChange={e=>update(vehicle.id,{checks:{...draft.checks,[item.code]:e.target.checked}})}/><span>{item.name}</span></label>)}</div></div>:<div className="operations-info muted"><WarningCircle size={17}/>التشيك غير ظاهر لأن المكان الحالي ليس الوكالة، وستظل بياناته القديمة محفوظة دون تصفير.</div>}</article>})}</div><div className="operations-form-actions sticky"><button type="button" className="primary" disabled={saving} onClick={()=>void submit()}>{saving?"جاري تنفيذ Transaction...":bulk?`تنفيذ الحركة لعدد ${selected.length} سيارة`:"تنفيذ الحركة"}</button></div></>:<div className="operations-empty large">ابدأ بالبحث عن السيارة واختيارها.</div>}
  </div>;
}
