import { useCallback, useEffect, useState } from "react";
import { DownloadSimple, MagnifyingGlass, SpinnerGap } from "@phosphor-icons/react";
import { downloadExcel, formatOperationsDate, operationsFetch, operationsQuery, statusLabel } from "../api";
import type { OperationsMeta } from "../types";

type Movement=Record<string,unknown>&{id:string;vin:string;car_name:string;statement:string;model_year:string;from_location_name:string;to_location_name:string;old_status:string;new_status:string;performed_by_name:string;performed_by_branch:string;status_note:string;missing_reservation_location:string;note:string;request_id:string;batch_id:string;created_at:string};
export function MovementLogPage(){
  const[meta,setMeta]=useState<OperationsMeta>({locations:[],statuses:[],checklist:[]});const[rows,setRows]=useState<Movement[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[filters,setFilters]=useState({search:"",fromDate:"",toDate:"",fromLocation:"",toLocation:""});
  useEffect(()=>{operationsFetch<OperationsMeta&{ok:boolean}>("/api/operations?resource=meta").then(setMeta).catch(()=>undefined);},[]);
  const load=useCallback(()=>{setLoading(true);setError("");operationsFetch<{rows:Movement[]}>(`/api/operations${operationsQuery({resource:"movements",...filters})}`).then((p)=>setRows(p.rows)).catch((e)=>setError((e as Error).message)).finally(()=>setLoading(false));},[JSON.stringify(filters)]);useEffect(()=>{const t=window.setTimeout(load,filters.search?300:0);return()=>window.clearTimeout(t);},[load,filters.search]);
  const set=(key:keyof typeof filters,value:string)=>setFilters((c)=>({...c,[key]:value}));const exportRows=()=>downloadExcel("MZJ-Operations-Movements",["التاريخ","الوقت","VIN","السيارة","المكان السابق","المكان الجديد","الحالة السابقة","الحالة الجديدة","منفذ الحركة","فرع المستخدم","الملاحظات التاريخية","ملاحظات الحالة","حجز - نواقص - تحديد مكان","رقم الطلب","Batch ID"],rows.map((r)=>{const d=new Date(r.created_at);return[d.toLocaleDateString("ar-SA"),d.toLocaleTimeString("ar-SA"),r.vin,r.car_name,r.from_location_name,r.to_location_name,statusLabel(r.old_status),statusLabel(r.new_status),r.performed_by_name,r.performed_by_branch,r.note,r.status_note,r.missing_reservation_location,r.request_id,r.batch_id];}));
  return <section className="panel operations-page"><header className="operations-page-title"><div><span>Audit تشغيلي</span><h2>سجل الحركات</h2><p>كل سيارة لها سجل مستقل حتى عند تنفيذ الحركة ضمن Batch واحدة.</p></div><button type="button" className="operations-primary-button" onClick={exportRows}><DownloadSimple size={18}/>تصدير النتائج</button></header><div className="operations-filter-bar"><label className="wide"><MagnifyingGlass size={17}/><input value={filters.search} onChange={(e)=>set("search",e.target.value)} placeholder="VIN أو السيارة أو منفذ الحركة"/></label><label><span>من تاريخ</span><input type="date" value={filters.fromDate} onChange={(e)=>set("fromDate",e.target.value)}/></label><label><span>إلى تاريخ</span><input type="date" value={filters.toDate} onChange={(e)=>set("toDate",e.target.value)}/></label><label><select value={filters.fromLocation} onChange={(e)=>set("fromLocation",e.target.value)}><option value="">من أي مكان</option>{meta.locations.map((l)=><option key={l.id} value={l.code}>{l.name}</option>)}</select></label><label><select value={filters.toLocation} onChange={(e)=>set("toLocation",e.target.value)}><option value="">إلى أي مكان</option>{meta.locations.map((l)=><option key={l.id} value={l.code}>{l.name}</option>)}</select></label></div>{error?<div className="operations-error">{error}</div>:null}<div className="operations-table-wrap"><table className="operations-table movement-log-table"><thead><tr><th>التاريخ</th><th>VIN</th><th>السيارة</th><th>من</th><th>إلى</th><th>الحالة السابقة</th><th>الحالة الجديدة</th><th>منفذ الحركة</th><th>فرع المستخدم</th><th>الملاحظات التاريخية</th><th>ملاحظات الحالة</th><th>حجز - نواقص - تحديد مكان</th><th>رقم الطلب</th><th>Batch ID</th></tr></thead><tbody>{loading?<tr><td colSpan={14}><div className="operations-loading"><SpinnerGap className="spin" size={22}/>جاري تحميل السجل...</div></td></tr>:rows.length?rows.map((r)=><tr key={r.id}><td>{formatOperationsDate(r.created_at)}</td><td><b>{r.vin}</b></td><td>{r.car_name||"—"}</td><td>{r.from_location_name||"—"}</td><td>{r.to_location_name||"—"}</td><td>{statusLabel(r.old_status)}</td><td>{statusLabel(r.new_status)}</td><td>{r.performed_by_name||"—"}</td><td>{r.performed_by_branch||"—"}</td><td>{r.note||"—"}</td><td>{r.status_note||"—"}</td><td>{r.missing_reservation_location||"—"}</td><td>{r.request_id||"—"}</td><td>{r.batch_id||"—"}</td></tr>):<tr><td colSpan={14}><div className="operations-empty-inline">لا توجد حركات مطابقة.</div></td></tr>}</tbody></table></div></section>;
}
