import { useCallback,useEffect,useState } from "react";
import { DownloadSimple } from "@phosphor-icons/react";
import { operationsFetch } from "../api";
import { exportXlsx } from "../excel";
import type { MovementRow,OperationsMeta,Pagination as PaginationType } from "../types";
import { Pagination } from "../components/Pagination";
const emptyPagination:PaginationType={page:1,pageSize:40,total:0,pages:1};
const columns=[{key:"created_at",header:"التاريخ والوقت"},{key:"vin",header:"VIN"},{key:"car_name",header:"السيارة"},{key:"from_location_name",header:"المكان السابق"},{key:"to_location_name",header:"المكان الجديد"},{key:"old_status_name",header:"الحالة السابقة"},{key:"new_status_name",header:"الحالة الجديدة"},{key:"performer_name",header:"منفذ الحركة"},{key:"performer_branch",header:"فرع المستخدم"},{key:"note",header:"الملاحظات"},{key:"status_note",header:"ملاحظات الحالة"},{key:"shortage_note",header:"حجز - نواقص - تحديد مكان"},{key:"request_no",header:"رقم الطلب"},{key:"batch_id",header:"Batch ID"}] as const;
const fmt=(value?:string|null)=>value?new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";
export function MovementLogPage({meta,notify}:{meta:OperationsMeta;notify:(message:string,error?:boolean)=>void}){
 const [filters,setFilters]=useState({fromDate:"",toDate:"",fromTime:"",toTime:"",filterType:"vin",filterValue:"",performer:"",requestNo:"",branch:""});const [debounced,setDebounced]=useState("");const [rows,setRows]=useState<MovementRow[]>([]);const [pagination,setPagination]=useState(emptyPagination);const [page,setPage]=useState(1);const [loading,setLoading]=useState(true);const [exporting,setExporting]=useState(false);
 useEffect(()=>{const timer=window.setTimeout(()=>setDebounced(filters.filterValue),300);return()=>window.clearTimeout(timer)},[filters.filterValue]);
 const query=(p:number,size:number)=>({...filters,filterValue:debounced,page:p,pageSize:size});
 const load=useCallback(async()=>{setLoading(true);try{const payload=await operationsFetch<{movements:MovementRow[];pagination:PaginationType}>("movements",{query:query(page,40)});setRows(payload.movements||[]);setPagination(payload.pagination||emptyPagination)}catch(error){notify(error instanceof Error?error.message:"تعذر تحميل سجل الحركات",true)}finally{setLoading(false)}},[filters.fromDate,filters.toDate,filters.fromTime,filters.toTime,filters.filterType,filters.performer,filters.requestNo,filters.branch,debounced,page,notify]);
 useEffect(()=>{void load()},[load]);useEffect(()=>setPage(1),[debounced,filters.fromDate,filters.toDate,filters.fromTime,filters.toTime,filters.filterType,filters.performer,filters.requestNo,filters.branch]);
 async function download(){setExporting(true);try{const all:MovementRow[]=[];let current=1,pages=1;do{const payload=await operationsFetch<{movements:MovementRow[];pagination:PaginationType}>("movements",{query:query(current,200)});all.push(...payload.movements);pages=payload.pagination.pages;current+=1;}while(current<=pages);exportXlsx(all.map(row=>({...row,created_at:fmt(row.created_at)})) as any,columns as any,"MZJ-Operations-Movement-Log.xlsx","سجل الحركات");notify(`تم تصدير ${all.length} حركة`)}catch(error){notify(error instanceof Error?error.message:"تعذر تصدير السجل",true)}finally{setExporting(false)}}
 const filterControl=filters.filterType==="from"||filters.filterType==="to"?<select value={filters.filterValue} onChange={e=>setFilters({...filters,filterValue:e.target.value})}><option value="">اختر المكان</option>{meta.locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>:<input value={filters.filterValue} onChange={e=>setFilters({...filters,filterValue:e.target.value})} placeholder={filters.filterType==="vin"?"جزء من VIN":filters.filterType==="car"?"اسم السيارة":"قيمة البحث"}/>;
 return <div className="operations-page"><header className="operations-page-toolbar"><div><h2>سجل الحركات</h2><p>فلترة بالتاريخ والوقت وVIN والسيارة والمكان والمستخدم والفرع ورقم الطلب.</p></div><button type="button" disabled={exporting} onClick={()=>void download()}><DownloadSimple size={17}/>{exporting?"جاري التصدير...":"تصدير النتائج"}</button></header>
 <section className="operations-filters movement-log-filters"><label><span>من تاريخ</span><input type="date" value={filters.fromDate} onChange={e=>setFilters({...filters,fromDate:e.target.value})}/></label><label><span>إلى تاريخ</span><input type="date" value={filters.toDate} onChange={e=>setFilters({...filters,toDate:e.target.value})}/></label><label><span>من ساعة</span><input type="time" value={filters.fromTime} onChange={e=>setFilters({...filters,fromTime:e.target.value})}/></label><label><span>إلى ساعة</span><input type="time" value={filters.toTime} onChange={e=>setFilters({...filters,toTime:e.target.value})}/></label><label><span>قائمة الفلترة</span><select value={filters.filterType} onChange={e=>setFilters({...filters,filterType:e.target.value,filterValue:""})}><option value="vin">رقم الهيكل</option><option value="car">السيارة</option><option value="from">من</option><option value="to">إلى</option></select></label><label><span>قيمة الفلتر</span>{filterControl}</label><label><span>منفذ الحركة</span><input value={filters.performer} onChange={e=>setFilters({...filters,performer:e.target.value})}/></label><label><span>الفرع</span><input value={filters.branch} onChange={e=>setFilters({...filters,branch:e.target.value})}/></label><label><span>رقم الطلب</span><input value={filters.requestNo} onChange={e=>setFilters({...filters,requestNo:e.target.value})}/></label></section>
 {loading?<div className="operations-loading">جاري تحميل سجل الحركات...</div>:<><div className="operations-table-wrap"><table className="operations-table movement-log-table"><thead><tr><th>التاريخ</th><th>الوقت</th><th>VIN</th><th>السيارة</th><th>المكان السابق</th><th>المكان الجديد</th><th>الحالة السابقة</th><th>الحالة الجديدة</th><th>منفذ الحركة</th><th>فرع المستخدم</th><th>الملاحظات</th><th>ملاحظات الحالة</th><th>حجز - نواقص - تحديد مكان</th><th>رقم الطلب</th><th>Batch ID</th></tr></thead><tbody>{rows.length?rows.map(row=>{const date=new Date(row.created_at);return <tr key={row.id}><td>{new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium"}).format(date)}</td><td>{new Intl.DateTimeFormat("ar-SA",{timeStyle:"short"}).format(date)}</td><td className="mono">{row.vin}</td><td>{row.car_name||"—"}</td><td>{row.from_location_name||"—"}</td><td>{row.to_location_name||"—"}</td><td>{row.old_status_name||"—"}</td><td>{row.new_status_name||"—"}</td><td>{row.performer_name||"—"}</td><td>{row.performer_branch||"—"}</td><td>{row.note||"—"}</td><td>{row.status_note||"—"}</td><td>{row.shortage_note||"—"}</td><td>{row.request_no||"—"}</td><td className="mono">{row.batch_id||"—"}</td></tr>}):<tr><td colSpan={15} className="operations-empty">لا توجد حركات مطابقة</td></tr>}</tbody></table></div><Pagination value={pagination} onChange={setPage}/></>}
 </div>;
}
