import { useEffect, useState } from 'react';
import { FileXls, MagnifyingGlass, WarningCircle } from '@phosphor-icons/react';
import { formatDate, operationsFetch, operationsQuery, statusLabel } from '../api';
import { exportExcel } from '../excel';
import { useOperationsMeta } from '../OperationsLayout';
import type { MovementRow } from '../types';

export function MovementsLogPage(){const meta=useOperationsMeta();const [rows,setRows]=useState<MovementRow[]>([]);const [search,setSearch]=useState('');const [fromDate,setFromDate]=useState('');const [toDate,setToDate]=useState('');const [fromLocation,setFromLocation]=useState('');const [toLocation,setToLocation]=useState('');const [status,setStatus]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');
async function load(){setLoading(true);setError('');try{const payload=await operationsFetch<any>(`/api/operations${operationsQuery({resource:'movements',search,fromDate,toDate,fromLocation,toLocation,status,page:1,pageSize:5000})}`);setRows(payload.rows||[]);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل سجل الحركات');}finally{setLoading(false);}}
useEffect(()=>{void load();},[]);function exportRows(){exportExcel('سجل-الحركات',['التاريخ والوقت','رقم الهيكل','السيارة','من','إلى','الحالة السابقة','الحالة الجديدة','المنفذ','الفرع','الملاحظات','ملاحظات الحالة','حجز - نواقص - تحديد مكان','Batch ID','رقم الطلب'],rows.map((row)=>[formatDate(row.created_at),row.vin,row.car_name,row.from_location_name,row.to_location_name,statusLabel(row.old_status),statusLabel(row.new_status),row.performed_by_name,row.branch_name,row.note,row.status_note,row.shortage_location_note,row.batch_id,row.request_id]));}
return <div className="module-page operations-page"><section className="panel movement-log-filters"><div className="operations-search"><MagnifyingGlass size={18}/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="VIN أو السيارة أو المنفذ"/></div><label><span>من تاريخ</span><input type="date" value={fromDate} onChange={(e)=>setFromDate(e.target.value)}/></label><label><span>إلى تاريخ</span><input type="date" value={toDate} onChange={(e)=>setToDate(e.target.value)}/></label><select value={fromLocation} onChange={(e)=>setFromLocation(e.target.value)}><option value="">من كل الأماكن</option>{meta.locations.map((item)=><option key={item.id} value={item.code}>{item.name}</option>)}</select><select value={toLocation} onChange={(e)=>setToLocation(e.target.value)}><option value="">إلى كل الأماكن</option>{meta.locations.map((item)=><option key={item.id} value={item.code}>{item.name}</option>)}</select><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">كل الحالات الجديدة</option>{meta.statuses.map((item)=><option key={item.code} value={item.code}>{item.name}</option>)}</select><button onClick={()=>void load()}><MagnifyingGlass size={17}/>بحث</button><button className="secondary" onClick={exportRows}><FileXls size={17}/>تصدير Excel</button></section>{error?<div className="connection-banner"><WarningCircle size={20}/><span>{error}</span></div>:null}<section className="panel operations-list-panel"><div className="operations-panel-title"><div><h2>سجل الحركات</h2><p>كل حركة محفوظة بالحالة والمكان والمنفذ وBatch ID.</p></div><strong>{rows.length}</strong></div><div className="operations-table-scroll"><table className="operations-table"><thead><tr><th>التاريخ والوقت</th><th>VIN</th><th>السيارة</th><th>من</th><th>إلى</th><th>الحالة السابقة</th><th>الحالة الجديدة</th><th>المنفذ</th><th>الملاحظات</th><th>Batch ID</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={10} className="table-empty">لا توجد حركات مطابقة</td></tr>:rows.map((row)=><tr key={row.id}><td>{formatDate(row.created_at)}</td><td>{row.vin}</td><td>{row.car_name||'—'}</td><td>{row.from_location_name||'—'}</td><td>{row.to_location_name||'—'}</td><td>{statusLabel(row.old_status)}</td><td>{statusLabel(row.new_status)}</td><td>{row.performed_by_name||'—'}</td><td>{row.note||row.status_note||'—'}</td><td>{row.batch_id||'—'}</td></tr>)}</tbody></table></div>{loading?<div className="operations-loading">جاري التحميل...</div>:null}</section></div>;}
