import { useEffect, useState } from 'react';
import { ArrowsLeftRight, MagnifyingGlass, Plus, Trash, WarningCircle } from '@phosphor-icons/react';
import { operationsFetch, operationsQuery } from '../api';
import { useOperationsMeta } from '../OperationsLayout';
import type { VehicleRow } from '../types';

type SelectedVehicle=VehicleRow&{note:string;statusNote:string;shortageLocationNote:string;checks:Array<{code:string;name:string;status:string;note:string}>};
export function MovementPage(){
  const meta=useOperationsMeta();const [search,setSearch]=useState('');const [suggestions,setSuggestions]=useState<VehicleRow[]>([]);const [selected,setSelected]=useState<SelectedVehicle[]>([]);const [toLocationId,setToLocationId]=useState('');const [toStatusCode,setToStatusCode]=useState('available_for_sale');const [generalNote,setGeneralNote]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  async function searchVehicles(){if(!search.trim()){setSuggestions([]);return;}try{const payload=await operationsFetch<any>(`/api/operations${operationsQuery({resource:'vehicles',search,page:1,pageSize:20})}`);setSuggestions((payload.rows||[]).filter((row:VehicleRow)=>!selected.some((item)=>item.id===row.id)));}catch(e){setError(e instanceof Error?e.message:'تعذر البحث');}}
  useEffect(()=>{const timer=window.setTimeout(()=>{if(search.trim().length>=2)void searchVehicles();else setSuggestions([]);},300);return()=>window.clearTimeout(timer);},[search]);
  function add(row:VehicleRow){setSelected((current)=>[...current,{...row,note:'',statusNote:'',shortageLocationNote:'',checks:meta.checkItems.map((item)=>({...item,status:'not_checked',note:''}))}]);setSearch('');setSuggestions([]);}
  function update(id:string,changes:Partial<SelectedVehicle>){setSelected((current)=>current.map((item)=>item.id===id?{...item,...changes}:item));}
  async function submit(){if(!selected.length||!toLocationId||!toStatusCode)return;setLoading(true);setError('');setMessage('');try{const payload=await operationsFetch<any>('/api/operations',{method:'POST',body:JSON.stringify({action:'move_vehicles',toLocationId,toStatusCode,generalNote,idempotencyKey:crypto.randomUUID(),vehicles:selected.map((item)=>({id:item.id,note:item.note,statusNote:item.statusNote,shortageLocationNote:item.shortageLocationNote,checks:item.location_code==='agency'?item.checks:[]}))})});setMessage(`${payload.message} — رقم الدفعة: ${payload.batchNo}`);setSelected([]);setGeneralNote('');}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ الحركة');}finally{setLoading(false);}}
  const requiresNote=meta.statuses.find((item)=>item.code===toStatusCode)?.requires_note;
  return <div className="module-page operations-page">
    {error?<div className="connection-banner"><WarningCircle size={20}/><span>{error}</span></div>:null}{message?<div className="success-banner"><span>{message}</span></div>:null}
    <section className="panel movement-builder"><div className="operations-panel-title"><div><h2>الحركة</h2><p>نفس الفلو يدعم سيارة واحدة أو عدة سيارات داخل Transaction واحدة.</p></div><ArrowsLeftRight size={28}/></div><div className="vehicle-picker"><div className="operations-search"><MagnifyingGlass size={19}/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="اكتب جزءًا من رقم الهيكل"/></div>{suggestions.length?<div className="vehicle-suggestions">{suggestions.map((row)=><button key={row.id} type="button" onClick={()=>add(row)}><span><strong>{row.vin}</strong><small>{row.car_name||'—'} — {row.location_name||'—'} — {row.status_name||'—'}</small></span><Plus size={18}/></button>)}</div>:null}</div><div className="movement-destination"><label><span>المكان الجديد</span><select value={toLocationId} onChange={(e)=>setToLocationId(e.target.value)}><option value="">اختر المكان</option>{meta.locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>الحالة الجديدة</span><select value={toStatusCode} onChange={(e)=>setToStatusCode(e.target.value)}>{meta.statuses.map((item)=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label><label className="wide"><span>ملاحظات عامة للحركة</span><textarea value={generalNote} onChange={(e)=>setGeneralNote(e.target.value)}/></label></div></section>
    <section className="movement-cards">{selected.length===0?<div className="panel empty-selection">اختر سيارة واحدة أو أكثر لبدء الحركة.</div>:selected.map((vehicle,index)=><article className="panel movement-vehicle-card" key={vehicle.id}><header><div><span>السيارة {index+1}</span><h3>{vehicle.vin}</h3><p>{vehicle.car_name||'—'} — {vehicle.statement||'—'}</p></div><button type="button" className="danger-icon" onClick={()=>setSelected((current)=>current.filter((item)=>item.id!==vehicle.id))}><Trash size={18}/></button></header><div className="movement-current-grid"><div><small>المكان الحالي</small><strong>{vehicle.location_name||'—'}</strong></div><div><small>الحالة الحالية</small><strong>{vehicle.status_name||'—'}</strong></div><div><small>الموديل</small><strong>{vehicle.model_year||'—'}</strong></div><div><small>الفرع</small><strong>{vehicle.branch_name||'—'}</strong></div></div><div className="movement-notes"><label><span>ملاحظة السيارة في الحركة</span><textarea value={vehicle.note} onChange={(e)=>update(vehicle.id,{note:e.target.value})}/></label>{requiresNote?<label><span>ملاحظات الحالة *</span><textarea required value={vehicle.statusNote} onChange={(e)=>update(vehicle.id,{statusNote:e.target.value})}/></label>:null}<label><span>حجز - نواقص - تحديد مكان</span><textarea value={vehicle.shortageLocationNote} onChange={(e)=>update(vehicle.id,{shortageLocationNote:e.target.value})}/></label></div>{vehicle.location_code==='agency'?<div className="vehicle-check-grid"><h4>تشيك السيارة — يظهر لأن مكانها الحالي الوكالة</h4>{vehicle.checks.map((check)=><div key={check.code}><span>{check.name}</span><select value={check.status} onChange={(e)=>update(vehicle.id,{checks:vehicle.checks.map((item)=>item.code===check.code?{...item,status:e.target.value}:item)})}><option value="not_checked">لم يتم</option><option value="available">موجود</option><option value="missing">ناقص</option><option value="damaged">به ملاحظة</option></select><input placeholder="ملاحظة" value={check.note} onChange={(e)=>update(vehicle.id,{checks:vehicle.checks.map((item)=>item.code===check.code?{...item,note:e.target.value}:item)})}/></div>)}</div>:null}</article>)}</section>
    {selected.length?<div className="sticky-submit-bar"><span>{selected.length} سيارة محددة</span><button type="button" disabled={loading||!toLocationId||!toStatusCode||Boolean(requiresNote&&selected.some((item)=>!item.statusNote.trim()))} onClick={()=>void submit()}>{loading?'جاري التنفيذ...':'مراجعة وتنفيذ الحركة'}</button></div>:null}
  </div>;
}
