import { useEffect, useMemo, useState } from "react";
import { ArrowsLeftRight, CheckCircle, CheckSquare, SpinnerGap, Trash, WarningCircle, XCircle } from "@phosphor-icons/react";
import { notifyOperationsChanged, operationsFetch } from "../api";
import type { OperationsMeta, VehicleDetail, VehicleRow } from "../types";
import { VehicleSearch } from "../components/VehicleSearch";

type CheckState=Record<string,{isPresent:boolean;note:string}>;
type MovementPreview={atomic:boolean;allowed:boolean;destination:{name:string};status:{name:string};rows:Array<{vehicleId:string;vin:string;carName?:string;currentLocation?:string;currentStatus?:string;allowed:boolean;reason:string}>};

export function MovementPage(){
  const[meta,setMeta]=useState<OperationsMeta>({locations:[],statuses:[],checklist:[]});const[requestKey,setRequestKey]=useState(()=>crypto.randomUUID());const[selected,setSelected]=useState<VehicleRow[]>([]);const[destination,setDestination]=useState("");const[status,setStatus]=useState("");const[statusNote,setStatusNote]=useState("");const[missing,setMissing]=useState("");const[checks,setChecks]=useState<Record<string,CheckState>>({});const[saving,setSaving]=useState(false);const[reviewing,setReviewing]=useState(false);const[preview,setPreview]=useState<MovementPreview|null>(null);const[error,setError]=useState("");const[message,setMessage]=useState("");
  useEffect(()=>{operationsFetch<OperationsMeta&{ok:boolean}>("/api/operations?resource=meta").then((payload)=>{setMeta(payload);setStatus(payload.statuses[0]?.code||"");}).catch((e)=>setError((e as Error).message));},[]);
  const chosenStatus=useMemo(()=>meta.statuses.find((item)=>item.code===status),[meta.statuses,status]);
  const clearReview=()=>setPreview(null);
  const add=(vehicle:VehicleRow)=>{
    clearReview();setSelected((current)=>current.some((item)=>item.id===vehicle.id)?current:[...current,vehicle]);
    if(vehicle.location_code!=="agency")return;
    operationsFetch<{detail:VehicleDetail}>(`/api/operations?resource=vehicle&id=${encodeURIComponent(vehicle.id)}`).then(({detail})=>setChecks((current)=>{if(current[vehicle.id])return current;return {...current,[vehicle.id]:Object.fromEntries(meta.checklist.map((item)=>{const saved=detail.checklist.find((entry)=>entry.code===item.code);return[item.code,{isPresent:Boolean(saved?.is_present),note:saved?.note||""}];}))};})).catch((e)=>setError((e as Error).message));
  };
  const remove=(id:string)=>{clearReview();setSelected((current)=>current.filter((item)=>item.id!==id));setChecks((current)=>{const next={...current};delete next[id];return next;});};
  const toggle=(vehicleId:string,itemCode:string,checked:boolean)=>{clearReview();setChecks((current)=>({...current,[vehicleId]:{...(current[vehicleId]||{}),[itemCode]:{...(current[vehicleId]?.[itemCode]||{note:""}),isPresent:checked}}}));};
  const review=async()=>{setReviewing(true);setError("");setMessage("");try{const payload=await operationsFetch<{preview:MovementPreview}>("/api/operations",{method:"POST",body:JSON.stringify({action:"preview_movement",vehicleIds:selected.map((vehicle)=>vehicle.id),destinationLocationId:destination,newStatusCode:status})});setPreview(payload.preview);}catch(e){setPreview(null);setError((e as Error).message);}finally{setReviewing(false);}};
  const execute=async()=>{setSaving(true);setError("");setMessage("");try{await operationsFetch("/api/operations",{method:"POST",body:JSON.stringify({action:"create_movement",vehicleIds:selected.map((vehicle)=>vehicle.id),destinationLocationId:destination,newStatusCode:status,statusNote,missingReservationLocation:missing,checklistByVehicle:checks,requestKey})});setMessage(`تم تنفيذ الحركة بنجاح لعدد ${selected.length.toLocaleString("ar-SA")} سيارة`);setSelected([]);setChecks({});setDestination("");setStatusNote("");setMissing("");setPreview(null);setRequestKey(crypto.randomUUID());notifyOperationsChanged({entity:"movement"});}catch(e){setError((e as Error).message);}finally{setSaving(false);}};
  return <section className="panel operations-page movement-page"><header className="operations-page-title"><div><span>حركة موحدة</span><h2>الحركة</h2><p>سيارة واحدة أو عدة سيارات بنفس الخدمة، مع مراجعة مستقلة لكل سيارة وتنفيذ Atomic كامل.</p></div></header>
    {error?<div className="operations-error">{error}</div>:null}{message?<div className="operations-success">{message}</div>:null}
    <div className="operations-movement-builder"><section><h3>1. السيارات المختارة</h3><VehicleSearch onSelect={add} excludedIds={selected.map((item)=>item.id)}/>{selected.length?<div className="operations-selected-vehicles detailed">{selected.map((vehicle)=><article key={vehicle.id}><header><div><b>{vehicle.vin}</b><span>{vehicle.car_name||"—"} · {vehicle.statement||"—"}</span></div><button type="button" aria-label={`إزالة ${vehicle.vin}`} onClick={()=>remove(vehicle.id)}><Trash size={17}/></button></header><div className="movement-vehicle-facts"><span><small>الموديل</small><b>{vehicle.model_year||"—"}</b></span><span><small>المكان الحالي</small><b>{vehicle.location_name||"—"}</b></span><span><small>الحالة الحالية</small><b>{vehicle.status_name||"—"}</b></span><span><small>ملاحظات السيارة</small><b>{vehicle.notes||"—"}</b></span><span><small>ملاحظات الحالة</small><b>{vehicle.status_notes||"—"}</b></span><span><small>الموافقة المالية</small><b className={vehicle.financial_approved?"fact-approved":"fact-pending"}>{vehicle.financial_approved?"تمت":"لم تتم"}</b></span><span><small>الموافقة الإدارية</small><b className={vehicle.administrative_approved?"fact-approved":"fact-pending"}>{vehicle.administrative_approved?"تمت":"لم تتم"}</b></span><span><small>ملخص الموافقات</small><b>{vehicle.financial_approved&&vehicle.administrative_approved?"مكتملة":vehicle.financial_approved||vehicle.administrative_approved?"مكتملة جزئيًا":"لم تبدأ"}</b></span></div>{vehicle.location_code==="agency"?<div className="operations-movement-checklist"><div className="checklist-title"><CheckSquare size={18}/><b>التشيك المستقل لهذه السيارة</b><span>ظهر لأن المكان الحالي هو الوكالة</span></div><div>{meta.checklist.map((item)=><label key={item.code}><input type="checkbox" checked={Boolean(checks[vehicle.id]?.[item.code]?.isPresent)} onChange={(event)=>toggle(vehicle.id,item.code,event.target.checked)}/><span>{item.name}</span></label>)}</div></div>:null}</article>)}</div>:<div className="operations-empty-inline">لم يتم اختيار سيارات بعد.</div>}</section>
      <section><h3>2. بيانات الحركة</h3><div className="operations-form-grid"><label><span>المكان الجديد *</span><select value={destination} onChange={(event)=>{setDestination(event.target.value);clearReview();}}><option value="">اختر المكان</option>{meta.locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>الحالة الجديدة *</span><select value={status} onChange={(event)=>{setStatus(event.target.value);setStatusNote("");clearReview();}}>{meta.statuses.map((item)=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label>{chosenStatus?.requires_status_note?<label className="full required-note"><span>ملاحظات الحالة *</span><textarea value={statusNote} onChange={(event)=>{setStatusNote(event.target.value);clearReview();}} placeholder="سبب وجود الملاحظات"/></label>:null}<label className="full"><span>حجز - نواقص - تحديد مكان</span><textarea value={missing} onChange={(event)=>{setMissing(event.target.value);clearReview();}}/></label></div><div className="operations-note-removed">لا يوجد حقل إنشاء جديد باسم «ملاحظة الحركة». الملاحظات التاريخية القديمة محفوظة في سجل الحركات.</div><button type="button" className="operations-secondary-button movement-review-button" onClick={()=>void review()} disabled={reviewing||!selected.length||!destination||!status}>{reviewing?<SpinnerGap className="spin" size={18}/>:<CheckSquare size={18}/>} {reviewing?"جاري فحص السيارات...":"مراجعة الحركة قبل التنفيذ"}</button>{preview?<div className={`movement-preview ${preview.allowed?"allowed":"blocked"}`}><header>{preview.allowed?<CheckCircle size={21}/>:<WarningCircle size={21}/>}<div><b>{preview.allowed?"كل السيارات جاهزة للتنفيذ":"توجد سيارات تمنع التنفيذ Atomic"}</b><span>{preview.destination.name} · {preview.status.name}</span></div></header><div>{preview.rows.map((row)=><article key={row.vehicleId} className={row.allowed?"allowed":"blocked"}>{row.allowed?<CheckCircle size={18}/>:<XCircle size={18}/>}<span><b>{row.vin}</b><small>{row.reason}</small></span></article>)}</div></div>:null}<button type="button" className="operations-primary-button execute-movement" onClick={()=>void execute()} disabled={saving||!preview?.allowed||(Boolean(chosenStatus?.requires_status_note)&&!statusNote.trim())}>{saving?<SpinnerGap className="spin" size={18}/>:<ArrowsLeftRight size={18}/>} {saving?"جاري تنفيذ الحركة...":`تنفيذ الحركة (${selected.length.toLocaleString("ar-SA")})`}</button></section>
    </div>
  </section>;
}
