import { useEffect, useMemo, useState } from "react";
import { DownloadSimple, MagnifyingGlass, WarningCircle } from "@phosphor-icons/react";
import { downloadCsv, operationsFetch, operationsQuery } from "../api";
import type { OperationsVehicle } from "../types";
import { useOperationsMeta } from "../useOperationsMeta";

type SummaryRow={key:string;carName:string;statement:string;model:string;location:string;status:string;count:number};
export function OperationsAllVehiclesPage(){
  const {meta}=useOperationsMeta();const [vehicles,setVehicles]=useState<OperationsVehicle[]>([]);const [search,setSearch]=useState("");const [locationId,setLocationId]=useState("");const [status,setStatus]=useState("");const [minimum,setMinimum]=useState(1);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  async function load(){setLoading(true);setError("");try{const payload=await operationsFetch<{ok:boolean;vehicles:OperationsVehicle[]}>(`/api/operations${operationsQuery({resource:"vehicles",export:true,search,locationId,status})}`);setVehicles(payload.vehicles||[]);}catch(reason){setError(reason instanceof Error?reason.message:"تعذر تحميل جميع السيارات");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  const rows=useMemo(()=>{const map=new Map<string,SummaryRow>();for(const vehicle of vehicles){const key=[vehicle.car_name||"—",vehicle.statement||"—",vehicle.model_year||"—",vehicle.location_name||"—",vehicle.status_name||vehicle.status_code].join("|");const current=map.get(key);if(current)current.count++;else map.set(key,{key,carName:vehicle.car_name||"—",statement:vehicle.statement||"—",model:vehicle.model_year||"—",location:vehicle.location_name||"—",status:vehicle.status_name||vehicle.status_code,count:1});}return [...map.values()].filter((row)=>row.count>=minimum).sort((a,b)=>b.count-a.count);},[vehicles,minimum]);
  function exportRows(){downloadCsv("MZJ-Operations-All-Vehicles.csv",rows.map((row)=>({"السيارة":row.carName,"البيان":row.statement,"الموديل":row.model,"المكان":row.location,"الحالة":row.status,"العدد":row.count})));}
  return <div className="module-page operations-page"><header className="module-page-head"><div><h1>جميع السيارات</h1><p>تقرير مجمع حسب السيارة والبيان والموديل والمكان والحالة.</p></div><button type="button" onClick={exportRows}><DownloadSimple size={18}/>تصدير النتائج</button></header>{error?<div className="connection-banner"><WarningCircle size={20}/><span>{error}</span></div>:null}<section className="panel operations-filter-panel all-vehicles"><label className="operations-search-field"><span>بحث</span><div><MagnifyingGlass size={18}/><input value={search} onChange={(e)=>setSearch(e.target.value)}/></div></label><label><span>المكان</span><select value={locationId} onChange={(e)=>setLocationId(e.target.value)}><option value="">الكل</option>{meta?.locations.map((row)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label><span>الحالة</span><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">الكل</option>{meta?.statuses.map((row)=><option key={row.code} value={row.code}>{row.name}</option>)}</select></label><label><span>الحد الأدنى للعدد</span><input type="number" min={1} value={minimum} onChange={(e)=>setMinimum(Math.max(1,Number(e.target.value||1)))}/></label><button type="button" className="operations-primary-button" onClick={()=>void load()}>تطبيق</button></section><section className="panel operations-table-card"><div className="operations-table-heading"><div><h2>التقرير المجمع</h2><span>{rows.length} مجموعة</span></div><small>{vehicles.length} سيارة ضمن النتائج</small></div><div className="operations-table-wrap"><table className="operations-table compact"><thead><tr><th>السيارة</th><th>البيان</th><th>الموديل</th><th>المكان</th><th>الحالة</th><th>العدد</th></tr></thead><tbody>{!loading&&rows.length===0?<tr><td colSpan={6} className="table-empty">لا توجد نتائج</td></tr>:rows.map((row)=><tr key={row.key}><td>{row.carName}</td><td>{row.statement}</td><td>{row.model}</td><td>{row.location}</td><td>{row.status}</td><td><strong>{row.count}</strong></td></tr>)}</tbody></table>{loading?<div className="operations-loading-row">جاري التحميل...</div>:null}</div></section></div>;
}
