import { useEffect, useMemo, useState } from "react";
import { ArrowsLeftRight, MagnifyingGlass, Plus, Trash, WarningCircle } from "@phosphor-icons/react";
import { operationsFetch, operationsQuery } from "../api";
import { useEscapeToClose } from "../../components/useEscapeToClose";
import type { OperationsVehicle } from "../types";
import { useOperationsMeta } from "../useOperationsMeta";

type SelectedVehicle = OperationsVehicle & { note:string;statusNote:string;shortageLocationNote:string;checks:Array<{code:string;name:string;status:string;note:string}> };

export function OperationsMovementPage(){
  const {meta,error:metaError}=useOperationsMeta();
  const [search,setSearch]=useState("");const [results,setResults]=useState<OperationsVehicle[]>([]);const [selected,setSelected]=useState<SelectedVehicle[]>([]);
  const [destinationLocationId,setDestinationLocationId]=useState("");const [statusCode,setStatusCode]=useState("available_for_sale");const [generalNote,setGeneralNote]=useState("");
  const [loading,setLoading]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [reviewOpen,setReviewOpen]=useState(false);
  useEscapeToClose(reviewOpen,()=>setReviewOpen(false));
  const status=useMemo(()=>meta?.statuses.find((row)=>row.code===statusCode),[meta,statusCode]);
  async function find(){setLoading(true);setError("");try{const payload=await operationsFetch<{ok:boolean;vehicles:OperationsVehicle[]}>(`/api/operations${operationsQuery({resource:"vehicles",search,limit:20})}`);setResults(payload.vehicles||[]);}catch(reason){setError(reason instanceof Error?reason.message:"تعذر البحث");}finally{setLoading(false);}}
  useEffect(()=>{if(search.trim().length<2){setResults([]);return;}const timer=window.setTimeout(()=>void find(),300);return()=>window.clearTimeout(timer);},[search]);
  function add(vehicle:OperationsVehicle){if(selected.some((row)=>row.id===vehicle.id))return;setSelected((current)=>[...current,{...vehicle,note:"",statusNote:"",shortageLocationNote:"",checks:(meta?.checkItems||[]).map((item)=>({...item,status:"unknown",note:""}))}]);setSearch("");setResults([]);}
  function updateVehicle(id:string,key:string,value:any){setSelected((current)=>current.map((row)=>row.id===id?{...row,[key]:value}:row));}
  function updateCheck(id:string,code:string,key:"status"|"note",value:string){setSelected((current)=>current.map((row)=>row.id===id?{...row,checks:row.checks.map((item)=>item.code===code?{...item,[key]:value}:item)}:row));}
  async function execute(){setBusy(true);setError("");setMessage("");try{const payload=await operationsFetch<{ok:boolean;message:string}>("/api/operations",{method:"POST",body:JSON.stringify({action:"move_vehicles",destinationLocationId,statusCode,generalNote,vehicles:selected.map(({id,note,statusNote,shortageLocationNote,checks})=>({id,note,statusNote,shortageLocationNote,checks}))})});setMessage(payload.message);setSelected([]);setGeneralNote("");setReviewOpen(false);}catch(reason){setError(reason instanceof Error?reason.message:"تعذر تنفيذ الحركة");}finally{setBusy(false);}}
  const invalid=status?.requires_status_note&&selected.some((row)=>!row.statusNote.trim());
  return <div className="module-page operations-page"><header className="module-page-head"><div><h1>الحركة</h1><p>فلو موحد لسيارة واحدة أو عدة سيارات داخل Transaction واحدة.</p></div></header>
    {error||metaError?<div className="connection-banner"><WarningCircle size={20}/><span>{error||metaError}</span></div>:null}{message?<div className="success-banner operations-success-banner">{message}</div>:null}
    <section className="panel operations-movement-builder"><div className="operations-search-select"><label><span>ابحث بجزء من VIN</span><div><MagnifyingGlass size={18}/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="مثال: 000 أو آخر أرقام الهيكل"/></div></label>{results.length?<div className="operations-search-results">{results.map((vehicle)=><button type="button" key={vehicle.id} onClick={()=>add(vehicle)} disabled={selected.some((row)=>row.id===vehicle.id)}><span><strong>{vehicle.vin}</strong><small>{vehicle.car_name||"—"} • {vehicle.location_name||"—"}</small></span><Plus size={17}/></button>)}</div>:null}{loading?<small>جاري البحث...</small>:null}</div>
      <div className="operations-movement-target"><label><span>المكان الجديد</span><select value={destinationLocationId} onChange={(e)=>setDestinationLocationId(e.target.value)}><option value="">اختر المكان</option>{meta?.locations.map((row)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label><span>الحالة الجديدة</span><select value={statusCode} onChange={(e)=>setStatusCode(e.target.value)}>{meta?.statuses.map((row)=><option key={row.code} value={row.code}>{row.name}</option>)}</select></label><label className="span-2"><span>ملاحظات عامة للحركة</span><textarea rows={3} value={generalNote} onChange={(e)=>setGeneralNote(e.target.value)}/></label></div>
    </section>
    <div className="operations-selected-vehicles">{selected.map((vehicle,index)=><article className="panel operations-movement-card" key={vehicle.id}><header><div><span>سيارة {index+1}</span><h3>{vehicle.vin}</h3><p>{vehicle.car_name||"—"} • المكان الحالي: {vehicle.location_name||"—"} • الحالة الحالية: {vehicle.status_name||vehicle.status_code}</p></div><button type="button" className="danger" onClick={()=>setSelected((current)=>current.filter((row)=>row.id!==vehicle.id))}><Trash size={18}/></button></header><div className="operations-movement-vehicle-data"><span><small>البيان</small><b>{vehicle.statement||"—"}</b></span><span><small>الوكيل</small><b>{vehicle.agent_name||"—"}</b></span><span><small>الموديل</small><b>{vehicle.model_year||"—"}</b></span><span><small>اللوحة</small><b>{vehicle.plate_no||"—"}</b></span><span><small>اللون الخارجي</small><b>{vehicle.exterior_color||"—"}</b></span><span><small>اللون الداخلي</small><b>{vehicle.interior_color||"—"}</b></span><span><small>الدفعة</small><b>{vehicle.batch_no||"—"}</b></span><span><small>الموافقات</small><b>{vehicle.financial_approved?"مالي ✓":"مالي —"} / {vehicle.administrative_approved?"إداري ✓":"إداري —"}</b></span><span className="span-2"><small>ملاحظات السيارة الحالية</small><b>{vehicle.notes||"—"}</b></span></div><div className="operations-form-grid"><label className="span-2"><span>ملاحظات السيارة في الحركة</span><textarea rows={2} value={vehicle.note} onChange={(e)=>updateVehicle(vehicle.id,"note",e.target.value)}/></label>{status?.requires_status_note?<label className="span-2"><span>ملاحظات الحالة *</span><textarea rows={2} value={vehicle.statusNote} onChange={(e)=>updateVehicle(vehicle.id,"statusNote",e.target.value)}/></label>:null}<label className="span-2"><span>حجز - نواقص - تحديد مكان</span><textarea rows={2} value={vehicle.shortageLocationNote} onChange={(e)=>updateVehicle(vehicle.id,"shortageLocationNote",e.target.value)}/></label></div>{vehicle.location_code==="agency"?<div className="operations-check-grid"><h4>تشيك السيارة في الوكالة</h4>{vehicle.checks.map((item)=><div key={item.code}><strong>{item.name}</strong><select value={item.status} onChange={(e)=>updateCheck(vehicle.id,item.code,"status",e.target.value)}><option value="unknown">غير محدد</option><option value="ok">موجود / سليم</option><option value="missing">ناقص</option><option value="damaged">به ملاحظة</option></select><input value={item.note} onChange={(e)=>updateCheck(vehicle.id,item.code,"note",e.target.value)} placeholder="ملاحظة"/></div>)}</div>:null}</article>)}</div>
    {selected.length?<section className="panel operations-submit-bar"><span>{selected.length} سيارة سيتم تنفيذ حركتها بصورة Atomic</span><button type="button" className="operations-primary-button" disabled={busy||!destinationLocationId||!statusCode||Boolean(invalid)} onClick={()=>setReviewOpen(true)}><ArrowsLeftRight size={18}/>{busy?"جاري تنفيذ الحركة...":"تنفيذ الحركة"}</button></section>:<section className="panel operations-empty-state">ابحث عن سيارة وأضفها لبدء الحركة.</section>}
    {reviewOpen?<div className="modal-backdrop operations-confirm-backdrop"><div className="operations-transfer-detail-modal"><header><div><span>مراجعة الحركة قبل التنفيذ</span><h3>{selected.length} سيارة</h3><p>الوجهة: {meta?.locations.find((row)=>row.id===destinationLocationId)?.name||"—"} • الحالة: {status?.name||statusCode}</p></div><button type="button" onClick={()=>setReviewOpen(false)}>×</button></header><div className="operations-transfer-detail-body"><section><h4>السيارات التي ستتأثر</h4><div className="operations-detail-cards">{selected.map((vehicle)=><div key={vehicle.id}><strong>{vehicle.vin}</strong><span>{vehicle.car_name||"—"}</span><small>{vehicle.location_name||"—"} / {vehicle.status_name||vehicle.status_code}</small></div>)}</div></section>{generalNote?<section><h4>الملاحظة العامة</h4><p>{generalNote}</p></section>:null}<div className="operations-review-actions"><button type="button" onClick={()=>setReviewOpen(false)}>رجوع للتعديل</button><button type="button" className="operations-primary-button" disabled={busy} onClick={()=>void execute()}>{busy?"جاري تنفيذ الحركة...":"تأكيد وتنفيذ الحركة"}</button></div></div></div></div>:null}
  </div>;
}
