import { useEffect, useState } from "react";
import { CheckCircle, Coins, ShieldCheck, WarningCircle, XCircle } from "@phosphor-icons/react";
import { useEscapeToClose } from "../../components/useEscapeToClose";
import { operationsFetch, operationsQuery, formatDate } from "../api";
import type { ApprovalRow } from "../types";

type PendingAction={row:ApprovalRow;type:"financial"|"administrative"|"reset";approvalAction:"approve"|"revert"|"note"};

export function OperationsApprovalsPage(){
  const [filter,setFilter]=useState("");const [rows,setRows]=useState<ApprovalRow[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");
  const [pending,setPending]=useState<PendingAction|null>(null);const [pendingNote,setPendingNote]=useState("");
  useEscapeToClose(Boolean(pending),()=>setPending(null));
  async function load(next=filter){setLoading(true);setError("");try{const payload=await operationsFetch<{ok:boolean;approvals:ApprovalRow[]}>(`/api/operations${operationsQuery({resource:"approvals",filter:next})}`);setRows(payload.approvals||[]);}catch(reason){setError(reason instanceof Error?reason.message:"تعذر تحميل الموافقات");}finally{setLoading(false);}}
  useEffect(()=>{void load("");},[]);
  function choose(value:string){setFilter(value);void load(value);}
  function requestAction(row:ApprovalRow,type:"financial"|"administrative"|"reset",approvalAction:"approve"|"revert"|"note"="approve"){
    if(approvalAction==="approve"){void act({row,type,approvalAction},"");return;}
    setPending({row,type,approvalAction});setPendingNote(type==="financial"?row.financial_note||"":type==="administrative"?row.administrative_note||"":"");
  }
  async function act(action:PendingAction,note:string){
    const {row,type,approvalAction}=action;const key=`${row.vehicle_id}:${type}:${approvalAction}`;setBusy(key);setError("");
    try{const payload=await operationsFetch<{ok:boolean;message:string}>("/api/operations",{method:"POST",body:JSON.stringify({action:"approval",vehicleId:row.vehicle_id,type,approvalAction,note})});setMessage(payload.message);setPending(null);setPendingNote("");await load();}
    catch(reason){setError(reason instanceof Error?reason.message:"تعذر تحديث الموافقة");}finally{setBusy("");}
  }
  const pendingNeedsReason=pending?.approvalAction==="revert"||pending?.type==="reset";
  return <div className="module-page operations-page"><header className="module-page-head"><div><h1>الموافقات المالية والإدارية</h1><p>الموافقتان مستقلتان، وكلتاهما مطلوبة قبل السماح بحالة مباع تم التسليم.</p></div></header>{error?<div className="connection-banner"><WarningCircle size={20}/><span>{error}</span></div>:null}{message?<div className="success-banner operations-success-banner">{message}</div>:null}
    <div className="operations-approval-filters"><button className={filter===""?"active":""} onClick={()=>choose("")}>كل السيارات</button><button className={filter==="financial"?"active":""} onClick={()=>choose("financial")}>ناقص مالي</button><button className={filter==="administrative"?"active":""} onClick={()=>choose("administrative")}>ناقص إداري</button><button className={filter==="completed"?"active":""} onClick={()=>choose("completed")}>مكتملة</button></div>
    <section className="operations-approval-grid">{loading?<div className="panel operations-empty-state">جاري تحميل الموافقات...</div>:rows.length?rows.map((row)=><article className="panel operations-approval-card" key={row.cycle_id}><header><div><span>دورة موافقات رقم {row.cycle_no}</span><h3>{row.vin}</h3><p>{row.car_name||"—"} • {row.location_name||"—"}</p></div><small>بدأت {formatDate(row.started_at)}</small></header><div className="operations-approval-columns"><section className={row.financial_approved?"approved":""}><div><Coins size={22}/><h4>الموافقة المالية</h4>{row.financial_approved?<CheckCircle size={20}/>:<XCircle size={20}/>}</div><p>{row.financial_note||"لا توجد ملاحظة مالية"}</p><small>{row.financial_approved_by_name?`${row.financial_approved_by_name} • ${formatDate(row.financial_approved_at)}`:"لم تتم"}</small><div><button type="button" onClick={()=>requestAction(row,"financial","note")}>حفظ ملاحظة</button><button type="button" disabled={busy.startsWith(row.vehicle_id)} onClick={()=>requestAction(row,"financial",row.financial_approved?"revert":"approve")}>{row.financial_approved?"تراجع":"موافقة مالية"}</button></div></section><section className={row.administrative_approved?"approved":""}><div><ShieldCheck size={22}/><h4>الموافقة الإدارية</h4>{row.administrative_approved?<CheckCircle size={20}/>:<XCircle size={20}/>}</div><p>{row.administrative_note||"لا توجد ملاحظة إدارية"}</p><small>{row.administrative_approved_by_name?`${row.administrative_approved_by_name} • ${formatDate(row.administrative_approved_at)}`:"لم تتم"}</small><div><button type="button" onClick={()=>requestAction(row,"administrative","note")}>حفظ ملاحظة</button><button type="button" disabled={busy.startsWith(row.vehicle_id)} onClick={()=>requestAction(row,"administrative",row.administrative_approved?"revert":"approve")}>{row.administrative_approved?"تراجع":"موافقة إدارية"}</button></div></section></div><button type="button" className="operations-reset-approvals" onClick={()=>requestAction(row,"reset","revert")}>إلغاء الطلب (مسح الموافقات)</button></article>):<div className="panel operations-empty-state">لا توجد سيارات مطابقة.</div>}</section>
    {pending?<div className="modal-backdrop operations-confirm-backdrop"><div className="operations-confirm-modal"><h3>{pending.type==="reset"?"مسح الموافقات":pending.approvalAction==="revert"?`التراجع عن الموافقة ${pending.type==="financial"?"المالية":"الإدارية"}`:`حفظ الملاحظة ${pending.type==="financial"?"المالية":"الإدارية"}`}</h3><p>{pendingNeedsReason?"يجب كتابة سبب واضح، وسيظل الاعتماد السابق محفوظًا داخل سجل التدقيق.":"حفظ الملاحظة لا ينفذ الموافقة ولا يغير حالتها."}</p><strong>{pending.row.vin} — {pending.row.car_name||"—"}</strong><label><span>{pendingNeedsReason?"السبب *":"الملاحظة"}</span><textarea rows={4} value={pendingNote} onChange={(event)=>setPendingNote(event.target.value)}/></label><div><button type="button" onClick={()=>setPending(null)}>إلغاء</button><button type="button" className={pendingNeedsReason?"danger":"primary"} disabled={(pendingNeedsReason&&!pendingNote.trim())||busy.startsWith(pending.row.vehicle_id)} onClick={()=>void act(pending,pendingNote)}>{busy.startsWith(pending.row.vehicle_id)?"جاري الحفظ...":pendingNeedsReason?"تأكيد الإجراء":"حفظ الملاحظة"}</button></div></div></div>:null}
  </div>;
}
