import { useCallback,useEffect,useState } from "react";
import { DownloadSimple,ArrowClockwise,MagnifyingGlass } from "@phosphor-icons/react";
import { operationsFetch,formatOperationsError,exportExcelFile } from "../api";
import { useOperationsMeta } from "../useOperationsMeta";
import type { VehicleRow } from "../types";
import { VehicleTable } from "../components/VehicleTable";
import { VehicleDetailDrawer } from "../components/VehicleDetailDrawer";
export function OperationsInventoryPage(){
 const {locations,statuses,error:metaError}=useOperationsMeta();const [rows,setRows]=useState<VehicleRow[]>([]),[q,setQ]=useState(''),[location,setLocation]=useState(''),[status,setStatus]=useState(''),[model,setModel]=useState(''),[agent,setAgent]=useState(''),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(false),[selected,setSelected]=useState<VehicleRow|null>(null);
 const load=useCallback(async(target=page)=>{setLoading(true);setError('');try{const r=await operationsFetch<any>('vehicles',{query:{q,location,status,model,agent,page:target,limit:25}});setRows(r.rows);setPage(r.page);setPages(r.pages);setTotal(r.total);}catch(e){setError(formatOperationsError(e));setRows([])}finally{setLoading(false)}},[q,location,status,model,agent,page]);useEffect(()=>{void load(1)},[]);
 async function exportAll(){try{const r=await operationsFetch<any>('vehicles',{query:{q,location,status,model,agent,page:1,limit:5000}});exportExcelFile('مخزون-السيارات',['رقم الهيكل','السيارة','البيان','الوكيل','الداخلي','الخارجي','الموديل','اللوحة','اسم الدفعة','المكان','ملاحظات السيارة','حجز - نواقص - تحديد مكان','الحالة','Tracking','الموافقات','التشيك','طلبات النقل','الأرشيف'],r.rows.map((v:VehicleRow)=>[v.vin,v.car_name,v.statement,v.agent_name,v.interior_color,v.exterior_color,v.model_year,v.plate_no,v.batch_no,v.location_name,v.notes,v.shortage_location_note,v.status_name,v.tracking_order_no?`${v.tracking_order_no} — ${v.tracking_progress||0}%`:'لا يوجد طلب',v.financial_approved&&v.administrative_approved?'مكتملة':v.financial_approved?'ناقص إداري':v.administrative_approved?'ناقص مالي':'لم تتم',Number(v.checks_count||0),Number(v.active_transfers||0),v.archived_at?'مؤرشفة':'نشطة']));}catch(e){setError(formatOperationsError(e))}}
 return <div className="operations-page"><header className="operations-page-head"><div><h1>مخزون السيارات</h1><p>المخزون التشغيلي الكامل مع الحركة والتراكينج والموافقات وطلبات النقل.</p></div><div><button onClick={()=>void load()}><ArrowClockwise/>تحديث</button><button onClick={()=>void exportAll()}><DownloadSimple/>تصدير Excel</button></div></header>{error||metaError?<div className="operations-error">{error||metaError}</div>:null}<section className="operations-filter-card"><label><span>بحث جزئي في VIN أو السيارة</span><div><MagnifyingGlass/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load(1)}} placeholder="اكتب جزءًا من رقم الهيكل"/></div></label><label><span>المكان</span><select value={location} onChange={e=>setLocation(e.target.value)}><option value="">كل الأماكن</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>الحالة</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">كل الحالات</option>{statuses.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label><label><span>الموديل</span><input value={model} onChange={e=>setModel(e.target.value)} placeholder="الموديل"/></label><label><span>الوكيل</span><input value={agent} onChange={e=>setAgent(e.target.value)} placeholder="الوكيل"/></label><button className="primary" onClick={()=>void load(1)}>تطبيق</button></section><section className="operations-card"><header><strong>السيارات الظاهرة <b>{total}</b></strong><span>اضغط على رقم الهيكل لفتح الملف الكامل.</span></header>{loading?<div className="operations-loading">جاري تحميل البيانات...</div>:<VehicleTable rows={rows} onOpen={setSelected}/>}<footer className="operations-pagination"><button disabled={page<=1} onClick={()=>void load(page-1)}>السابق</button><span>صفحة {page} من {pages}</span><button disabled={page>=pages} onClick={()=>void load(page+1)}>التالي</button></footer></section>{selected?<VehicleDetailDrawer vehicle={selected} onClose={()=>setSelected(null)} onChanged={()=>void load(page)}/>:null}</div>
}
