import { useEffect, useMemo, useState } from "react";
import { Camera, ClockCounterClockwise, MagnifyingGlass } from "@phosphor-icons/react";
import { formatOperationsDate, operationsFetch, queryString } from "../api";
import { useOperations } from "../useOperations";

type RequestStatus = { code: string; name: string; is_terminal: boolean; is_active: boolean; sort_order: number };
type RequestEvent = { id: string; status: string; actor_name?: string; note?: string; created_at: string };
type PhotoRequest = { id:string; request_no:string; status:string; requested_by_name?:string; requested_at:string; photography_date:string; note?:string; vehicles:Array<{vehicle_id:string;vin:string;car_name?:string;statement?:string;location_name?:string}>; events:RequestEvent[] };

export function PhotographyRequestsPage(){
  const { meta }=useOperations();
  const [rows,setRows]=useState<PhotoRequest[]>([]); const [requestStatuses,setRequestStatuses]=useState<RequestStatus[]>([]); const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const labels=useMemo(()=>Object.fromEntries(requestStatuses.map(row=>[row.code,row.name])),[requestStatuses]);
  async function load(){setLoading(true);setError("");try{const result=await operationsFetch<{rows:PhotoRequest[];requestStatuses:RequestStatus[]}>(`/api/operations${queryString({resource:"photography_requests",search,status})}`);setRows(result.rows);setRequestStatuses(result.requestStatuses||[]);}catch(failure){setError(failure instanceof Error?failure.message:"تعذر تحميل طلبات التصوير");}finally{setLoading(false);}}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),180);return()=>window.clearTimeout(timer);},[search,status]);
  async function update(id:string,next:string){setMessage("");setError("");try{const result=await operationsFetch<{message:string}>("/api/operations",{method:"POST",body:JSON.stringify({action:"photography_request_action",id,status:next})});setMessage(result.message);await load();}catch(failure){setError(failure instanceof Error?failure.message:"تعذر تحديث الطلب");}}
  return <div className="module-page operations-page"><header className="module-page-head"><div><h1>طلبات التصوير</h1><p>طلبات التسويق ظاهرة هنا من نفس سجل العمليات، ويتم تحديث نفس الحالة وسجل المتابعة بدون تكرار.</p></div></header>{error?<div className="connection-banner"><span>{error}</span></div>:null}{message?<div className="success-banner"><span>{message}</span></div>:null}<section className="panel operations-filters"><label className="operations-search"><MagnifyingGlass size={18}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="رقم الطلب أو VIN أو مقدم الطلب"/></label><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">كل الحالات</option>{requestStatuses.map(row=><option key={row.code} value={row.code}>{row.name}</option>)}</select></section><section className="operations-photo-request-grid">{loading?<div className="crm-loading-panel">جاري تحميل طلبات التصوير...</div>:rows.length?rows.map(row=><article className="panel" key={row.id}><header><div className="operations-request-icon"><Camera size={24}/></div><div><strong>{row.request_no}</strong><span>{row.requested_by_name||"—"} · {formatOperationsDate(row.requested_at)}</span></div><span className={`operations-status status-${row.status}`}>{labels[row.status]||row.status}</span></header><div>{row.vehicles.map(vehicle=><p key={vehicle.vehicle_id}><b>{vehicle.car_name||vehicle.statement||"سيارة"}</b><span dir="ltr">{vehicle.vin}</span><small>{vehicle.location_name||"—"}</small></p>)}</div><footer><span>موعد التصوير: {formatOperationsDate(row.photography_date)}</span>{meta.permissions.canManagePhotoRequests?<select value={row.status} onChange={event=>void update(row.id,event.target.value)}>{requestStatuses.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select>:null}</footer>{row.note?<blockquote>{row.note}</blockquote>:null}{row.events?.length?<div className="operations-photo-events"><strong><ClockCounterClockwise size={17}/>سجل المتابعة</strong>{row.events.slice(0,5).map(event=><p key={event.id}><span>{labels[event.status]||event.status}</span><small>{event.actor_name||"النظام"} · {formatOperationsDate(event.created_at)}{event.note?` · ${event.note}`:""}</small></p>)}</div>:null}</article>):<div className="operations-empty-state"><Camera size={42}/><strong>لا توجد طلبات تصوير</strong></div>}</section></div>;
}
