import { useCallback,useEffect,useState } from "react";
import { DownloadSimple } from "@phosphor-icons/react";
import { operationsFetch } from "../api";
import { exportXlsx } from "../excel";
import type { OperationsMeta,Pagination as PaginationType,ReportRow } from "../types";
import { Pagination } from "../components/Pagination";
const emptyPagination:PaginationType={page:1,pageSize:40,total:0,pages:1};
const columns=[{key:"car_name",header:"السيارة"},{key:"statement",header:"البيان"},{key:"model_year",header:"الموديل"},{key:"location_name",header:"المكان"},{key:"status_name",header:"الحالة"},{key:"total",header:"العدد"}] as const;
export function ReportPage({meta,notify}:{meta:OperationsMeta;notify:(message:string,error?:boolean)=>void}){
  const [filters,setFilters]=useState({search:"",locationId:"",statusCode:"",modelYear:"",minCount:"1"});const [debounced,setDebounced]=useState("");const [page,setPage]=useState(1);const [rows,setRows]=useState<ReportRow[]>([]);const [pagination,setPagination]=useState(emptyPagination);const [loading,setLoading]=useState(true);const [exporting,setExporting]=useState(false);
  useEffect(()=>{const timer=window.setTimeout(()=>setDebounced(filters.search),300);return()=>window.clearTimeout(timer)},[filters.search]);
  const load=useCallback(async()=>{setLoading(true);try{const payload=await operationsFetch<{rows:ReportRow[];pagination:PaginationType}>("reports",{query:{...filters,search:debounced,minCount:Number(filters.minCount||1),page,pageSize:40}});setRows(payload.rows||[]);setPagination(payload.pagination||emptyPagination)}catch(error){notify(error instanceof Error?error.message:"تعذر تحميل التقرير",true)}finally{setLoading(false)}},[filters.locationId,filters.statusCode,filters.modelYear,filters.minCount,debounced,page,notify]);
  useEffect(()=>{void load()},[load]);useEffect(()=>setPage(1),[debounced,filters.locationId,filters.statusCode,filters.modelYear,filters.minCount]);
  async function download(){setExporting(true);try{const all:ReportRow[]=[];let current=1,pages=1;do{const payload=await operationsFetch<{rows:ReportRow[];pagination:PaginationType}>("reports",{query:{...filters,search:debounced,minCount:Number(filters.minCount||1),page:current,pageSize:200}});all.push(...payload.rows);pages=payload.pagination.pages;current+=1;}while(current<=pages);exportXlsx(all as any,columns as any,"MZJ-Operations-All-Vehicles.xlsx","جميع السيارات");notify(`تم تصدير ${all.length} مجموعة`)}catch(error){notify(error instanceof Error?error.message:"تعذر التصدير",true)}finally{setExporting(false)}}
  return <div className="operations-page"><header className="operations-page-toolbar"><div><h2>جميع السيارات</h2><p>تقرير مجمع من نفس مصدر حقيقة المخزون، مع استبعاد الحالات الخارجة من المخزون الفعلي.</p></div><button type="button" onClick={()=>void download()} disabled={exporting}><DownloadSimple size={17}/>{exporting?"جاري التصدير...":"تصدير النتائج المفلترة"}</button></header>
    <section className="operations-filters"><label><span>بحث السيارة أو البيان</span><input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></label><label><span>المكان</span><select value={filters.locationId} onChange={e=>setFilters({...filters,locationId:e.target.value})}><option value="">كل المواقع</option>{meta.locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>الحالة</span><select value={filters.statusCode} onChange={e=>setFilters({...filters,statusCode:e.target.value})}><option value="">كل الحالات</option>{meta.statuses.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label><label><span>الموديل</span><input value={filters.modelYear} onChange={e=>setFilters({...filters,modelYear:e.target.value})}/></label><label><span>الحد الأدنى للعدد</span><input type="number" min="1" value={filters.minCount} onChange={e=>setFilters({...filters,minCount:e.target.value})}/></label></section>
    {loading?<div className="operations-loading">جاري تحميل التقرير...</div>:<><div className="operations-table-wrap"><table className="operations-table"><thead><tr><th>السيارة</th><th>البيان</th><th>الموديل</th><th>المكان</th><th>الحالة</th><th>العدد</th></tr></thead><tbody>{rows.length?rows.map((row,index)=><tr key={`${row.car_name}-${row.statement}-${row.location_name}-${row.status_name}-${index}`}><td>{row.car_name}</td><td>{row.statement}</td><td>{row.model_year}</td><td>{row.location_name}</td><td>{row.status_name}</td><td><b>{row.total}</b></td></tr>):<tr><td colSpan={6} className="operations-empty">لا توجد نتائج</td></tr>}</tbody></table></div><Pagination value={pagination} onChange={setPage}/></>}
  </div>;
}
