import { useCallback,useEffect,useMemo,useState } from "react";
import { ArrowClockwise,CheckCircle,Plus,Prohibit,Trash,Truck } from "@phosphor-icons/react";
import { operationsFetch } from "../api";
import type { OperationsMeta,Pagination as PaginationType,RequestRow,VehicleRow } from "../types";
import { Modal } from "../components/Modal";
import { Pagination } from "../components/Pagination";
import { VehicleSearchPicker } from "../components/VehicleSearchPicker";

const emptyPagination:PaginationType={page:1,pageSize:30,total:0,pages:1};
const stageLabels:Record<string,string>={draft:"جديد",request_received:"تم استلام الطلب",vehicle_sent:"تم إرسال السيارة",vehicle_received:"تم استلام السيارة",completed:"تم الانتهاء",cancelled:"ملغي"};
const nextStage:Record<string,string>={draft:"request_received",request_received:"vehicle_sent",vehicle_sent:"vehicle_received",vehicle_received:"completed"};
const permissionByStage:Record<string,string>={request_received:"operations.requests.receive_order",vehicle_sent:"operations.requests.send_vehicle",vehicle_received:"operations.requests.receive_vehicle",completed:"operations.requests.complete"};
const date=(value?:string|null)=>value?new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";
type Dialog={type:"advance"|"cancel"|"delete"|"override";request:RequestRow}|null;
export function RequestsPage({meta,notify}:{meta:OperationsMeta;notify:(message:string,error?:boolean)=>void}){
  const [tab,setTab]=useState("outgoing");const [search,setSearch]=useState("");const [debounced,setDebounced]=useState("");const [page,setPage]=useState(1);const [rows,setRows]=useState<RequestRow[]>([]);const [pagination,setPagination]=useState(emptyPagination);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
  const [createOpen,setCreateOpen]=useState(false);const [selected,setSelected]=useState<VehicleRow[]>([]);const [form,setForm]=useState({requestType:"transfer",destinationLocationId:"",targetStatusCode:"",photographyDate:"",notes:""});const [dialog,setDialog]=useState<Dialog>(null);const [note,setNote]=useState("");const [overrideStage,setOverrideStage]=useState("");
  const can=(permission:string)=>meta.permissionCodes.includes("*")||meta.permissionCodes.includes(permission);const isSystemAdmin=meta.isSystemAdmin||meta.permissionCodes.includes("*");
  const tabs=useMemo(()=>[{key:"outgoing",label:"الطلبات الصادرة من فرعي",show:can("operations.requests.view_outgoing")},{key:"incoming",label:"الطلبات الواردة إلى فرعي",show:can("operations.requests.view_incoming")},{key:"completed",label:"المكتملة",show:can("operations.requests.view_outgoing")||can("operations.requests.view_incoming")},{key:"cancelled",label:"الملغاة",show:can("operations.requests.view_outgoing")||can("operations.requests.view_incoming")},{key:"all",label:"جميع الطلبات",show:can("operations.requests.view_all")}].filter(item=>item.show),[meta.permissionCodes]);
  useEffect(()=>{const timer=window.setTimeout(()=>setDebounced(search),300);return()=>window.clearTimeout(timer)},[search]);
  const load=useCallback(async()=>{setLoading(true);try{const payload=await operationsFetch<{requests:RequestRow[];pagination:PaginationType}>("requests",{query:{tab,search:debounced,page,pageSize:30}});setRows(payload.requests||[]);setPagination(payload.pagination||emptyPagination)}catch(err){notify(err instanceof Error?err.message:"تعذر تحميل الطلبات",true)}finally{setLoading(false)}},[tab,debounced,page,notify]);
  useEffect(()=>{void load()},[load]);useEffect(()=>setPage(1),[tab,debounced]);
  function addVehicle(vehicle:VehicleRow){if(!selected.some(item=>item.id===vehicle.id))setSelected([...selected,vehicle])}function removeVehicle(id:string){setSelected(selected.filter(item=>item.id!==id))}
  async function create(){if(!selected.length)return notify("اختر سيارة واحدة على الأقل",true);setSaving(true);try{const payload=await operationsFetch<{message:string}>("requests",{method:"POST",body:JSON.stringify({...form,vehicleIds:selected.map(item=>item.id)})});notify(payload.message);setCreateOpen(false);setSelected([]);setForm({requestType:"transfer",destinationLocationId:"",targetStatusCode:"",photographyDate:"",notes:""});await load()}catch(err){notify(err instanceof Error?err.message:"تعذر إنشاء الطلب",true)}finally{setSaving(false)}}
  async function perform(){if(!dialog)return;setSaving(true);try{let payload:{message:string};if(dialog.type==="delete")payload=await operationsFetch("requests",{method:"DELETE",query:{id:dialog.request.id,reason:note||"حذف قبل بدء التنفيذ"}});else payload=await operationsFetch("requests",{method:"POST",body:JSON.stringify({action:dialog.type==="override"?"override":dialog.type,requestId:dialog.request.id,version:dialog.request.version,note,reason:note,overrideReason:note,stageCode:dialog.type==="override"?overrideStage:undefined})});notify(payload.message);setDialog(null);setNote("");setOverrideStage("");await load()}catch(err){notify(err instanceof Error?err.message:"تعذر تنفيذ الإجراء",true)}finally{setSaving(false)}}
  const dialogTitle=dialog?.type==="advance"?`تنفيذ ${stageLabels[nextStage[dialog.request.status]]||"المرحلة التالية"}`:dialog?.type==="cancel"?"إلغاء الطلب":dialog?.type==="delete"?"حذف الطلب قبل التنفيذ":"تجاوز إداري";
  return <div className="operations-page"><header className="operations-page-toolbar"><div><h2>طلبات النقل والتصوير</h2><p>كل طلب مستقل بمراحله وسياراته وصلاحيات الفرع المصدر والفرع المستهدف.</p></div>{can("operations.requests.create")?<button type="button" className="primary" onClick={()=>setCreateOpen(true)}><Plus size={17}/>إنشاء طلب</button>:null}</header>
    <nav className="operations-subtabs">{tabs.map(item=><button type="button" key={item.key} className={tab===item.key?"active":""} onClick={()=>setTab(item.key)}>{item.label}</button>)}</nav><section className="operations-filters"><label><span>بحث برقم الطلب أو VIN</span><input value={search} onChange={e=>setSearch(e.target.value)}/></label><button type="button" onClick={()=>void load()}><ArrowClockwise size={17}/>تحديث</button></section>
    {loading?<div className="operations-loading">جاري تحميل الطلبات...</div>:<div className="operations-request-list">{rows.length?rows.map(row=>{const next=nextStage[row.status];return <article key={row.id} className="operations-panel request-card"><header><div><span className={`operations-badge ${row.transfer_type==="transfer"?"progress":"warning"}`}>{row.transfer_type==="transfer"?"طلب نقل":"طلب تصوير"}</span><h3>{row.request_no}</h3><p>{row.source_branch_name||row.source_location_name||"—"} ← {row.destination_branch_name||row.destination_location_name||"—"}</p></div><div><span className={`operations-badge ${row.status==="completed"?"success":row.status==="cancelled"?"danger":"progress"}`}>{stageLabels[row.status]||row.status}</span><small>{date(row.requested_at)}</small></div></header><div className="request-meta"><p><span>منشئ الطلب</span>{row.requested_by_name||"—"}</p><p><span>السيارات</span>{row.vehicles.length}</p>{row.photography_date?<p><span>تاريخ التصوير</span>{row.photography_date}</p>:null}{row.target_status_name?<p><span>الحالة عند الاستلام</span>{row.target_status_name}</p>:null}<p className="wide"><span>الملاحظات</span>{row.notes||"—"}</p></div><div className="request-vehicles">{row.vehicles.map(vehicle=><span key={vehicle.id}><b>{vehicle.vin}</b>{vehicle.carName||"—"} • {vehicle.currentLocationName||"—"}</span>)}</div><div className="operations-timeline compact">{row.events.map((event,index)=><article key={event.id||`${event.stageCode}-${index}`}><b>{event.action==="cancelled"?"إلغاء":stageLabels[event.stageCode]||event.stageCode}{event.isOverride?" — تجاوز إداري":""}</b><span>{event.performerName} • {event.performerBranch||"—"} • {date(event.createdAt)}</span><p>{event.overrideReason||event.note||"—"}</p></article>)}</div><footer className="request-actions">{next&&can(permissionByStage[next])?<button type="button" className="primary" onClick={()=>{setDialog({type:"advance",request:row});setNote("")}}><CheckCircle size={16}/>{stageLabels[next]}</button>:null}{!["completed","cancelled"].includes(row.status)&&can("operations.requests.cancel")?<button type="button" className="danger-outline" onClick={()=>{setDialog({type:"cancel",request:row});setNote("")}}><Prohibit size={16}/>إلغاء الطلب</button>:null}{row.status==="draft"&&can("operations.requests.delete")?<button type="button" className="danger-outline" onClick={()=>{setDialog({type:"delete",request:row});setNote("")}}><Trash size={16}/>حذف</button>:null}{isSystemAdmin&&!["completed","cancelled"].includes(row.status)?<button type="button" onClick={()=>{setDialog({type:"override",request:row});setNote("");setOverrideStage(next||"")}}>تجاوز إداري</button>:null}</footer>{row.cancellation_reason?<div className="operations-inline-error">سبب الإلغاء: {row.cancellation_reason}</div>:null}</article>}):<div className="operations-empty large">لا توجد طلبات في هذا التبويب.</div>}<Pagination value={pagination} onChange={setPage}/></div>}
    <Modal open={createOpen} title="إنشاء طلب نقل أو تصوير" subtitle="لن يتم دمج الطلبات تلقائيًا، وسيُحفظ مكان وحالة كل سيارة وقت الإنشاء" onClose={()=>setCreateOpen(false)} className="wide" dirty={selected.length>0}><div className="operations-form-grid"><label><span>نوع الطلب</span><select value={form.requestType} onChange={e=>setForm({...form,requestType:e.target.value})}><option value="transfer">طلب نقل</option><option value="photography">طلب تصوير</option></select></label>{form.requestType==="transfer"?<><label><span>المكان المستهدف *</span><select value={form.destinationLocationId} onChange={e=>setForm({...form,destinationLocationId:e.target.value})}><option value="">اختر المكان</option>{meta.locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>الحالة عند الاستلام</span><select value={form.targetStatusCode} onChange={e=>setForm({...form,targetStatusCode:e.target.value})}><option value="">بدون تغيير الحالة</option>{meta.statuses.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label></>:<label><span>تاريخ التصوير *</span><input type="date" value={form.photographyDate} onChange={e=>setForm({...form,photographyDate:e.target.value})}/></label>}<label className="wide"><span>ملاحظات الطلب</span><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><VehicleSearchPicker selected={selected} onAdd={addVehicle} onRemove={removeVehicle}/><div className="operations-form-actions"><button type="button" className="primary" disabled={saving||!selected.length} onClick={()=>void create()}><Truck size={17}/>{saving?"جاري الإنشاء...":"إنشاء الطلب"}</button></div></Modal>
    <Modal open={Boolean(dialog)} title={dialogTitle||"إجراء الطلب"} subtitle={dialog?.type==="delete"?"لن يسمح السيرفر بالحذف إذا تم تنفيذ أي إجراء فعلي":"سيتم تسجيل المستخدم والفرع والتاريخ والبيانات قبل وبعد الإجراء"} onClose={()=>setDialog(null)}>{dialog?.type==="override"?<label className="operations-modal-field"><span>المرحلة المطلوب تنفيذها</span><select value={overrideStage} onChange={e=>setOverrideStage(e.target.value)}>{Object.keys(stageLabels).filter(key=>["request_received","vehicle_sent","vehicle_received","completed"].includes(key)).map(key=><option key={key} value={key}>{stageLabels[key]}</option>)}</select></label>:null}<label className="operations-modal-field"><span>{dialog?.type==="advance"?"ملاحظة المرحلة":"السبب *"}</span><textarea rows={4} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="operations-form-actions"><button type="button" className={dialog?.type==="advance"?"primary":"danger"} disabled={saving||((dialog?.type==="cancel"||dialog?.type==="override")&&!note.trim())} onClick={()=>void perform()}>{saving?"جاري التنفيذ...":"تأكيد الإجراء"}</button></div></Modal>
  </div>;
}
