import { useEffect, useMemo, useState } from "react";
import { DownloadSimple, FileArrowUp, FloppyDisk, Plus, SpinnerGap, X } from "@phosphor-icons/react";
import { downloadExcel, operationsFetch } from "../api";
import { parseSpreadsheet } from "../excel";
import type { OperationsMeta, VehicleRow } from "../types";
import { VehicleSearch } from "../components/VehicleSearch";

type Form={id:string;vin:string;carName:string;statement:string;agentName:string;interiorColor:string;exteriorColor:string;modelYear:string;plateNo:string;batchNo:string;locationId:string;statusCode:string;notes:string;statusNotes:string;missingReservationLocation:string};
const empty:Form={id:"",vin:"",carName:"",statement:"",agentName:"",interiorColor:"",exteriorColor:"",modelYear:"",plateNo:"",batchNo:"",locationId:"",statusCode:"available_for_sale",notes:"",statusNotes:"",missingReservationLocation:""};
function formFromVehicle(v:VehicleRow):Form{return{id:v.id,vin:v.vin,carName:v.car_name||"",statement:v.statement||"",agentName:v.agent_name||"",interiorColor:v.interior_color||"",exteriorColor:v.exterior_color||"",modelYear:v.model_year||"",plateNo:v.plate_no||"",batchNo:v.batch_no||"",locationId:v.location_id||"",statusCode:v.status_code,notes:v.notes||"",statusNotes:v.status_notes||"",missingReservationLocation:v.missing_reservation_location||""};}
export function VehicleManagementPage(){
  const[meta,setMeta]=useState<OperationsMeta>({locations:[],statuses:[],checklist:[]});const[form,setForm]=useState<Form>(empty);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");const[importRows,setImportRows]=useState<Array<Record<string,unknown>>>([]);const[importing,setImporting]=useState(false);const[importReport,setImportReport]=useState<Record<string,unknown>|null>(null);
  useEffect(()=>{operationsFetch<OperationsMeta&{ok:boolean}>("/api/operations?resource=meta").then(setMeta).catch((e)=>setError((e as Error).message));},[]);
  const selectedStatus=useMemo(()=>meta.statuses.find((s)=>s.code===form.statusCode),[meta.statuses,form.statusCode]);
  const set=(key:keyof Form,value:string)=>setForm((current)=>({...current,[key]:value}));
  const save=async()=>{setSaving(true);setError("");setMessage("");try{await operationsFetch("/api/operations",{method:"POST",body:JSON.stringify({action:"save_vehicle",...form})});setMessage(form.id?"تم تحديث السيارة بنجاح":"تمت إضافة السيارة بنجاح");setForm(empty);}catch(e){setError((e as Error).message);}finally{setSaving(false);}};
  const exportTemplate=()=>downloadExcel("MZJ-Operations-Vehicles-Template",["VIN","السيارة","البيان","الوكيل","اللون الداخلي","اللون الخارجي","الموديل","اللوحة","اسم الدفعة بالتاريخ","كود المكان","كود الحالة","ملاحظات في السيارة","ملاحظات الحالة","حجز - نواقص - تحديد مكان"],[["000123","مثال سيارة","الوصف","الوكيل","بيج","أبيض","2026","أ ب ج 1234","دفعة 2026-07","warehouse","available_for_sale","","",""]]);
  const handleFile=async(file?:File)=>{if(!file)return;setError("");setImportReport(null);try{const parsed=await parseSpreadsheet(file);const normalized=parsed.map((row)=>{const locationValue=String(row["locationId"]||row["كود المكان"]||row["المكان"]||"").trim();const statusValue=String(row["statusCode"]||row["كود الحالة"]||row["الحالة"]||"").trim();const location=meta.locations.find((l)=>l.id===locationValue||l.code===locationValue||l.name===locationValue);const status=meta.statuses.find((s)=>s.code===statusValue||s.name===statusValue);return{vin:row["vin"]||row["VIN"]||row["الهيكل"]||row["رقم الهيكل"],carName:row["carName"]||row["السيارة"],statement:row["statement"]||row["البيان"]||row["الوصف"],agentName:row["agentName"]||row["الوكيل"],interiorColor:row["interiorColor"]||row["اللون الداخلي"],exteriorColor:row["exteriorColor"]||row["اللون الخارجي"],modelYear:row["modelYear"]||row["الموديل"],plateNo:row["plateNo"]||row["اللوحة"],batchNo:row["batchNo"]||row["اسم الدفعة بالتاريخ"],locationId:location?.id||"",statusCode:status?.code||"",notes:row["notes"]||row["ملاحظات في السيارة"],statusNotes:row["statusNotes"]||row["ملاحظات الحالة"],missingReservationLocation:row["missingReservationLocation"]||row["حجز - نواقص - تحديد مكان"]};});setImportRows(normalized);}catch(e){setError((e as Error).message);}};
  const runImport=async()=>{setImporting(true);setError("");try{const payload=await operationsFetch<{report:Record<string,unknown>}>("/api/operations",{method:"POST",body:JSON.stringify({action:"import_vehicles",rows:importRows})});setImportReport(payload.report);setImportRows([]);}catch(e){setError((e as Error).message);}finally{setImporting(false);}};
  return <div className="operations-management-grid">
    <section className="panel operations-page vehicle-form-panel"><header className="operations-page-title"><div><span>{form.id?"تعديل سجل قائم":"سجل جديد"}</span><h2>{form.id?`تعديل السيارة ${form.vin}`:"إضافة سيارة"}</h2><p>يحفظ VIN كنص ويحافظ على الأصفار في بدايته.</p></div>{form.id?<button type="button" className="operations-secondary-button" onClick={()=>setForm(empty)}><X size={17}/>إلغاء التعديل</button>:null}</header>
      <div className="operations-edit-search"><b>اختيار سيارة للتعديل</b><VehicleSearch onSelect={(vehicle)=>setForm(formFromVehicle(vehicle))}/></div>
      {error?<div className="operations-error">{error}</div>:null}{message?<div className="operations-success">{message}</div>:null}
      <div className="operations-form-grid"><label><span>VIN *</span><input value={form.vin} onChange={(e)=>set("vin",e.target.value)} placeholder="رقم الهيكل"/></label><label><span>السيارة *</span><input value={form.carName} onChange={(e)=>set("carName",e.target.value)}/></label><label><span>البيان / الوصف</span><input value={form.statement} onChange={(e)=>set("statement",e.target.value)}/></label><label><span>الوكيل</span><input value={form.agentName} onChange={(e)=>set("agentName",e.target.value)}/></label><label><span>اللون الداخلي</span><input value={form.interiorColor} onChange={(e)=>set("interiorColor",e.target.value)}/></label><label><span>اللون الخارجي</span><input value={form.exteriorColor} onChange={(e)=>set("exteriorColor",e.target.value)}/></label><label><span>الموديل</span><input value={form.modelYear} onChange={(e)=>set("modelYear",e.target.value)}/></label><label><span>اللوحة</span><input value={form.plateNo} onChange={(e)=>set("plateNo",e.target.value)}/></label><label><span>اسم الدفعة بالتاريخ</span><input value={form.batchNo} onChange={(e)=>set("batchNo",e.target.value)}/></label><label><span>المكان *</span><select value={form.locationId} onChange={(e)=>set("locationId",e.target.value)}><option value="">اختر المكان</option>{meta.locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>الحالة *</span><select value={form.statusCode} onChange={(e)=>set("statusCode",e.target.value)}>{meta.statuses.map((item)=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label><label className="full"><span>ملاحظات في السيارة</span><textarea value={form.notes} onChange={(e)=>set("notes",e.target.value)}/></label>{selectedStatus?.requires_status_note?<label className="full required-note"><span>ملاحظات الحالة *</span><textarea value={form.statusNotes} onChange={(e)=>set("statusNotes",e.target.value)}/></label>:null}<label className="full"><span>حجز - نواقص - تحديد مكان</span><textarea value={form.missingReservationLocation} onChange={(e)=>set("missingReservationLocation",e.target.value)}/></label></div>
      <button type="button" className="operations-primary-button save-vehicle" onClick={()=>void save()} disabled={saving}>{saving?<SpinnerGap className="spin" size={18}/>:form.id?<FloppyDisk size={18}/>:<Plus size={18}/>} {saving?"جاري الحفظ...":form.id?"حفظ التعديل":"إضافة السيارة"}</button>
    </section>
    <section className="panel operations-page import-panel"><header className="operations-page-title"><div><span>Excel</span><h2>الاستيراد والتصدير</h2><p>معاينة الصفوف قبل الإرسال ومنع تكرار VIN داخل الملف.</p></div></header><div className="operations-import-actions"><button type="button" className="operations-secondary-button" onClick={exportTemplate}><DownloadSimple size={18}/>تصدير قالب فاضي</button><label className="operations-file-button"><FileArrowUp size={18}/><span>استيراد من Excel</span><input type="file" accept=".xlsx,.xls,.csv,.tsv" onChange={(e)=>void handleFile(e.target.files?.[0])}/></label></div>
      {importRows.length?<><div className="operations-import-summary"><b>{importRows.length.toLocaleString("ar-SA")} صف جاهز للمعالجة</b><span>سيتم اكتشاف الإضافة أو التحديث باستخدام VIN.</span></div><div className="operations-table-wrap import-preview"><table className="operations-table compact"><thead><tr><th>#</th><th>VIN</th><th>السيارة</th><th>المكان</th><th>الحالة</th></tr></thead><tbody>{importRows.slice(0,50).map((row,index)=><tr key={`${String(row.vin)}-${index}`}><td>{index+2}</td><td>{String(row.vin||"—")}</td><td>{String(row.carName||"—")}</td><td>{meta.locations.find((l)=>l.id===row.locationId)?.name||"غير محدد"}</td><td>{meta.statuses.find((s)=>s.code===row.statusCode)?.name||"غير محدد"}</td></tr>)}</tbody></table></div><button type="button" className="operations-primary-button" disabled={importing} onClick={()=>void runImport()}>{importing?"جاري الاستيراد...":"تنفيذ الاستيراد"}</button></>:null}
      {importReport?<div className="operations-import-report"><h3>نتيجة الاستيراد</h3><div><span>الصفوف المقروءة <b>{String(importReport.total||0)}</b></span><span>تمت الإضافة <b>{String(importReport.added||0)}</b></span><span>تم التحديث <b>{String(importReport.updated||0)}</b></span><span>فشل <b>{String(importReport.failed||0)}</b></span></div></div>:null}
    </section>
  </div>;
}
