import { useCallback,useEffect,useMemo,useState } from "react";
import { Archive,Plus,WarningCircle } from "@phosphor-icons/react";
import { operationsFetch } from "../api";
import type { OperationsMeta,Pagination as PaginationType,VehicleRow } from "../types";
import { Modal } from "../components/Modal";
import { Pagination } from "../components/Pagination";
import { TrackingModal } from "../components/TrackingModal";
import { VehicleDetailsModal } from "../components/VehicleDetailsModal";
import { VehicleTable } from "../components/VehicleTable";

type Mode="inventory"|"manage"|"archive";
type FormState={id:string;version:number;originalLocationCode:string;vin:string;carName:string;statement:string;agentName:string;interiorColor:string;exteriorColor:string;modelYear:string;plateNo:string;batchNo:string;locationId:string;statusCode:string;statusNote:string;sourceType:string;notes:string;placeNotes:string;bookingShortageLocationNotes:string;checks:Record<string,boolean>};
const empty:FormState={id:"",version:0,originalLocationCode:"",vin:"",carName:"",statement:"",agentName:"",interiorColor:"",exteriorColor:"",modelYear:"",plateNo:"",batchNo:"",locationId:"",statusCode:"available_for_sale",statusNote:"",sourceType:"",notes:"",placeNotes:"",bookingShortageLocationNotes:"",checks:{}};
const emptyPagination:PaginationType={page:1,pageSize:30,total:0,pages:1};
function toForm(row:VehicleRow):FormState{return{id:row.id,version:row.version,originalLocationCode:row.location_code||"",vin:row.vin,carName:row.car_name||"",statement:row.statement||"",agentName:row.agent_name||"",interiorColor:row.interior_color||"",exteriorColor:row.exterior_color||"",modelYear:row.model_year||"",plateNo:row.plate_no||"",batchNo:row.batch_no||"",locationId:row.location_id||"",statusCode:row.status_code,statusNote:row.status_note||"",sourceType:row.source_type||"",notes:row.notes||"",placeNotes:row.place_notes||"",bookingShortageLocationNotes:row.booking_shortage_location_notes||"",checks:{...(row.check_items||{})}}}

export function VehicleListPage({mode,meta,notify}:{mode:Mode;meta:OperationsMeta;notify:(message:string,error?:boolean)=>void}){
  const [rows,setRows]=useState<VehicleRow[]>([]);const [loading,setLoading]=useState(true);const [page,setPage]=useState(1);const [pagination,setPagination]=useState(emptyPagination);
  const [filters,setFilters]=useState({search:"",locationId:"",statusCode:"",modelYear:"",archived:mode==="archive"?"only":"hide"});const [debounced,setDebounced]=useState(filters.search);
  const [detailId,setDetailId]=useState<string|null>(null);const [tracking,setTracking]=useState<VehicleRow|null>(null);const [form,setForm]=useState<FormState|null>(null);const [saving,setSaving]=useState(false);
  const [archiveTarget,setArchiveTarget]=useState<VehicleRow|null>(null);const [archiveReason,setArchiveReason]=useState("");
  const can=(permission:string)=>meta.permissionCodes.includes("*")||meta.permissionCodes.includes(permission);
  useEffect(()=>{const timer=window.setTimeout(()=>setDebounced(filters.search),300);return()=>window.clearTimeout(timer)},[filters.search]);
  const load=useCallback(async()=>{setLoading(true);try{const payload=await operationsFetch<{vehicles:VehicleRow[];pagination:PaginationType}>(mode==="archive"?"archive":"vehicles",{query:{...filters,search:debounced,page,pageSize:30,archived:mode==="archive"?"only":filters.archived}});setRows(payload.vehicles||[]);setPagination(payload.pagination||emptyPagination);}catch(err){notify(err instanceof Error?err.message:"تعذر تحميل السيارات",true)}finally{setLoading(false)}},[mode,filters,debounced,page,notify]);
  useEffect(()=>{void load()},[load]);useEffect(()=>setPage(1),[debounced,filters.locationId,filters.statusCode,filters.modelYear,filters.archived]);
  useEffect(()=>{const refresh=()=>void load();window.addEventListener("operations:data-changed",refresh);return()=>window.removeEventListener("operations:data-changed",refresh)},[load]);
  const selectedLocation=useMemo(()=>meta.locations.find(item=>item.id===form?.locationId),[meta.locations,form?.locationId]);
  const checklistAllowed=Boolean(form&&(form.id?form.originalLocationCode==="agency":selectedLocation?.code==="agency"));
  function field(key:keyof FormState,label:string,type="text"){return <label><span>{label}</span><input type={type} value={String(form?.[key]??"")} onChange={e=>setForm(current=>current?{...current,[key]:e.target.value}:current)}/></label>}
  async function save(){if(!form)return;setSaving(true);try{const payload=await operationsFetch<{message:string}>("vehicles",{method:"POST",body:JSON.stringify({...form,locationId:form.locationId,statusCode:form.statusCode})});notify(payload.message);setForm(null);await load();}catch(err){notify(err instanceof Error?err.message:"تعذر الحفظ",true)}finally{setSaving(false)}}
  async function archive(){if(!archiveTarget)return;setSaving(true);try{const payload=await operationsFetch<{message:string}>("archive",{method:"POST",body:JSON.stringify({vehicleId:archiveTarget.id,reason:archiveReason})});notify(payload.message);setArchiveTarget(null);setArchiveReason("");await load();}catch(err){notify(err instanceof Error?err.message:"تعذر الأرشفة",true)}finally{setSaving(false)}}
  const title=mode==="inventory"?"مخزون السيارات":mode==="manage"?"إدارة السيارات":"أرشيف السيارات";
  return <div className="operations-page"><header className="operations-page-toolbar"><div><h2>{title}</h2><p>{mode==="archive"?"السيارات محفوظة منطقيًا بكل حركاتها وموافقاتها وطلبات التراكينج.":"البحث والفلترة يتمان من PostgreSQL مع Pagination وصلاحيات الفروع."}</p></div>{mode==="manage"&&can("operations.vehicles.create")?<button type="button" className="primary" onClick={()=>setForm({...empty,locationId:meta.locations[0]?.id||"",statusCode:meta.statuses[0]?.code||"available_for_sale"})}><Plus size={17}/>إضافة سيارة</button>:null}</header>
    <section className="operations-filters"><label><span>بحث VIN أو السيارة</span><input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="يدعم جزء من رقم الهيكل ويحافظ على الأصفار"/></label><label><span>المكان</span><select value={filters.locationId} onChange={e=>setFilters({...filters,locationId:e.target.value})}><option value="">كل المواقع</option>{meta.locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>الحالة</span><select value={filters.statusCode} onChange={e=>setFilters({...filters,statusCode:e.target.value})}><option value="">كل الحالات</option>{meta.statuses.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label><label><span>الموديل</span><input value={filters.modelYear} onChange={e=>setFilters({...filters,modelYear:e.target.value})}/></label>{mode==="inventory"?<label><span>الأرشيف</span><select value={filters.archived} onChange={e=>setFilters({...filters,archived:e.target.value})}><option value="hide">إخفاء المؤرشف</option><option value="all">الكل</option><option value="only">المؤرشف فقط</option></select></label>:null}</section>
    {loading?<div className="operations-loading">جاري تحميل النتائج...</div>:<><VehicleTable rows={rows} onView={setDetailId} onTracking={setTracking} manage={mode==="manage"} onEdit={mode==="manage"&&can("operations.vehicles.update")?row=>setForm(toForm(row)):undefined} onArchive={mode!=="archive"&&can("operations.archive")?row=>{setArchiveTarget(row);setArchiveReason("")}:undefined}/><Pagination value={pagination} onChange={setPage}/></>}
    <VehicleDetailsModal vehicleId={detailId} onClose={()=>setDetailId(null)}/><TrackingModal vehicle={tracking} onClose={()=>setTracking(null)}/>
    <Modal open={Boolean(form)} title={form?.id?"تعديل السيارة":"إضافة سيارة"} subtitle="لا تُحذف الموافقات أو الحركات أو الطلبات عند تعديل السيارة" onClose={()=>setForm(null)} className="wide" dirty={Boolean(form)}>{form?<form className="operations-form" onSubmit={e=>{e.preventDefault();void save()}}><div className="operations-form-grid">{field("vin","الهيكل VIN")}{field("carName","السيارة")}{field("statement","البيان")}{field("agentName","الوكيل")}{field("interiorColor","اللون الداخلي")}{field("exteriorColor","اللون الخارجي")}{field("modelYear","الموديل")}{field("plateNo","اللوحة")}{field("batchNo","اسم الدفعة بالتاريخ")}<label><span>المكان</span><select required value={form.locationId} onChange={e=>setForm({...form,locationId:e.target.value})}><option value="">اختر المكان</option>{meta.locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>الحالة</span><select required value={form.statusCode} onChange={e=>setForm({...form,statusCode:e.target.value})}>{meta.statuses.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label>{form.statusCode==="has_notes"?<label className="wide"><span>ملاحظات الحالة *</span><textarea required rows={3} value={form.statusNote} onChange={e=>setForm({...form,statusNote:e.target.value})}/></label>:null}<label className="wide"><span>ملاحظات في السيارة</span><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label className="wide"><span>حجز - نواقص - تحديد مكان</span><textarea rows={3} value={form.bookingShortageLocationNotes} onChange={e=>setForm({...form,bookingShortageLocationNotes:e.target.value})}/></label><label className="wide"><span>ملاحظات المكان</span><textarea rows={2} value={form.placeNotes} onChange={e=>setForm({...form,placeNotes:e.target.value})}/></label></div>{checklistAllowed?<div><h3>التشيك — يظهر لأن المكان الحالي هو الوكالة</h3><div className="operations-check-grid">{meta.checkItems.map(item=><label key={item.code}><input type="checkbox" checked={Boolean(form.checks[item.code])} onChange={e=>setForm({...form,checks:{...form.checks,[item.code]:e.target.checked}})}/><span>{item.name}</span></label>)}</div></div>:<div className="operations-info"><WarningCircle size={18}/>التشيك لا يظهر ولا يتغير إلا عندما يكون المكان الحالي للسيارة هو «الوكالة».</div>}<div className="operations-form-actions"><button className="primary" disabled={saving}>{saving?"جاري الحفظ...":"حفظ"}</button></div></form>:null}</Modal>
    <Modal open={Boolean(archiveTarget)} title="أرشفة السيارة" subtitle="سيعيد الـAPI فحص الحالة النهائية والموافقات والحركة وTracking 100% والطلبات النشطة" onClose={()=>setArchiveTarget(null)}><label className="operations-modal-field"><span>سبب الأرشفة *</span><textarea rows={4} required value={archiveReason} onChange={e=>setArchiveReason(e.target.value)}/></label><div className="operations-form-actions"><button type="button" className="danger" disabled={saving||!archiveReason.trim()} onClick={()=>void archive()}><Archive size={17}/>تنفيذ الأرشفة</button></div></Modal>
  </div>;
}
