import { useEffect,useState } from 'react';
import { ArrowSquareOut,Copy,Gift,ShareNetwork,SignOut,Star,WhatsappLogo } from '@phosphor-icons/react';
import { ownersPublicGet,ownersPublicPost } from './api';
function date(v:any){if(!v)return '—';return new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium'}).format(new Date(v))}
export function OwnersPortalPage(){
 const [me,setMe]=useState<any>(null); const [phone,setPhone]=useState(''); const [challenge,setChallenge]=useState(''); const [code,setCode]=useState(''); const [stage,setStage]=useState<'phone'|'otp'>('phone'); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 async function load(){try{const x=await ownersPublicGet('me');setMe(x)}catch{setMe(null)}} useEffect(()=>{void load()},[]);
 async function otp(){setBusy(true);setMessage('');try{const x=await ownersPublicPost({action:'request_otp',phone});setChallenge(x.challengeId);setStage('otp');setMessage('تم إرسال رمز التحقق إلى واتساب')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function verify(){setBusy(true);setMessage('');try{await ownersPublicPost({action:'verify_otp',phone,challengeId:challenge,code});await load()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 if(!me)return <div className="owners-public" dir="rtl"><div className="owners-login-card"><img src="/logo.png"/><span className="owners-eyebrow">MZJ Owners Community</span><h1>مجتمع ملاك MZJ</h1><p>ادخل برقم الجوال المسجل في عملية الشراء. سنرسل لك رمز تحقق عبر واتساب.</p>{message?<div className="owners-public-message">{message}</div>:null}{stage==='phone'?<><label><span>رقم الجوال</span><input inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="05xxxxxxxx"/></label><button disabled={busy} onClick={()=>void otp()}><WhatsappLogo size={20}/>{busy?'جاري الإرسال...':'إرسال رمز التحقق'}</button></>:<><label><span>رمز التحقق</span><input inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000"/></label><button disabled={busy||code.length!==6} onClick={()=>void verify()}>{busy?'جاري التحقق...':'دخول الحساب'}</button><button className="owners-ghost" onClick={()=>setStage('phone')}>تغيير رقم الجوال</button></>}</div></div>;
 const m=me.member; const referrals=me.referrals||[]; const rewards=me.rewards||[];
 async function copy(){await navigator.clipboard.writeText(m.inviteUrl);setMessage('تم نسخ رابط دعوتك')}
 async function redeem(id:string){setBusy(true);try{await ownersPublicPost({action:'redeem',rewardId:id});await load();setMessage('تم إرسال طلب الاستبدال')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 return <div className="owners-public portal" dir="rtl"><header className="owners-public-head"><div><img src="/logo.png"/><div><span>MZJ Owners Community</span><strong>أهلًا {m.name||'بك'} 👋</strong></div></div><button onClick={async()=>{await ownersPublicPost({action:'logout'});setMe(null)}}><SignOut size={18}/> خروج</button></header><main>
  {message?<div className="owners-public-message">{message}</div>:null}
  <section className="owners-member-card"><div><span>رصيدك الحالي</span><strong>{Number(m.points||0).toLocaleString('ar-SA-u-nu-latn')}</strong><small>نقطة</small></div><div><span>مستوى العضوية</span><b><Star size={18} weight="fill"/> {m.tier}</b></div></section>
  <section className="owners-invite-card"><div><ShareNetwork size={28}/><div><h2>شارك MZJ مع أصحابك</h2><p>كل صديق جديد يتفاعل أو يسجل أو يشتري يقربك من مكافأتك التالية حسب قواعد البرنامج.</p></div></div><div className="owners-invite-link"><input readOnly value={m.inviteUrl}/><button onClick={()=>void copy()}><Copy size={18}/> نسخ</button><a href={`https://wa.me/?text=${encodeURIComponent(`ميزة خاصة من MZJ عبر رابط دعوتي: ${m.inviteUrl}`)}`} target="_blank"><WhatsappLogo size={18}/> واتساب</a></div></section>
  <section className="owners-public-stats"><article><strong>{referrals.length}</strong><span>أصدقاء مسجلون</span></article><article><strong>{referrals.filter((r:any)=>r.status==='qualified'||r.status==='sold').length}</strong><span>عملاء مؤهلون</span></article><article><strong>{referrals.filter((r:any)=>r.status==='sold').length}</strong><span>مبيعات ناجحة</span></article></section>
  <section className="owners-public-section"><h2>المكافآت المتاحة</h2><div className="owners-public-rewards">{rewards.map((r:any)=><article key={r.id}><Gift size={25}/><h3>{r.name}</h3><p>{r.description}</p><strong>{Number(r.points_cost).toLocaleString('ar-SA-u-nu-latn')} نقطة</strong><button disabled={busy||Number(m.points)<Number(r.points_cost)} onClick={()=>void redeem(r.id)}>استبدال النقاط</button></article>)}</div></section>
  <section className="owners-public-section"><h2>رحلة دعوتك</h2><div className="owners-referral-list">{referrals.length?referrals.map((r:any)=><article key={r.id}><div><strong>{r.referred_name||'صديق من دعوتك'}</strong><span>{r.status==='sold'?'تم البيع':r.status==='qualified'?'مؤهل':r.status==='registered'?'تم التسجيل':'فتح الرابط'}</span></div><small>{date(r.registered_at||r.created_at)}</small></article>):<p>لسه مفيش دعوات مسجلة. شارك رابطك وابدأ تجمع نقاط.</p>}</div></section>
  <section className="owners-public-section"><h2>كشف النقاط</h2><div className="owners-ledger">{(me.ledger||[]).map((l:any)=><article key={l.id}><span>{l.description||l.event_type}</span><strong className={Number(l.points)>=0?'plus':'minus'}>{Number(l.points)>=0?'+':''}{l.points}</strong><small>{date(l.created_at)}</small></article>)}</div></section>
 </main></div>
}
