import { useEffect,useMemo,useState } from 'react';
import { ArrowsClockwise,CheckCircle,Crown,Gift,PaperPlaneTilt,ShareNetwork,UsersThree,Wallet } from '@phosphor-icons/react';
import { useAuth } from '../auth/AuthContext';
import { hasPermission } from '../systemAccess';
import { ownersAdminGet,ownersAdminPost } from './api';

type Tab='members'|'referrals'|'rewards'|'redemptions';
function date(value:any){if(!value)return '—';try{return new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}catch{return String(value)}}
export function OwnersCommunityPage(){
 const {user}=useAuth(); const canManage=hasPermission(user,'owners.community.manage'); const [data,setData]=useState<any>(null); const [tab,setTab]=useState<Tab>('members'); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [reward,setReward]=useState<any>({name:'',description:'',pointsCost:500,stockQuantity:'',isActive:true});
 async function load(){const x=await ownersAdminGet();setData(x)}
 useEffect(()=>{void load().catch(e=>setMessage(e.message))},[]);
 async function act(payload:Record<string,unknown>){setBusy(true);setMessage('');try{await ownersAdminPost(payload);await load();setMessage('تم تنفيذ العملية بنجاح')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 const stats=data?.stats||{}; const members=data?.members||[]; const referrals=data?.referrals||[]; const rewards=data?.rewards||[]; const redemptions=data?.redemptions||[];
 const soldRate=useMemo(()=>Number(stats.referrals||0)?Math.round(Number(stats.referral_sales||0)*100/Number(stats.referrals||1)):0,[stats]);
 if(!data)return <div className="module-page"><div className="owners-panel owners-loading">جاري تحميل MZJ Owners Community...</div></div>;
 return <div className="module-page owners-admin-page" dir="rtl">
  <header className="owners-hero"><div><span className="owners-hero-icon"><Crown size={30} weight="duotone"/></span><div><h1>MZJ Owners Community</h1><p>إدارة مجتمع ملاك MZJ، الدعوات، النقاط، المكافآت والمبيعات الناتجة من العملاء.</p></div></div>{canManage?<button className="owners-primary" disabled={busy} onClick={()=>void act({action:'sync_members'})}><ArrowsClockwise size={18}/>{busy?'جاري المزامنة...':'مزامنة المبيعات والدعوات'}</button>:null}</header>
  {message?<div className="owners-notice">{message}</div>:null}
  <section className="owners-stat-grid">
   <article><UsersThree size={24}/><div><span>الأعضاء</span><strong>{Number(stats.members||0).toLocaleString('ar-SA-u-nu-latn')}</strong></div></article>
   <article><ShareNetwork size={24}/><div><span>الدعوات المسجلة</span><strong>{Number(stats.referrals||0).toLocaleString('ar-SA-u-nu-latn')}</strong></div></article>
   <article><CheckCircle size={24}/><div><span>مبيعات من الدعوات</span><strong>{Number(stats.referral_sales||0).toLocaleString('ar-SA-u-nu-latn')} <small>{soldRate}%</small></strong></div></article>
   <article><Wallet size={24}/><div><span>النقاط القائمة</span><strong>{Number(stats.outstanding_points||0).toLocaleString('ar-SA-u-nu-latn')}</strong></div></article>
   <article><Gift size={24}/><div><span>استبدالات تنتظر المراجعة</span><strong>{Number(stats.pending_redemptions||0).toLocaleString('ar-SA-u-nu-latn')}</strong></div></article>
  </section>
  <nav className="owners-tabs"><button className={tab==='members'?'active':''} onClick={()=>setTab('members')}>الأعضاء</button><button className={tab==='referrals'?'active':''} onClick={()=>setTab('referrals')}>الدعوات</button><button className={tab==='rewards'?'active':''} onClick={()=>setTab('rewards')}>المكافآت</button><button className={tab==='redemptions'?'active':''} onClick={()=>setTab('redemptions')}>طلبات الاستبدال</button></nav>
  {tab==='members'?<section className="owners-table-card"><header><h2>أعضاء MZJ Owners Community</h2><span>{members.length} عضو ظاهر</span></header><div className="owners-table-wrap"><table><thead><tr><th>العميل</th><th>الجوال</th><th>كود الدعوة</th><th>النقاط</th><th>الدعوات</th><th>المبيعات</th><th>آخر شراء</th><th>الإجراءات</th></tr></thead><tbody>{members.map((m:any)=><tr key={m.id}><td><strong>{m.customer_name||'عميل MZJ'}</strong></td><td>{m.phone_normalized}</td><td><code>{m.referral_code}</code></td><td>{Number(m.points_balance||0).toLocaleString('ar-SA-u-nu-latn')}</td><td>{m.referrals_count||0}</td><td>{m.sales_count||0}</td><td>{date(m.last_sale_at)}</td><td>{canManage?<button className="owners-link-btn" onClick={()=>void act({action:'send_welcome',memberId:m.id})}><PaperPlaneTilt size={16}/> إرسال الترحيب</button>:'—'}</td></tr>)}</tbody></table></div></section>:null}
  {tab==='referrals'?<section className="owners-table-card"><header><h2>رحلة الدعوات</h2><span>مرتبطة بالـCRM والمبيعات</span></header><div className="owners-table-wrap"><table><thead><tr><th>صاحب الدعوة</th><th>الصديق</th><th>الجوال</th><th>الحالة</th><th>التسجيل</th><th>التأهيل</th><th>البيع</th></tr></thead><tbody>{referrals.map((r:any)=><tr key={r.id}><td>{r.referrer_name}<small className="owners-sub">{r.referral_code}</small></td><td>{r.referred_name||'—'}</td><td>{r.referred_phone_normalized||'—'}</td><td><span className={`owners-status ${r.status}`}>{r.status==='sold'?'تم البيع':r.status==='qualified'?'مؤهل':r.status==='registered'?'مسجل':'فتح الرابط'}</span></td><td>{date(r.registered_at)}</td><td>{date(r.qualified_at)}</td><td>{date(r.sold_at)}</td></tr>)}</tbody></table></div></section>:null}
  {tab==='rewards'?<><section className="owners-table-card"><header><h2>كتالوج المكافآت</h2><span>يمكن تغيير المكافآت بدون تغيير نقاط العملاء</span></header><div className="owners-rewards-grid">{rewards.map((r:any)=><article key={r.id}><Gift size={24}/><strong>{r.name}</strong><p>{r.description||'مكافأة لأعضاء المجتمع'}</p><b>{Number(r.points_cost).toLocaleString('ar-SA-u-nu-latn')} نقطة</b><small>{r.stock_quantity==null?'كمية مفتوحة':`المتبقي ${Math.max(0,Number(r.stock_quantity)-Number(r.redeemed_quantity||0))}`}</small></article>)}</div></section>{canManage?<section className="owners-table-card owners-reward-editor"><header><h2>إضافة مكافأة جديدة</h2></header><div className="owners-form-grid"><label><span>اسم المكافأة</span><input value={reward.name} onChange={e=>setReward({...reward,name:e.target.value})}/></label><label><span>النقاط المطلوبة</span><input type="number" min="1" value={reward.pointsCost} onChange={e=>setReward({...reward,pointsCost:Number(e.target.value)})}/></label><label><span>الكمية المتاحة</span><input type="number" min="0" placeholder="اتركها فارغة لكمية مفتوحة" value={reward.stockQuantity} onChange={e=>setReward({...reward,stockQuantity:e.target.value})}/></label><label className="wide"><span>الوصف</span><textarea value={reward.description} onChange={e=>setReward({...reward,description:e.target.value})}/></label></div><button className="owners-primary" onClick={()=>void act({action:'save_reward',...reward})}><Gift size={18}/> إضافة المكافأة</button></section>:null}</>:null}
  {tab==='redemptions'?<section className="owners-table-card"><header><h2>طلبات استبدال النقاط</h2><span>الموافقة والتسليم بسجل واضح</span></header><div className="owners-table-wrap"><table><thead><tr><th>العميل</th><th>المكافأة</th><th>النقاط</th><th>الحالة</th><th>تاريخ الطلب</th><th>الإجراء</th></tr></thead><tbody>{redemptions.map((r:any)=><tr key={r.id}><td>{r.customer_name}<small className="owners-sub">{r.phone_normalized}</small></td><td>{r.reward_name}</td><td>{r.points_cost}</td><td>{r.status}</td><td>{date(r.created_at)}</td><td>{canManage&&r.status==='requested'?<div className="owners-actions"><button onClick={()=>void act({action:'redemption',id:r.id,status:'approved'})}>اعتماد</button><button onClick={()=>void act({action:'redemption',id:r.id,status:'rejected'})}>رفض</button></div>:canManage&&r.status==='approved'?<button className="owners-link-btn" onClick={()=>void act({action:'redemption',id:r.id,status:'delivered'})}>تم التسليم</button>:'—'}</td></tr>)}</tbody></table></div></section>:null}
 </div>
}
