name = "mersal-crm"
main = "src/index.js"
compatibility_date = "2026-07-01"

[vars]
MZJ_PLATFORM_INBOUND_URL = "https://mzj-platform.vercel.app/api/integrations/whatsapp"
MZJ_PLATFORM_MEDIA_URL = "https://mzj-platform.vercel.app/api/integrations/media"
MERSAL_SEND_URL = "https://w-mersal.com/api/wpbox/sendmessage"
MERSAL_TEMPLATE_URL = "https://w-mersal.com/api/wpbox/sendtemplatemessage"
MERSAL_MEDIA_SEND_URL = "https://w-mersal.com/api/wpbox/sendmedia"
MERSAL_TEMPLATES_URL = "https://w-mersal.com/api/wpbox/getTemplates"
MERSAL_CONVERSATIONS_URL = "https://w-mersal.com/api/wpbox/getConversations/none?mobile_api=true"
MERSAL_MESSAGES_URL = "https://w-mersal.com/api/wpbox/getMessages"
