import { useEffect,useState } from "react";
import { ArrowClockwise,ChatCircleDots,MagnifyingGlass } from "@phosphor-icons/react";
import { crmFetch,formatDate } from "../api";
import { sourceLabel } from "../sourceCatalog";
export function CrmInboxPage(){
  const [rows,setRows]=useState<any[]>([]),[search,setSearch]=useState(""),[state,setState]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(false);
  async function load(){setLoading(true);try{const q=new URLSearchParams();if(search)q.set("search",search);if(state)q.set("state",state);const result=await crmFetch<any>(`/api/crm/inbox?${q}`);setRows(result.rows||[])}catch(error){setNotice(error instanceof Error?error.message:"تعذر تحميل صندوق الوارد")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function classify(id:string,serviceKey:string){try{await crmFetch("/api/crm/inbox",{method:"POST",body:JSON.stringify({conversationId:id,serviceKey})});setNotice("تم تصنيف المحادثة وإنشاء الطلب وتوزيعه.");await load()}catch(error){setNotice(error instanceof Error?error.message:"فشل التصنيف")}}
  return <div className="crm-page crm-unified-inbox"><header className="crm-page-head"><div><h1>صندوق الوارد الموحد</h1><p>كل الرسائل تدخل هنا أولًا. العميل غير المصنف لا يُنشأ له ليد ولا يتوزع قبل اختيار الخدمة.</p></div><button className="crm-secondary-button" onClick={()=>void load()}><ArrowClockwise size={18}/>{loading?"جاري التحميل":"تحديث"}</button></header>{notice?<div className="crm-inline-notice">{notice}</div>:null}<section className="crm-panel crm-filter-bar"><label><MagnifyingGlass size={18}/><input placeholder="بحث بالاسم أو الرقم أو الرسالة" value={search} onChange={(e)=>setSearch(e.target.value)} onKeyDown={(e)=>{if(e.key==="Enter")void load()}}/></label><select value={state} onChange={(e)=>setState(e.target.value)}><option value="">كل المحادثات</option><option value="new">محادثة جديدة</option><option value="awaiting_service">بانتظار اختيار الخدمة</option><option value="classified">تم التصنيف</option><option value="closed">طلب مغلق</option></select><button className="crm-primary-button" onClick={()=>void load()}>تطبيق</button></section><div className="crm-inbox-cards">{rows.map((row)=><article className={`crm-panel crm-inbox-card ${row.unread_count?"unread":""}`} key={row.id}><header><span className="crm-inbox-avatar"><ChatCircleDots size={24}/></span><div><strong>{row.lead_customer_name||row.customer_name||"عميل"}</strong><small>{row.primary_phone||row.primary_phone_normalized||row.participant_id||"بدون رقم"} • {sourceLabel(row.channel_code)}</small></div><time>{formatDate(row.last_message_at)}</time></header><p>{row.preview_text||"مرفق جديد"}</p><footer><span>{row.classification_state==="awaiting_service"?"بانتظار اختيار الخدمة":row.classification_state==="classified"?`المسؤول: ${row.assigned_name||"غير موزع"}`:"محادثة جديدة"}</span>{!row.service_request_id?<div className="crm-inbox-classify"><button onClick={()=>void classify(row.id,"cash")}>كاش</button><button onClick={()=>void classify(row.id,"finance")}>تمويل</button><button onClick={()=>void classify(row.id,"service")}>خدمة العملاء</button></div>:null}</footer></article>)}{!rows.length?<div className="crm-empty-state">لا توجد محادثات مطابقة.</div>:null}</div></div>
}
