import { getSql } from "./_db.js";
import type { SessionUser } from "./_auth.js";
import type { DashboardData } from "../src/types.js";

const locationNames = [["warehouse","المستودع"],["agency","الوكالة"],["hall","الصالة"],["qadisiyah","القادسية"],["multaqa","الملتقى"]] as const;
function emptyData(connected=false):DashboardData{return{connected,generatedAt:new Date().toISOString(),crm:{totalCustomers:null,openConversations:null,potentialCustomers:null,sold:null,cashSales:null,financeSales:null,customerService:null,newToday:null,newThisWeek:null,recentConversations:[],newCustomersSeries:[]},marketing:{campaigns:null,scheduled:null,delayed:null},tracking:{requests:null,inProgress:null,completed:null},operations:{inventory:{actualTotal:null,agency:null,availableForSale:null,underDelivery:null,hasNotes:null},locations:locationNames.map(([key,name])=>({key,name,actualTotal:null,underDelivery:null,availableForSale:null,reserved:null,delivered:null,hasNotes:null})),approvals:{total:null,missingFinancial:null,missingAdministrative:null,completed:null},shortages:{total:null,multaqa:null,hall:null,qadisiyah:null},transfers:{total:null,requestReceived:null,vehicleReceived:null,vehicleSent:null,completed:null},salesTracking:{total:null,notStarted:null,inProgress:null,completed:null}}};}
function n(value:unknown){return Number(value??0);}
function admin(user:SessionUser){return user.roleCodes.some((code)=>code==='admin'||code==='system_admin');}
function scope(sql:any,user:SessionUser){if(admin(user))return sql``;if(!user.branchCodes.length)return sql`and false`;return sql`and b.code in ${sql(user.branchCodes)}`;}

export async function getDashboardData(user:SessionUser):Promise<DashboardData>{
  let sql:any;try{sql=getSql();await sql`select 1`;}catch{return emptyData(false);}
  const result=emptyData(true);const branchFilter=scope(sql,user);
  try{
    const [row]=await sql<any[]>`select (select count(*) from crm.leads where is_deleted=false)::int as total_customers,(select count(*) from crm.conversations where status='open')::int as open_conversations,(select count(*) from crm.leads where status_label='محتمل' and is_deleted=false)::int as potential_customers,(select count(*) from crm.leads where status_label in ('تم البيع','تم الانتهاء - إنشاء طلب البيع','تم الإنتهاء - إنشاء طلب البيع') and is_deleted=false)::int as sold,(select count(*) from crm.leads where department_code='cash_sales' and is_deleted=false)::int as cash_sales,(select count(*) from crm.leads where department_code='finance_sales' and is_deleted=false)::int as finance_sales,(select count(*) from crm.leads where department_code='customer_service' and is_deleted=false)::int as customer_service,(select count(*) from crm.leads where created_at::date=current_date and is_deleted=false)::int as new_today,(select count(*) from crm.leads where created_at>=date_trunc('week',now()) and is_deleted=false)::int as new_this_week`;
    result.crm={...result.crm,totalCustomers:n(row?.total_customers),openConversations:n(row?.open_conversations),potentialCustomers:n(row?.potential_customers),sold:n(row?.sold),cashSales:n(row?.cash_sales),financeSales:n(row?.finance_sales),customerService:n(row?.customer_service),newToday:n(row?.new_today),newThisWeek:n(row?.new_this_week)};
    const recent=await sql<any[]>`select c.id::text,coalesce(c.customer_name,l.customer_name,'عميل') as customer_name,coalesce(c.preview_text,'') as preview_text,c.last_message_at,coalesce(c.unread_count,0)::int as unread_count,coalesce(c.lead_id::text,'') as lead_id,coalesce(l.department_code,'') as department_code from crm.conversations c left join crm.leads l on l.id=c.lead_id and l.is_deleted=false order by c.last_message_at desc nulls last limit 5`;
    const series=await sql<any[]>`select to_char(day,'DD/MM') as label,count(l.id)::int as value from generate_series(current_date-interval '6 days',current_date,interval '1 day') day left join crm.leads l on l.created_at::date=day::date and l.is_deleted=false group by day order by day`;
    result.crm.recentConversations=recent.map((r:any)=>({id:r.id,customerName:r.customer_name,preview:r.preview_text,time:r.last_message_at?new Date(r.last_message_at).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'}):'',unreadCount:n(r.unread_count),leadId:r.lead_id,department:r.department_code==='finance_sales'||r.department_code==='call_center'?'finance':r.department_code==='customer_service'?'service':'cash'}));
    result.crm.newCustomersSeries=series.map((r:any)=>({label:r.label,value:n(r.value)}));
  }catch(error){console.error('Dashboard CRM section failed',error);}
  try{const [row]=await sql<any[]>`select count(*)::int as campaigns,count(*) filter(where status='scheduled')::int as scheduled,count(*) filter(where due_at<now() and status not in ('completed','archived'))::int as delayed from marketing.campaigns where is_deleted=false`;result.marketing={campaigns:n(row?.campaigns),scheduled:n(row?.scheduled),delayed:n(row?.delayed)};}catch(error){console.error('Dashboard marketing section failed',error);}
  try{const [row]=await sql<any[]>`select count(*) filter(where coalesce(is_archived,false)=false)::int as requests,count(*) filter(where coalesce(is_archived,false)=false and status='in_progress')::int as in_progress,count(*) filter(where coalesce(is_archived,false)=true or status='completed')::int as completed from tracking.orders where coalesce(is_deleted,false)=false`;result.tracking={requests:n(row?.requests),inProgress:n(row?.in_progress),completed:n(row?.completed)};result.operations.salesTracking={total:n(row?.requests),notStarted:0,inProgress:n(row?.in_progress),completed:n(row?.completed)};const [notStarted]=await sql<any[]>`select count(*)::int as count from tracking.orders where coalesce(is_deleted,false)=false and coalesce(is_archived,false)=false and status='not_started'`;result.operations.salesTracking.notStarted=n(notStarted?.count);}catch(error){console.error('Dashboard tracking section failed',error);}
  try{
    const [inventory]=await sql<any[]>`select count(*) filter(where s.counts_in_actual_inventory=true)::int as actual_total,count(*) filter(where l.code='agency')::int as agency,count(*) filter(where v.status_code='available_for_sale')::int as available_for_sale,count(*) filter(where v.status_code='under_delivery')::int as under_delivery,count(*) filter(where v.status_code='has_notes')::int as has_notes from operations.vehicles v left join operations.locations l on l.id=v.location_id left join operations.vehicle_statuses s on s.code=v.status_code left join core.branches b on b.id=v.branch_id where v.is_deleted=false and v.archived_at is null ${branchFilter}`;
    result.operations.inventory={actualTotal:n(inventory?.actual_total),agency:n(inventory?.agency),availableForSale:n(inventory?.available_for_sale),underDelivery:n(inventory?.under_delivery),hasNotes:n(inventory?.has_notes)};
    const locations=await sql<any[]>`select l.code as key,l.name,count(v.id) filter(where s.counts_in_actual_inventory=true and v.is_deleted=false and v.archived_at is null)::int as actual_total,count(v.id) filter(where v.status_code='under_delivery' and v.is_deleted=false and v.archived_at is null)::int as under_delivery,count(v.id) filter(where v.status_code='available_for_sale' and v.is_deleted=false and v.archived_at is null)::int as available_for_sale,count(v.id) filter(where v.status_code='reserved' and v.is_deleted=false and v.archived_at is null)::int as reserved,count(v.id) filter(where v.status_code='delivered' and v.is_deleted=false and v.archived_at is null)::int as delivered,count(v.id) filter(where v.status_code='has_notes' and v.is_deleted=false and v.archived_at is null)::int as has_notes from operations.locations l left join operations.vehicles v on v.location_id=l.id left join operations.vehicle_statuses s on s.code=v.status_code left join core.branches b on b.id=v.branch_id where l.is_active=true ${branchFilter} group by l.code,l.name,l.sort_order order by l.sort_order`;
    result.operations.locations=result.operations.locations.map((base)=>{const found=locations.find((item:any)=>item.key===base.key);return found?{key:found.key,name:found.name,actualTotal:n(found.actual_total),underDelivery:n(found.under_delivery),availableForSale:n(found.available_for_sale),reserved:n(found.reserved),delivered:n(found.delivered),hasNotes:n(found.has_notes)}:base;});
    const [approvals]=await sql<any[]>`select count(*)::int as total,count(*) filter(where a.financial_approved=false)::int as missing_financial,count(*) filter(where a.administrative_approved=false)::int as missing_administrative,count(*) filter(where a.financial_approved=true and a.administrative_approved=true)::int as completed from operations.vehicle_approvals a join operations.vehicles v on v.id=a.vehicle_id left join core.branches b on b.id=v.branch_id where a.is_current=true and v.status_code='under_delivery' and v.is_deleted=false and v.archived_at is null ${branchFilter}`;
    result.operations.approvals={total:n(approvals?.total),missingFinancial:n(approvals?.missing_financial),missingAdministrative:n(approvals?.missing_administrative),completed:n(approvals?.completed)};
    const [shortages]=await sql<any[]>`select count(*) filter(where sh.is_resolved=false)::int as total,count(*) filter(where sh.is_resolved=false and l.code='multaqa')::int as multaqa,count(*) filter(where sh.is_resolved=false and l.code='hall')::int as hall,count(*) filter(where sh.is_resolved=false and l.code='qadisiyah')::int as qadisiyah from operations.vehicle_shortages sh join operations.vehicles v on v.id=sh.vehicle_id left join operations.locations l on l.id=v.location_id left join core.branches b on b.id=v.branch_id where v.is_deleted=false ${branchFilter}`;
    result.operations.shortages={total:n(shortages?.total),multaqa:n(shortages?.multaqa),hall:n(shortages?.hall),qadisiyah:n(shortages?.qadisiyah)};
    const [transfers]=await sql<any[]>`select count(distinct r.id)::int as total,count(distinct r.id) filter(where r.current_stage='request_received')::int as request_received,count(distinct r.id) filter(where r.current_stage='vehicle_sent')::int as vehicle_sent,count(distinct r.id) filter(where r.current_stage='vehicle_received')::int as vehicle_received,count(distinct r.id) filter(where r.current_stage='completed')::int as completed from operations.transfer_requests r left join operations.transfer_request_vehicles rv on rv.transfer_request_id=r.id left join operations.vehicles v on v.id=rv.vehicle_id left join core.branches b on b.id=v.branch_id where r.deleted_at is null and r.request_type='transfer' ${branchFilter}`;
    result.operations.transfers={total:n(transfers?.total),requestReceived:n(transfers?.request_received),vehicleSent:n(transfers?.vehicle_sent),vehicleReceived:n(transfers?.vehicle_received),completed:n(transfers?.completed)};
  }catch(error){console.error('Dashboard operations section failed',error);}
  return result;
}
