import { getSql } from "./_db.js";
import { ensureOperationsSchema } from "./_operations-schema.js";
import type { DashboardData } from "../src/types.js";

const locationNames=[["warehouse","المستودع"],["agency","الوكالة"],["hall","الصالة"],["qadisiyah","القادسية"],["multaqa","الملتقى"]] as const;
function emptyData():DashboardData{return{connected:false,generatedAt:new Date().toISOString(),crm:{totalCustomers:null,openConversations:null,potentialCustomers:null,sold:null,cashSales:null,financeSales:null,customerService:null,newToday:null,newThisWeek:null,recentConversations:[],newCustomersSeries:[]},marketing:{campaigns:null,scheduled:null,delayed:null},tracking:{requests:null,inProgress:null,completed:null},operations:{inventory:{actualTotal:null,agency:null,availableForSale:null,underDelivery:null,hasNotes:null},locations:locationNames.map(([key,name])=>({key,name,actualTotal:null,underDelivery:null,availableForSale:null,reserved:null,delivered:null,hasNotes:null})),approvals:{total:null,missingFinancial:null,missingAdministrative:null,completed:null},shortages:{total:null,multaqa:null,hall:null,qadisiyah:null},transfers:{total:null,requestReceived:null,vehicleReceived:null,vehicleSent:null,completed:null},salesTracking:{total:null,notStarted:null,inProgress:null,completed:null}},errors:{}}}
const n=(v:unknown)=>Number(v??0);
export async function getDashboardData():Promise<DashboardData>{
 const data=emptyData();let sql;try{sql=getSql();await sql`select 1`;data.connected=true}catch{return data}
 const errors:Record<string,string>={};const safe=async(key:string,fn:()=>Promise<any>,apply:(value:any)=>void)=>{try{apply(await fn())}catch(error){const id=`dashboard-${key}-${Date.now().toString(36)}`;errors[key]=id;console.error("Dashboard section failed",{key,id,error})}};
 await safe('crm.metrics',async()=>{const [r]=await sql<any[]>`select (select count(*) from crm.leads where is_deleted=false)::int total_customers,(select count(*) from crm.conversations where status='open')::int open_conversations,(select count(*) from crm.leads where status_label='محتمل' and is_deleted=false)::int potential_customers,(select count(*) from crm.leads where status_label in('تم البيع','تم الانتهاء - إنشاء طلب البيع','تم الإنتهاء - إنشاء طلب البيع') and is_deleted=false)::int sold,(select count(*) from crm.leads where department_code='cash_sales' and is_deleted=false)::int cash_sales,(select count(*) from crm.leads where department_code='finance_sales' and is_deleted=false)::int finance_sales,(select count(*) from crm.leads where department_code='customer_service' and is_deleted=false)::int customer_service,(select count(*) from crm.leads where created_at::date=current_date and is_deleted=false)::int new_today,(select count(*) from crm.leads where created_at>=date_trunc('week',now()) and is_deleted=false)::int new_this_week`;return r},r=>Object.assign(data.crm,{totalCustomers:n(r.total_customers),openConversations:n(r.open_conversations),potentialCustomers:n(r.potential_customers),sold:n(r.sold),cashSales:n(r.cash_sales),financeSales:n(r.finance_sales),customerService:n(r.customer_service),newToday:n(r.new_today),newThisWeek:n(r.new_this_week)}));
 await safe('crm.recent',()=>sql<any[]>`select c.id::text,coalesce(c.customer_name,l.customer_name,'عميل') customer_name,coalesce(c.preview_text,'') preview_text,c.last_message_at,coalesce(c.unread_count,0)::int unread_count,coalesce(c.lead_id::text,'') lead_id,coalesce(l.department_code,'') department_code from crm.conversations c left join crm.leads l on l.id=c.lead_id and l.is_deleted=false order by c.last_message_at desc nulls last limit 5`,rows=>data.crm.recentConversations=rows.map(r=>({id:r.id,customerName:r.customer_name,preview:r.preview_text,time:r.last_message_at?new Date(r.last_message_at).toISOString():'',unreadCount:n(r.unread_count),leadId:r.lead_id,department:r.department_code==='finance_sales'?'finance':r.department_code==='customer_service'?'service':'cash'})));
 await safe('crm.series',()=>sql<any[]>`select to_char(day,'DD/MM') label,count(l.id)::int value from generate_series(current_date-interval '6 days',current_date,interval '1 day') day left join crm.leads l on l.created_at::date=day::date and l.is_deleted=false group by day order by day`,rows=>data.crm.newCustomersSeries=rows.map(r=>({label:r.label,value:n(r.value)})));
 await safe('marketing',async()=>{const [r]=await sql<any[]>`select count(*)::int campaigns,count(*) filter(where status='scheduled')::int scheduled,count(*) filter(where due_at<now() and status not in('completed','archived'))::int delayed from marketing.campaigns where is_deleted=false`;return r},r=>data.marketing={campaigns:n(r.campaigns),scheduled:n(r.scheduled),delayed:n(r.delayed)});
 await safe('tracking',async()=>{const [r]=await sql<any[]>`select count(*) filter(where coalesce(is_archived,false)=false)::int requests,count(*) filter(where coalesce(is_archived,false)=false and status='in_progress')::int in_progress,count(*) filter(where coalesce(is_archived,false)=true or status='completed')::int completed from tracking.orders`;return r},r=>{data.tracking={requests:n(r.requests),inProgress:n(r.in_progress),completed:n(r.completed)};data.operations.salesTracking={total:n(r.requests)+n(r.completed),notStarted:0,inProgress:n(r.in_progress),completed:n(r.completed)}});
 await safe('operations.schema',()=>ensureOperationsSchema(),()=>undefined);
 await safe('operations.inventory',async()=>{const [r]=await sql<any[]>`select count(*) filter(where archived_at is null and status_code not in('under_delivery','delivered'))::int actual_total,count(*) filter(where archived_at is null and status_code='available_for_sale')::int available,count(*) filter(where archived_at is null and status_code='under_delivery')::int under_delivery,count(*) filter(where archived_at is null and status_code='has_notes')::int has_notes,count(*) filter(where archived_at is null and location_id=(select id from operations.locations where code='agency' limit 1))::int agency from operations.vehicles where is_deleted=false`;return r},r=>data.operations.inventory={actualTotal:n(r.actual_total),agency:n(r.agency),availableForSale:n(r.available),underDelivery:n(r.under_delivery),hasNotes:n(r.has_notes)});
 await safe('operations.locations',()=>sql<any[]>`select l.code,l.name,count(v.id) filter(where v.archived_at is null and v.status_code not in('under_delivery','delivered'))::int actual_total,count(v.id) filter(where v.archived_at is null and v.status_code='under_delivery')::int under_delivery,count(v.id) filter(where v.archived_at is null and v.status_code='available_for_sale')::int available,count(v.id) filter(where v.archived_at is null and v.status_code='reserved')::int reserved,count(v.id) filter(where v.archived_at is null and v.status_code='delivered')::int delivered,count(v.id) filter(where v.archived_at is null and v.status_code='has_notes')::int has_notes from operations.locations l left join operations.vehicles v on v.location_id=l.id and v.is_deleted=false where l.is_active=true group by l.id order by l.sort_order`,rows=>data.operations.locations=rows.map(r=>({key:r.code,name:r.name,actualTotal:n(r.actual_total),underDelivery:n(r.under_delivery),availableForSale:n(r.available),reserved:n(r.reserved),delivered:n(r.delivered),hasNotes:n(r.has_notes)})));
 await safe('operations.approvals',async()=>{const [r]=await sql<any[]>`select count(*)::int total,count(*) filter(where coalesce(c.financial_approved,false)=false)::int missing_financial,count(*) filter(where coalesce(c.administrative_approved,false)=false)::int missing_administrative,count(*) filter(where c.financial_approved=true and c.administrative_approved=true)::int completed from operations.vehicles v left join operations.vehicle_approval_cycles c on c.vehicle_id=v.id and c.is_active=true where v.is_deleted=false and v.archived_at is null and v.status_code='under_delivery'`;return r},r=>data.operations.approvals={total:n(r.total),missingFinancial:n(r.missing_financial),missingAdministrative:n(r.missing_administrative),completed:n(r.completed)});
 await safe('operations.shortages',async()=>{const [r]=await sql<any[]>`select count(*) filter(where s.is_resolved=false)::int total,count(*) filter(where s.is_resolved=false and l.code='multaqa')::int multaqa,count(*) filter(where s.is_resolved=false and l.code='hall')::int hall,count(*) filter(where s.is_resolved=false and l.code='qadisiyah')::int qadisiyah from operations.vehicle_shortages s join operations.vehicles v on v.id=s.vehicle_id left join operations.locations l on l.id=v.location_id where v.is_deleted=false`;return r},r=>data.operations.shortages={total:n(r.total),multaqa:n(r.multaqa),hall:n(r.hall),qadisiyah:n(r.qadisiyah)});
 await safe('operations.transfers',async()=>{const [r]=await sql<any[]>`select count(*) filter(where deleted_at is null)::int total,count(*) filter(where deleted_at is null and status='request_received')::int request_received,count(*) filter(where deleted_at is null and status='vehicle_received')::int vehicle_received,count(*) filter(where deleted_at is null and status='vehicle_sent')::int vehicle_sent,count(*) filter(where deleted_at is null and status='completed')::int completed from operations.transfer_requests`;return r},r=>data.operations.transfers={total:n(r.total),requestReceived:n(r.request_received),vehicleReceived:n(r.vehicle_received),vehicleSent:n(r.vehicle_sent),completed:n(r.completed)});
 data.errors=errors;return data;
}
