import type { DataScope, PlatformSystem } from "../../shared/access-control";

export type SystemItem = { code: PlatformSystem; name_ar: string; sort_order: number; is_active: boolean };
export type PageItem = { id: string; system_code: string; code: string; name_ar: string; route: string; sort_order: number; is_active: boolean };
export type PermissionItem = { id: string; code: string; system_code: string; page_code: string; action_code: string; name_ar: string; description_ar: string; category: string; is_sensitive: boolean; sort_order: number };
export type RoleItem = { id: string; code: string; name: string; description_ar: string | null; is_system: boolean; is_active: boolean; permission_codes: string[]; users_count: number };
export type OrgItem = { id: string; code: string; name: string; system_code?: string; is_active: boolean; sort_order?: number };
export type BootstrapResponse = { ok: true; systems: SystemItem[]; pages: PageItem[]; permissions: PermissionItem[]; roles: RoleItem[]; branches: OrgItem[]; departments: OrgItem[]; dataScopes: Array<{ code: DataScope; name: string }> };
export type UserListItem = { id: string; employee_no: string | null; full_name: string; email: string | null; mobile: string | null; next_erp_user_id: string | null; is_active: boolean; can_receive_leads: boolean; can_receive_tasks: boolean; roles: string; branches: string; departments: string; role_ids: string[]; branch_ids: string[]; department_ids: string[]; systems: Record<string, { enabled: boolean; dataScope: DataScope; roleId: string | null }>; last_access_change_at: string | null; last_access_changed_by: string | null };
export type UserSystemDetail = { system_code: PlatformSystem; is_enabled: boolean; role_id: string | null; data_scope: DataScope; branch_ids: string[]; department_ids: string[]; primary_branch_id: string | null; primary_department_id: string | null };
export type UserDetailResponse = { ok: true; user: { id: string; employee_no: string | null; full_name: string; email: string | null; mobile: string | null; next_erp_user_id: string | null; is_active: boolean; can_receive_leads: boolean; can_receive_tasks: boolean }; roleIds: string[]; systems: UserSystemDetail[]; overrides: Array<{ permission_code: string; effect: "allow" | "deny"; reason: string | null }>; effective: { inheritedPermissions: string[]; directPermissions: string[]; deniedPermissions: string[]; permissions: string[] } };
