begin;
drop table if exists crm.conversation_automation_final_actions cascade;
drop table if exists crm.conversation_automation_outbound_messages cascade;
drop table if exists crm.conversation_automation_answers cascade;
drop table if exists crm.conversation_automation_inbound_events cascade;
drop table if exists crm.conversation_automation_sessions cascade;
drop table if exists crm.conversation_automation_flow_steps cascade;
drop table if exists crm.conversation_automation_flow_aliases cascade;
drop table if exists crm.conversation_automation_flows cascade;
drop table if exists crm.conversation_automation_start_messages cascade;
drop table if exists crm.conversation_automation_platforms cascade;
drop table if exists crm.conversation_automation_settings cascade;
delete from core.schema_migrations where version='crm-conversation-automation-v1.18.1';
commit;
