drop table if exists crm.automation_final_actions cascade;
drop table if exists crm.automation_outbound_messages cascade;
drop table if exists crm.automation_answers cascade;
drop table if exists crm.automation_inbound_events cascade;
drop table if exists crm.automation_sessions cascade;
drop table if exists crm.automation_flow_steps cascade;
drop table if exists crm.automation_flow_aliases cascade;
drop table if exists crm.automation_flows cascade;
drop table if exists crm.automation_start_messages cascade;
drop table if exists crm.automation_platforms cascade;
alter table crm.automation_settings drop column if exists automation_name;
alter table crm.automation_settings drop column if exists automation_enabled;
alter table crm.automation_settings drop column if exists trigger_policy;
alter table crm.automation_settings drop column if exists custom_interval_value;
alter table crm.automation_settings drop column if exists custom_interval_unit;
delete from core.schema_migrations where version='crm-conversation-automation-v1.18.0';
