import { useEffect, useMemo, useState } from "react";
import { CalendarBlank, CaretLeft, CaretRight } from "@phosphor-icons/react";
import { formatDate, marketingFetch } from "../api";
import type { DashboardResponse, DashboardTask } from "../types";
import { Alert, Empty, PageHead, StatusBadge } from "../components/Ui";

function isoDay(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function monthCells(month: Date) { const first = new Date(month.getFullYear(), month.getMonth(), 1); const start = new Date(first); start.setDate(first.getDate() - first.getDay()); return Array.from({ length: 42 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date; }); }
export function MarketingCalendarPage() {
  const [data, setData] = useState<DashboardResponse | null>(null); const [month, setMonth] = useState(() => new Date()); const [error, setError] = useState("");
  useEffect(() => { marketingFetch<DashboardResponse>("/api/marketing?resource=dashboard").then(setData).catch((failure) => setError(failure instanceof Error ? failure.message : "تعذر تحميل التقويم")); }, []);
  const received = useMemo(() => (data?.tasks || []).filter((task) => task.actual_received_at), [data]); const cells = monthCells(month); const monthTitle = new Intl.DateTimeFormat("ar-SA", { month: "long", year: "numeric" }).format(month);
  function tasksFor(date: Date): DashboardTask[] { const key = isoDay(date); return received.filter((task) => String(task.actual_received_at).slice(0, 10) === key); }
  return <div className="marketing-page"><PageHead title="التقويم" description="التاسكات تظهر حسب تاريخ الاستلام الفعلي المسجل عند الضغط على تم الاستلام." />{error ? <Alert type="error">{error}</Alert> : null}<section className="marketing-calendar-card"><header><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}><CaretRight size={20} /></button><h2><CalendarBlank size={22} />{monthTitle}</h2><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}><CaretLeft size={20} /></button></header><div className="marketing-calendar-week"><span>الأحد</span><span>الاثنين</span><span>الثلاثاء</span><span>الأربعاء</span><span>الخميس</span><span>الجمعة</span><span>السبت</span></div><div className="marketing-calendar-grid">{cells.map((date) => { const tasks = tasksFor(date); const currentMonth = date.getMonth() === month.getMonth(); const today = isoDay(date) === isoDay(new Date()); return <article key={date.toISOString()} className={`${currentMonth ? "" : "outside"} ${today ? "today" : ""}`}><header><b>{date.getDate()}</b>{today ? <span>اليوم</span> : null}</header><div>{tasks.map((task) => <section key={task.id}><StatusBadge status={task.source_kind === "agenda" ? "agenda" : "campaign"} /><b>{task.assigned_to_name}</b><span>{task.instance_code} - {task.creative_name}</span><small>{task.campaign_name}</small><em>تاريخ الاستلام {formatDate(task.actual_received_at, true)}</em></section>)}</div></article>; })}</div></section>{!received.length ? <Empty text="لا توجد تاسكات تم استلامها حتى الآن." /> : null}</div>;
}
