import { useEffect, useMemo, useState } from "react";
import { CaretLeft, CaretRight } from "@phosphor-icons/react";
import { marketingFetch, queryString } from "../api";
import { MarketingAlert, MarketingLoading, MarketingModal, MarketingPageHeader, StatusBadge } from "../components/Ui";
import { MonthCalendar, type CalendarEntry } from "../components/MonthCalendar";

type Row = { schedule_id?: string; prep_id?: string; publish_date: string; campaign_code: string; campaign_name: string; source_type: string; creative_name: string; instance_code: string; platform_name: string; post_type_name: string; publish_time?: string; status: string; source: string; caption?: string; hashtags?: string; published_url?: string; error_message?: string };
function monthShift(month: string, amount: number) { const [year, monthNo] = month.split("-").map(Number); const date = new Date(year, monthNo - 1 + amount, 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; }
function monthLabel(month: string) { return new Intl.DateTimeFormat("ar-SA", { month: "long", year: "numeric" }).format(new Date(`${month}-01T12:00:00`)); }

export function CalendarPage() {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [rows, setRows] = useState<Row[]>([]);
  const [selected, setSelected] = useState<CalendarEntry | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const payload = await marketingFetch<{ rows: Row[] }>(`/api/marketing?${queryString({ resource: "calendar", month })}`); setRows(payload.rows); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل تقويم النشر"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [month]);
  const entries = useMemo<CalendarEntry[]>(() => rows.map((row, index) => ({ id: row.prep_id || row.schedule_id || `${index}`, date: row.publish_date, title: `${row.campaign_code} · ${row.creative_name}`, subtitle: `${row.platform_name} · ${row.post_type_name}${row.publish_time ? ` · ${String(row.publish_time).slice(0, 5)}` : ""}`, status: row.status, raw: row })), [rows]);
  const details = selected?.raw as Row | undefined;
  return <div className="marketing-page"><MarketingPageHeader title="تقويم النشر" description="التقويم الموحد لجدول الحملات والأجندات، مع استبدال المواعيد المعدلة في تجهيز النشر بدون تكرار." />{error ? <MarketingAlert>{error}</MarketingAlert> : null}<section className="marketing-panel"><div className="marketing-calendar-toolbar"><button className="marketing-button" onClick={() => setMonth(monthShift(month, -1))}><CaretRight />السابق</button><div><strong>{monthLabel(month)}</strong><button className="marketing-button small secondary" style={{ marginRight: 10 }} onClick={() => setMonth(new Date().toISOString().slice(0, 7))}>اليوم</button></div><button className="marketing-button" onClick={() => setMonth(monthShift(month, 1))}>التالي<CaretLeft /></button></div></section>{loading ? <MarketingLoading /> : <MonthCalendar month={month} entries={entries} onEntry={setSelected} />}<MarketingModal open={Boolean(selected)} title={details ? `${details.campaign_code} — ${details.campaign_name}` : "تفاصيل النشر"} subtitle={details ? `${details.instance_code} · ${details.creative_name}` : undefined} onClose={() => setSelected(null)}>{details ? <div className="marketing-stack"><div className="marketing-review-kv"><div><small>التاريخ</small><strong>{String(details.publish_date).slice(0, 10)}</strong></div><div><small>الوقت</small><strong>{details.publish_time ? String(details.publish_time).slice(0, 5) : "—"}</strong></div><div><small>المنصة</small><strong>{details.platform_name}</strong></div><div><small>نوع النشر</small><strong>{details.post_type_name}</strong></div><div><small>المصدر</small><strong>{details.source === "publish_prep" ? "تجهيز النشر" : "جدول الحملة"}</strong></div><div><small>الحالة</small><StatusBadge status={details.status} type="publish" /></div></div>{details.caption ? <div className="marketing-panel"><strong>Caption</strong><p>{details.caption}</p></div> : null}{details.hashtags ? <div className="marketing-panel"><strong>Hashtags</strong><p>{details.hashtags}</p></div> : null}{details.published_url ? <a href={details.published_url} target="_blank" rel="noreferrer">فتح رابط النشر</a> : null}{details.error_message ? <MarketingAlert>{details.error_message}</MarketingAlert> : null}</div> : null}</MarketingModal></div>;
}
