import { useCallback, useEffect, useState } from "react";
import { Eye, MagnifyingGlass } from "@phosphor-icons/react";
import { useOutletContext } from "react-router-dom";
import { formatDate, marketingFetch, marketingQuery } from "../api";
import type { CampaignDetailResponse, CampaignRow } from "../types";
import type { MarketingOutletContext } from "../MarketingLayout";
import { CampaignDetailView } from "../components/CampaignDetailView";
import { Alert, Empty, Modal, PageHead, ProgressBar, StatusBadge } from "../components/Ui";

type Response = { ok: boolean; rows: CampaignRow[] };
export function CampaignManagementPage() {
  const { meta } = useOutletContext<MarketingOutletContext>(); const [rows, setRows] = useState<CampaignRow[]>([]); const [search, setSearch] = useState(""); const [error, setError] = useState(""); const [detail, setDetail] = useState<CampaignDetailResponse | null>(null); const [selected, setSelected] = useState("");
  const load = useCallback(async () => { try { const data = await marketingFetch<Response>(`/api/marketing${marketingQuery({ resource: "campaigns", kind: "campaign", search, pageSize: 500 })}`); setRows(data.rows); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل الحملات"); } }, [search]); useEffect(() => { void load(); }, [load]);
  async function open(id: string) { setSelected(id); setDetail(null); try { setDetail(await marketingFetch<CampaignDetailResponse>(`/api/marketing${marketingQuery({ resource: "campaign", id })}`)); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل الحملة"); } }
  return <div className="marketing-page"><PageHead title="إدارة الحملات" description="عرض كل حملة بنفس تفاصيل شاشة قاعدة البيانات وإجراءاتها الإدارية." />{error ? <Alert type="error">{error}</Alert> : null}<section className="marketing-filter-bar"><label><MagnifyingGlass size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="بحث باسم أو كود الحملة" /></label></section><div className="marketing-campaign-management-grid">{rows.map((row) => <article key={row.id}><header><div><strong>{row.name}</strong><small>{row.campaign_code}</small></div><StatusBadge status={row.workflow_stage} /></header><div className="marketing-detail-grid compact"><div><small>بداية النشر</small><b>{formatDate(row.publish_start_date)}</b></div><div><small>نهاية النشر</small><b>{formatDate(row.publish_end_date)}</b></div><div><small>الكرييتيفات</small><b>{row.instances_count}</b></div><div><small>التاسكات</small><b>{row.tasks_count}</b></div></div><ProgressBar value={row.tasks_count ? (row.completed_tasks_count / row.tasks_count) * 100 : 0} /><button type="button" onClick={() => void open(row.id)}><Eye size={17} />تفاصيل الحملة</button></article>)}</div>{!rows.length ? <Empty text="لا توجد حملات." /> : null}<Modal open={Boolean(selected)} title={detail?.campaign.name || "تفاصيل الحملة"} subtitle={detail?.campaign.campaign_code} onClose={() => { setSelected(""); setDetail(null); }} wide>{detail ? <CampaignDetailView detail={detail} meta={meta} onChanged={async () => { await open(selected); await load(); }} /> : <div className="crm-loading-panel">جاري تحميل التفاصيل...</div>}</Modal></div>;
}
