import { useCallback, useEffect, useState } from "react";
import type { FormEvent } from "react";
import { LinkSimple, PencilSimple, Plus, Trash } from "@phosphor-icons/react";
import { useOutletContext } from "react-router-dom";
import { marketingFetch } from "../api";
import type { PlatformConnection } from "../types";
import type { MarketingOutletContext } from "../MarketingLayout";
import { Alert, ConfirmButton, Empty, PageHead } from "../components/Ui";
type Response = { ok: boolean; rows: PlatformConnection[] };
type Form = { id: string; platformId: string; accountName: string; accountExternalId: string; connectionStatus: string; metadataText: string };
const blank: Form = { id: "", platformId: "", accountName: "", accountExternalId: "", connectionStatus: "disconnected", metadataText: "{}" };
export function MarketingConnectionsPage() {
  const { meta } = useOutletContext<MarketingOutletContext>(); const [rows, setRows] = useState<PlatformConnection[]>([]); const [form, setForm] = useState<Form>(blank); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const data = await marketingFetch<Response>("/api/marketing?resource=connections"); setRows(data.rows); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل ربط المنصات"); } }, []); useEffect(() => { void load(); }, [load]);
  async function save(event: FormEvent) { event.preventDefault(); try { let metadata: Record<string, unknown> = {}; try { metadata = JSON.parse(form.metadataText) as Record<string, unknown>; } catch { throw new Error("بيانات الربط الإضافية يجب أن تكون JSON صحيحة"); } await marketingFetch("/api/marketing", { method: "POST", body: JSON.stringify({ action: "save_connection", ...form, metadata }) }); setMessage("تم حفظ ربط المنصة"); setForm(blank); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر حفظ الربط"); } }
  async function remove(id: string) { try { await marketingFetch("/api/marketing", { method: "POST", body: JSON.stringify({ action: "delete_connection", id }) }); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر حذف الربط"); } }
  function edit(row: PlatformConnection) { setForm({ id: row.id, platformId: row.platform_id, accountName: row.account_name || "", accountExternalId: row.account_external_id || "", connectionStatus: row.connection_status, metadataText: JSON.stringify(row.metadata || {}, null, 2) }); }
  return <div className="marketing-page"><PageHead title="ربط المنصات" description="إدارة حسابات وربط منصات التسويق من إعدادات المنصة الموحدة." />{error ? <Alert type="error">{error}</Alert> : null}{message ? <Alert type="success">{message}</Alert> : null}<div className="marketing-connections-layout"><section><h2>المنصات المرتبطة</h2><div className="marketing-connections-grid">{rows.map((row) => <article key={row.id}><header><LinkSimple size={24} /><div><strong>{row.platform_name}</strong><small>{row.platform_code}</small></div><span className={row.connection_status === "connected" ? "connected" : "disconnected"}>{row.connection_status === "connected" ? "متصل" : "غير متصل"}</span></header><p>{row.account_name || "بدون اسم حساب"}</p><small>{row.account_external_id || "—"}</small><footer><button type="button" onClick={() => edit(row)}><PencilSimple size={16} />تعديل</button><button type="button" className="danger" onClick={() => void remove(row.id)}><Trash size={16} />حذف</button></footer></article>)}</div>{!rows.length ? <Empty text="لا توجد منصات مرتبطة." /> : null}</section><aside className="marketing-form-card"><h2>{form.id ? "تعديل الربط" : "إضافة ربط منصة"}</h2><form onSubmit={save}><label><span>المنصة</span><select required value={form.platformId} onChange={(event) => setForm({ ...form, platformId: event.target.value })}><option value="">اختر المنصة</option>{meta.platforms.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>اسم الحساب</span><input value={form.accountName} onChange={(event) => setForm({ ...form, accountName: event.target.value })} /></label><label><span>معرف الحساب الخارجي</span><input value={form.accountExternalId} onChange={(event) => setForm({ ...form, accountExternalId: event.target.value })} /></label><label><span>حالة الربط</span><select value={form.connectionStatus} onChange={(event) => setForm({ ...form, connectionStatus: event.target.value })}><option value="disconnected">غير متصل</option><option value="connected">متصل</option><option value="error">خطأ</option></select></label><label><span>بيانات الربط الإضافية JSON</span><textarea rows={8} dir="ltr" value={form.metadataText} onChange={(event) => setForm({ ...form, metadataText: event.target.value })} /></label><div className="marketing-row-actions"><ConfirmButton type="submit"><Plus size={17} />حفظ الربط</ConfirmButton>{form.id ? <ConfirmButton tone="secondary" onClick={() => setForm(blank)}>إلغاء</ConfirmButton> : null}</div></form></aside></div></div>;
}
