import { useEffect, useMemo, useState } from "react";
import { getJSZip } from "../zip";
import { CalendarPlus, CheckCircle, FolderOpen, PencilSimple, Plus } from "@phosphor-icons/react";
import { marketingFetch, marketingQuery } from "../api";
import { CreativeEditor, newCreativeDraft } from "../components/CreativeEditor";
import { MarketingAlert, MarketingPage } from "../components/MarketingPage";
import { relationshipCsv } from "../templateExcel";
import type { CreativeDraft, MarketingMeta } from "../types";

const emptyMeta: MarketingMeta = { ok: true, users: [], departments: [], actions: [], creativeTypes: [], campaignTypes: [], platforms: [], postTypes: [], funnels: [], cars: [], connections: [], permissions: { isAdmin: false, canManage: false } };
type AgendaDay = { date: string; creatives: CreativeDraft[] };
function between(start: string, end: string) { const result:string[]=[]; if(!start||!end)return result; const current=new Date(`${start}T00:00:00Z`),last=new Date(`${end}T00:00:00Z`); while(current<=last&&result.length<370){result.push(current.toISOString().slice(0,10));current.setUTCDate(current.getUTCDate()+1);} return result; }

export function CreateAgendaPage() {
  const [meta, setMeta] = useState<MarketingMeta>(emptyMeta);
  const [step, setStep] = useState(0);
  const [form, setForm] = useState({ monthKey: new Date().toISOString().slice(0,7), name: "", publishStart: "", publishEnd: "" });
  const [days, setDays] = useState<AgendaDay[]>([]);
  const [editingDay, setEditingDay] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  useEffect(()=>{marketingFetch<MarketingMeta>(`/api/marketing${marketingQuery({resource:"meta"})}`).then(setMeta).catch((failure)=>setError(failure instanceof Error?failure.message:"تعذر تحميل الإعدادات"));},[]);
  function prepareDays(){if(!form.name||!form.publishStart||!form.publishEnd){setError("أكمل بيانات الأجندة");return;}setDays((current)=>between(form.publishStart,form.publishEnd).map((date)=>current.find((item)=>item.date===date)||{date,creatives:[]}));setStep(1);setError("");}
  function updateDay(date:string,creatives:CreativeDraft[]){setDays((current)=>current.map((item)=>item.date===date?{...item,creatives}:item));}
  function creativeName(id:string){return meta.creativeTypes.find((item)=>item.id===id)?.name||"—";}
  const relations=useMemo(()=>days.flatMap((day)=>day.creatives.flatMap((creative)=>{const label=creativeName(creative.creativeTypeId);const user=(id:string)=>meta.users.find((item)=>item.id===id)?.full_name||meta.users.find((item)=>item.id===id)?.fullName||id;const rows:Record<string,unknown>[]=[];creative.primaryAssignments.forEach((assignment)=>assignment.contentUserIds.forEach((contentId)=>rows.push({day:day.date,creative:label,department:meta.creativeTypes.find((item)=>item.id===creative.creativeTypeId)?.primary_department_name,user:user(assignment.userId),contentUser:user(contentId),dueOn:assignment.dueOn,note:assignment.note})));creative.optionalAssignments.forEach((group)=>group.assignments.forEach((assignment)=>assignment.contentUserIds.forEach((contentId)=>rows.push({day:day.date,creative:label,department:meta.departments.find((item)=>item.id===group.departmentId)?.name,user:user(assignment.userId),contentUser:user(contentId),dueOn:assignment.dueOn,note:assignment.note}))));return rows;})),[days,meta]);
  const totalCreatives=days.reduce((sum,day)=>sum+day.creatives.reduce((part,item)=>part+item.quantity,0),0);
  const totalTemplates=days.reduce((sum,day)=>sum+day.creatives.reduce((part,item)=>part+item.contentAssignments.length*item.quantity,0),0);
  async function create(){setLoading(true);setError("");try{const result=await marketingFetch<{message:string}>("/api/marketing",{method:"POST",body:JSON.stringify({action:"create_agenda",...form,days})});setMessage(result.message);setStep(0);setForm({monthKey:new Date().toISOString().slice(0,7),name:"",publishStart:"",publishEnd:""});setDays([]);}catch(failure){setError(failure instanceof Error?failure.message:"تعذر إنشاء الأجندة");}finally{setLoading(false);}}
  async function rawFolders(){setLoading(true);setError("");try{const creatives=days.flatMap((day)=>day.creatives.flatMap((creative,index)=>Array.from({length:creative.quantity},(_,instance)=>({name:creativeName(creative.creativeTypeId),folderName:`${day.date}-${creativeName(creative.creativeTypeId)}-${index+1}-${instance+1}`,creativeInstanceId:creative.tempId,creativeIndex:index+1,cars:creative.cars.map((car)=>({id:car.id,name:`${car.car_name||"سيارة"}-${car.exterior_color||""}-${car.interior_color||""}`})),users:[...creative.primaryAssignments,...creative.optionalAssignments.flatMap((group)=>group.assignments)].map((assignment)=>({uid:assignment.userId,name:meta.users.find((item)=>item.id===assignment.userId)?.full_name||assignment.userId}))}))));const result=await marketingFetch<{message?:string}>("/api/marketing",{method:"POST",body:JSON.stringify({action:"create_raw_folders",payload:{monthKey:form.monthKey,campaignCode:form.monthKey,campaignFolderName:form.name,creatives}})});setMessage(result.message||"تم إنشاء فولدرات الخام");}catch(failure){setError(failure instanceof Error?failure.message:"تعذر إنشاء فولدرات الخام");}finally{setLoading(false);}}
  async function downloadZip(){const JSZip=await getJSZip();const zip=new JSZip();zip.file("agenda-relationships.csv",relationshipCsv(relations));const blob=await zip.generateAsync({type:"blob"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`${form.monthKey||"agenda"}-relationships.zip`;anchor.click();URL.revokeObjectURL(url);}
  const selectedDay=days.find((item)=>item.date===editingDay);
  return <MarketingPage title="إنشاء أجندة" description="إنشاء الأجندة وربط كرييتيفات كل يوم بالأقسام واليوزرات والمنصات.">
    <div className="marketing-wizard-steps three">{["بيانات الأجندة","جدول الأيام والربط","مراجعة وإنشاء الأجندة"].map((label,index)=><button key={label} type="button" className={step===index?"active":index<step?"done":""} onClick={()=>index<=step&&setStep(index)}><span>{index+1}</span><b>{label}</b></button>)}</div>
    {error?<MarketingAlert>{error}</MarketingAlert>:null}{message?<MarketingAlert type="success">{message}</MarketingAlert>:null}
    <section className="panel marketing-wizard-panel">
      {step===0?<div className="marketing-form-grid"><label><span>الشهر</span><input type="month" value={form.monthKey} onChange={(event)=>setForm({...form,monthKey:event.target.value})}/></label><label><span>اسم الأجندة</span><input value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})}/></label><label><span>بداية النشر</span><input type="date" value={form.publishStart} onChange={(event)=>setForm({...form,publishStart:event.target.value})}/></label><label><span>نهاية النشر</span><input type="date" min={form.publishStart} value={form.publishEnd} onChange={(event)=>setForm({...form,publishEnd:event.target.value})}/></label><div className="full marketing-inline-actions"><button type="button" className="primary" onClick={prepareDays}><CalendarPlus size={17}/>التالي</button></div></div>:null}
      {step===1?<div className="marketing-agenda-days"><table><thead><tr><th>اليوم</th><th>الكرييتيفات</th><th>العدد</th><th>إضافة / تعديل الربط</th></tr></thead><tbody>{days.map((day)=><tr key={day.date}><td>{new Date(`${day.date}T00:00:00`).toLocaleDateString("ar-SA",{weekday:"long",year:"numeric",month:"long",day:"numeric"})}</td><td>{day.creatives.length?day.creatives.map((creative)=>creativeName(creative.creativeTypeId)).join("، "):"—"}</td><td>{day.creatives.reduce((sum,item)=>sum+item.quantity,0)}</td><td><button type="button" className="secondary" onClick={()=>setEditingDay(day.date)}><PencilSimple size={16}/>إضافة / تعديل الربط</button></td></tr>)}</tbody></table><div className="marketing-wizard-footer"><span/><button type="button" className="primary" onClick={()=>setStep(2)}>التالي</button></div></div>:null}
      {step===2?<div className="marketing-review"><div className="marketing-review-grid"><article><small>الشهر</small><strong>{form.monthKey}</strong></article><article><small>اسم الأجندة</small><strong>{form.name}</strong></article><article><small>الأيام</small><strong>{days.length}</strong></article><article><small>الأيام المستخدمة</small><strong>{days.filter((day)=>day.creatives.length).length}</strong></article><article><small>الكرييتيفات</small><strong>{totalCreatives}</strong></article><article><small>العلاقات</small><strong>{relations.length}</strong></article><article><small>Task Templates</small><strong>{totalTemplates}</strong></article><article><small>إجمالي التاسكات</small><strong>{totalTemplates+relations.length}</strong></article></div><div className="marketing-review-table"><table><thead><tr><th>اليوم</th><th>الكرييتيف</th><th>العدد</th><th>المنصات وأنواع النشر</th></tr></thead><tbody>{days.flatMap((day)=>day.creatives.map((creative)=><tr key={`${day.date}-${creative.tempId}`}><td>{day.date}</td><td>{creativeName(creative.creativeTypeId)}</td><td>{creative.quantity}</td><td>{creative.platforms.map((platform)=>{const name=meta.platforms.find((item)=>item.id===platform.platformId)?.name;const types=platform.postTypeIds.map((id)=>meta.postTypes.find((item)=>item.id===id)?.name).filter(Boolean).join("، ");return `${name}: ${types}`;}).join(" | ")||"—"}</td></tr>))}</tbody></table></div><div className="marketing-inline-actions"><button type="button" className="secondary" onClick={()=>void rawFolders()} disabled={loading}><FolderOpen size={17}/>إنشاء فولدرات الخام</button><button type="button" className="secondary" onClick={()=>void downloadZip()}>تحميل شيتات العلاقات ZIP</button><button type="button" className="primary" onClick={()=>void create()} disabled={loading}><CheckCircle size={17}/>{loading?"جاري إنشاء الأجندة...":"إنشاء الأجندة"}</button></div></div>:null}
      {step>0?<footer className="marketing-wizard-footer"><button type="button" className="secondary" onClick={()=>setStep((current)=>current-1)}>السابق</button><span/></footer>:null}
    </section>
    {selectedDay?<div className="marketing-day-editor-overlay"><div className="marketing-day-editor"><header><div><h2>{selectedDay.date}</h2><p>إضافة الكرييتيفات وربط الأقسام والمنصات والسيارات لليوم.</p></div><button type="button" onClick={()=>setEditingDay(null)}>×</button></header><div className="marketing-day-editor-body">{selectedDay.creatives.map((creative,index)=><CreativeEditor key={creative.tempId} value={creative} meta={meta} showPlatforms onChange={(value)=>updateDay(selectedDay.date,selectedDay.creatives.map((item,itemIndex)=>itemIndex===index?value:item))} onDelete={()=>updateDay(selectedDay.date,selectedDay.creatives.filter((_,itemIndex)=>itemIndex!==index))}/>)}<button type="button" className="marketing-add-block" onClick={()=>updateDay(selectedDay.date,[...selectedDay.creatives,newCreativeDraft()])}><Plus size={18}/>إضافة الكرييتيف لليوم</button></div><footer><button type="button" className="primary" onClick={()=>setEditingDay(null)}>حفظ والعودة للجدول</button></footer></div></div>:null}
  </MarketingPage>;
}
