import { useCallback, useEffect, useMemo, useState } from "react";
import { Archive, ArrowsClockwise, Eye, FileCsv, MagnifyingGlass, Trash } from "@phosphor-icons/react";
import { useOutletContext } from "react-router-dom";
import { formatDate, marketingFetch, marketingQuery } from "../api";
import type { CampaignDetailResponse, CampaignRow } from "../types";
import type { MarketingOutletContext } from "../MarketingLayout";
import { CampaignDetailView } from "../components/CampaignDetailView";
import { Alert, Empty, Modal, PageHead, StatusBadge } from "../components/Ui";

type ListResponse = { ok: boolean; rows: CampaignRow[]; total: number };
function csv(value: unknown) { return `"${String(value ?? "").replaceAll('"', '""')}"`; }
function download(name: string, text: string) { const blob = new Blob([text], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }

export function MarketingDatabasePage() {
  const { meta } = useOutletContext<MarketingOutletContext>();
  const [rows, setRows] = useState<CampaignRow[]>([]); const [search, setSearch] = useState(""); const [kind, setKind] = useState(""); const [status, setStatus] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [archived, setArchived] = useState(false);
  const [sortKey, setSortKey] = useState<keyof CampaignRow>("created_at"); const [ascending, setAscending] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [selectedId, setSelectedId] = useState(""); const [detail, setDetail] = useState<CampaignDetailResponse | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const data = await marketingFetch<ListResponse>(`/api/marketing${marketingQuery({ resource: "campaigns", search, kind, status, from, to, archived, pageSize: 500 })}`); setRows(data.rows); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل قاعدة البيانات"); } finally { setLoading(false); } }, [archived, from, kind, search, status, to]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => [...rows].sort((a, b) => String(a[sortKey] ?? "").localeCompare(String(b[sortKey] ?? ""), "ar") * (ascending ? 1 : -1)), [ascending, rows, sortKey]);
  async function open(id: string) { setSelectedId(id); setDetail(null); try { setDetail(await marketingFetch<CampaignDetailResponse>(`/api/marketing${marketingQuery({ resource: "campaign", id })}`)); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل التفاصيل"); setSelectedId(""); } }
  async function action(id: string, campaignAction: string) { if (["archive", "restore", "delete"].includes(campaignAction) && !window.confirm(campaignAction === "delete" ? "هل تريد مسح السجل؟" : "هل تريد تنفيذ هذا الإجراء؟")) return; try { await marketingFetch("/api/marketing", { method: "POST", body: JSON.stringify({ action: "campaign_action", campaignAction, campaignId: id }) }); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تنفيذ الإجراء"); } }
  function exportRows() { const data = [["م", "التاريخ", "الكود", "الاسم", "النوع", "الهدف", "بداية النشر", "نهاية النشر", "الحالة"], ...visible.map((row, index) => [index + 1, row.created_at, row.campaign_code, row.name, row.campaign_type_name || (row.source_kind === "agenda" ? "أجندة" : ""), row.objective || "", row.publish_start_date, row.publish_end_date, row.status])]; download("marketing-database.csv", data.map((row) => row.map(csv).join(",")).join("\n")); }
  function sort(key: keyof CampaignRow) { if (sortKey === key) setAscending((value) => !value); else { setSortKey(key); setAscending(true); } }
  return <div className="marketing-page"><PageHead title="قاعدة البيانات" description="جدول بيانات الحملات والأجندات والنتائج وروابط المنصات والأرشفة." actions={<><button className="marketing-button secondary" type="button" onClick={() => void load()}><ArrowsClockwise size={17} />تحديث</button><button className="marketing-button secondary" type="button" onClick={exportRows}><FileCsv size={17} />تصدير</button></>} />
    {error ? <Alert type="error">{error}</Alert> : null}<section className="marketing-filter-bar"><label><MagnifyingGlass size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="بحث بالكود أو اسم الحملة..." /></label><select value={kind} onChange={(event) => setKind(event.target.value)}><option value="">كل المصادر</option><option value="campaign">الحملات</option><option value="agenda">الأجندات</option></select><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">كل الحالات</option><option value="draft">مسودة</option><option value="active">نشطة</option><option value="publishing">قسم النشر</option></select><input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /><input type="date" value={to} onChange={(event) => setTo(event.target.value)} /><label className="marketing-checkbox"><input type="checkbox" checked={archived} onChange={(event) => setArchived(event.target.checked)} />الأرشيف</label></section>
    <section className="marketing-table-card"><div className="marketing-table-wrap"><table className="marketing-table"><thead><tr><th>م</th><th onClick={() => sort("created_at")}>التاريخ</th><th onClick={() => sort("campaign_code")}>كود الحملة</th><th onClick={() => sort("name")}>اسم الحملة</th><th>نوع الحملة</th><th>الهدف من الحملة</th><th>تاريخ بداية الحملة</th><th>تاريخ نهاية الحملة</th><th>عرض البيانات</th><th>إجراءات</th></tr></thead><tbody>{visible.map((row, index) => <tr key={row.id}><td>{index + 1}</td><td>{formatDate(row.created_at)}</td><td><b>{row.campaign_code}</b></td><td>{row.name}</td><td>{row.campaign_type_name || (row.source_kind === "agenda" ? "أجندة" : "—")}</td><td>{row.objective || "—"}</td><td>{formatDate(row.publish_start_date)}</td><td>{formatDate(row.publish_end_date)}</td><td><button type="button" onClick={() => void open(row.id)}><Eye size={17} />عرض البيانات</button></td><td>{meta.permissions.canManage ? <div className="marketing-row-actions">{archived ? <button type="button" onClick={() => void action(row.id, "restore")}><ArrowsClockwise size={16} />استرجاع</button> : <button type="button" onClick={() => void action(row.id, "archive")}><Archive size={16} />أرشيف</button>}<button type="button" className="danger" onClick={() => void action(row.id, "delete")}><Trash size={16} />مسح</button></div> : "—"}</td></tr>)}</tbody></table></div>{!loading && !visible.length ? <Empty text="لا توجد بيانات مطابقة للفلاتر." /> : null}{loading ? <div className="crm-loading-panel">جاري تحميل البيانات...</div> : null}</section>
    <Modal open={Boolean(selectedId)} title={detail ? detail.campaign.name : "عرض بيانات الحملة"} subtitle={detail?.campaign.campaign_code} onClose={() => { setSelectedId(""); setDetail(null); }} wide>{detail ? <CampaignDetailView detail={detail} meta={meta} onChanged={async () => { await open(selectedId); await load(); }} /> : <div className="crm-loading-panel">جاري تحميل البيانات...</div>}</Modal>
  </div>;
}
