import { useEffect, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { CheckCircle, Copy, FloppyDisk, WarningCircle } from "@phosphor-icons/react";
import { marketingFetch, marketingMutation } from "../api";
import type { PublishingItem } from "../types";
import type { MarketingOutletContext } from "../MarketingLayout";
import { copyText, formatMarketingDate, statusTone, toLocalInput } from "../utils";

export function MarketingPublishingPage(){
  const {meta}=useOutletContext<MarketingOutletContext>(); const [rows,setRows]=useState<PublishingItem[]>([]); const [forms,setForms]=useState<Record<string,any>>({}); const [status,setStatus]=useState(""); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  async function load(){try{const data=await marketingFetch<{ok:true;rows:PublishingItem[]}>(`/api/marketing?resource=publishing&status=${encodeURIComponent(status)}`);setRows(data.rows);setForms((current)=>{const next={...current};for(const row of data.rows)next[row.id]||={scheduledAt:toLocalInput(row.scheduled_at),caption:row.caption||'',hashtags:row.hashtags||'',mediaPath:row.media_path||row.output_path||'',status:row.status,externalPostId:row.external_post_id||''};return next;});}catch(f){setError(f instanceof Error?f.message:"تعذر تحميل تجهيز النشر");}}
  useEffect(()=>{void load();},[status]);
  function patch(id:string,key:string,value:string){setForms((current)=>({...current,[id]:{...(current[id]||{}),[key]:value}}));}
  async function save(row:PublishingItem,action='update'){setError("");try{await marketingMutation("publishing","PUT",{id:row.id,action,...forms[row.id]});setMessage(action==='mark_published'?"تم تسجيل النشر":"تم تحديث جدول النشر");await load();}catch(f){setError(f instanceof Error?f.message:"تعذر التحديث");}}
  return <div className="module-page marketing-page"><header className="module-page-head"><div><h1>تجهيز النشر</h1><p>المحتوى النهائي، الكابشن، الهاشتاقات، والمنصة وموعد النشر.</p></div></header><section className="panel marketing-toolbar"><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">كل الحالات</option><option>مسودة</option><option>جاهز للجدولة</option><option>مجدول</option><option>تم النشر</option></select></section>{error?<div className="connection-banner"><WarningCircle size={20}/><span>{error}</span></div>:null}{message?<div className="success-banner">{message}</div>:null}<div className="marketing-publishing-list">{rows.map((row)=>{const form=forms[row.id]||{};return <article className="panel marketing-publishing-card" key={row.id}><header><div><span>{row.campaign_code}</span><h2>{row.campaign_name}</h2><p>{row.creative_name}</p></div><div><em className={`marketing-status ${statusTone(row.status)}`}>{row.status}</em><small>{row.platform_name||row.platform_code} · {row.post_type}</small></div></header><div className="marketing-publishing-grid"><label><span>موعد النشر</span><input type="datetime-local" value={form.scheduledAt||''} onChange={(e)=>patch(row.id,'scheduledAt',e.target.value)}/></label><label><span>الحالة</span><select value={form.status||row.status} onChange={(e)=>patch(row.id,'status',e.target.value)}><option>مسودة</option><option>جاهز للجدولة</option><option>مجدول</option>{row.status==='تم النشر'?<option>تم النشر</option>:null}</select></label><label className="wide"><span>الكابشن</span><textarea rows={4} value={form.caption||''} onChange={(e)=>patch(row.id,'caption',e.target.value)}/></label><label className="wide"><span>الهاشتاقات</span><textarea value={form.hashtags||''} onChange={(e)=>patch(row.id,'hashtags',e.target.value)}/></label><label className="wide"><span>مسار الملف النهائي</span><div><input value={form.mediaPath||''} onChange={(e)=>patch(row.id,'mediaPath',e.target.value)}/><button onClick={()=>void copyText(form.mediaPath||'')}><Copy size={16}/></button></div></label>{row.connection_status?<div className="marketing-connection-state"><b>{row.platform_name}</b><span>{row.connection_status}</span></div>:null}</div><footer><span>{row.scheduled_at?`الموعد الحالي: ${formatMarketingDate(row.scheduled_at,true)}`:'لم يحدد موعد بعد'}</span>{meta.access.canManagePublishing?<div><button onClick={()=>void save(row)}><FloppyDisk size={16}/>حفظ</button>{row.status!=='تم النشر'?<button className="success" onClick={()=>void save(row,'mark_published')}><CheckCircle size={16}/>تم النشر</button>:null}</div>:null}</footer></article>})}{rows.length===0?<div className="marketing-empty panel">لا توجد عناصر نشر مطابقة.</div>:null}</div></div>;
}
