import { useEffect, useState } from "react";
import { ArrowClockwise, Camera, MagnifyingGlass, PencilSimple } from "@phosphor-icons/react";
import { formatMarketingDate, marketingFetch, marketingPost, marketingQuery } from "../api";
import { useMarketing } from "../MarketingContext";
import type { PhotoRequest, PhotoRequestsResponse } from "../types";

export function MarketingRequestsPage() {
  const { meta } = useMarketing();
  const [rows, setRows] = useState<PhotoRequest[]>([]);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [editing, setEditing] = useState<string | null>(null);
  const [form, setForm] = useState({ status: "", photographyDate: "", note: "" });
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const load = async () => { setError(""); try { const payload = await marketingFetch<PhotoRequestsResponse>(`/api/marketing${marketingQuery({ action: "photo_requests", search, status })}`); setRows(payload.rows); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "تعذر تحميل طلبات التصوير"); } };
  useEffect(() => { void load(); }, []);
  if (!meta) return null;
  const beginEdit = (row: PhotoRequest) => { setEditing(row.id); setForm({ status: row.status, photographyDate: row.photography_date?.slice(0, 10) || "", note: row.note || "" }); };
  const save = async (requestId: string) => { setError(""); setMessage(""); try { const result = await marketingPost<{ ok: true; message: string }>({ action: "update_photo_request", requestId, ...form }); setMessage(result.message); setEditing(null); await load(); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "تعذر تحديث الطلب"); } };
  return <div className="marketing-page"><header className="marketing-page-title"><div><h2>متابعة الطلبات</h2><p>طلبات التصوير المشتركة مع نظام العمليات؛ أي تحديث يظهر في النظامين.</p></div><div className="marketing-title-actions"><button onClick={() => void load()}><ArrowClockwise />تحديث</button></div></header>{error ? <div className="marketing-error">{error}</div> : null}{message ? <div className="marketing-success">{message}</div> : null}<section className="marketing-filter-bar"><label className="marketing-search"><MagnifyingGlass /><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void load(); }} placeholder="رقم الطلب أو VIN أو السيارة..." /></label><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">كل الحالات</option>{meta.requestStatuses.filter((row) => row.is_active).map((row) => <option key={row.id} value={row.code}>{row.name}</option>)}</select><button className="primary" onClick={() => void load()}>بحث</button></section><section className="requests-board">{rows.map((row) => <article key={row.id}><header><div><span><Camera />طلب تصوير</span><h3>{row.request_no || row.id.slice(0, 8)}</h3></div><b>{meta.requestStatuses.find((item) => item.code === row.status)?.name || row.status}</b></header><div className="request-vehicles">{row.vehicles.map((vehicle) => <div key={vehicle.id}><strong>{vehicle.vin}</strong><span>{vehicle.car_name} — {vehicle.statement}</span><small>{vehicle.location_name}</small></div>)}</div>{editing === row.id ? <div className="request-edit-form"><label><span>الحالة</span><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}>{meta.requestStatuses.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.code}>{item.name}</option>)}</select></label><label><span>تاريخ التصوير</span><input type="date" value={form.photographyDate} onChange={(event) => setForm({ ...form, photographyDate: event.target.value })} /></label><label className="wide"><span>الملاحظات</span><textarea value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} /></label><div><button onClick={() => setEditing(null)}>إلغاء</button><button className="primary" onClick={() => void save(row.id)}>حفظ التحديث</button></div></div> : <dl><div><dt>منشئ الطلب</dt><dd>{row.requested_by_name || "—"}</dd></div><div><dt>تاريخ الطلب</dt><dd>{formatMarketingDate(row.requested_at, true)}</dd></div><div><dt>تاريخ التصوير</dt><dd>{formatMarketingDate(row.photography_date)}</dd></div><div><dt>الملاحظات</dt><dd>{row.note || "—"}</dd></div></dl>}<footer>{editing !== row.id && meta.permissions.manageRequests ? <button onClick={() => beginEdit(row)}><PencilSimple />تحديث المتابعة</button> : null}</footer></article>)}</section>{!rows.length ? <div className="marketing-empty">لا توجد طلبات تصوير مطابقة.</div> : null}</div>;
}
