import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useOutletContext, useParams } from "react-router-dom";
import { Archive, CheckCircle, Copy, FolderOpen, PencilSimple, RocketLaunch, Trash, WarningCircle } from "@phosphor-icons/react";
import { marketingFetch, marketingMutation } from "../api";
import type { CampaignDetailResponse } from "../types";
import type { MarketingOutletContext } from "../MarketingLayout";
import { copyText, formatMarketingDate, statusTone } from "../utils";

export function MarketingCampaignDetailPage() {
  const { id = "" } = useParams(); const navigate=useNavigate(); const {meta}=useOutletContext<MarketingOutletContext>();
  const [data,setData]=useState<CampaignDetailResponse|null>(null); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function load(){setError("");try{setData(await marketingFetch<CampaignDetailResponse>(`/api/marketing?resource=campaign&id=${encodeURIComponent(id)}`));}catch(f){setError(f instanceof Error?f.message:"تعذر تحميل الحملة");}}
  useEffect(()=>{void load();},[id]);
  const allDone=useMemo(()=>Boolean(data?.tasks.length)&&data!.tasks.every((task)=>task.task_type==='task_template'?task.status==='تاسك معتمد':task.status==='تم الاستلام'),[data]);
  async function action(name:string){setBusy(true);setError("");setMessage("");try{await marketingMutation("campaign-action","POST",{campaignId:id,action:name});setMessage(name==='approve_structure'?"تم اعتماد الهيكل وإنشاء التاسكات":name==='move_to_publishing'?"تم نقل الحملة إلى تجهيز النشر":"تم تنفيذ الإجراء");await load();}catch(f){setError(f instanceof Error?f.message:"تعذر تنفيذ الإجراء");}finally{setBusy(false);}}
  async function remove(){if(!confirm("حذف الحملة؟"))return;setBusy(true);try{await marketingFetch(`/api/marketing?resource=campaigns&id=${encodeURIComponent(id)}`,{method:"DELETE"});navigate('/marketing/campaigns');}catch(f){setError(f instanceof Error?f.message:"تعذر الحذف");}finally{setBusy(false);}}
  if(!data)return <div className="module-page">{error?<div className="connection-banner"><WarningCircle size={20}/><span>{error}</span></div>:<div className="crm-loading-panel">جاري تحميل الحملة...</div>}</div>;
  const {campaign,creatives,tasks,publishing}=data;
  return <div className="module-page marketing-page">
    <header className="module-page-head marketing-detail-head"><div><span className="marketing-kicker">{campaign.campaign_code}</span><h1>{campaign.name}</h1><p>{campaign.objective}</p></div><div className="marketing-head-actions">{meta.access.canManageCampaigns&&campaign.status==='في انتظار اعتماد الهيكل'?<Link to={`/marketing/campaigns/${id}/edit`}><PencilSimple size={17}/>تعديل</Link>:null}{meta.access.canApproveStructure&&campaign.status==='في انتظار اعتماد الهيكل'?<button disabled={busy} className="primary" onClick={()=>void action('approve_structure')}><CheckCircle size={17}/>اعتماد الهيكل</button>:null}{meta.access.canManagePublishing&&allDone&&!['تجهيز النشر','مجدولة','مكتملة'].includes(campaign.status)?<button disabled={busy} className="primary" onClick={()=>void action('move_to_publishing')}><RocketLaunch size={17}/>{publishing.length?'نقل لتجهيز النشر':'إكمال الحملة'}</button>:null}{meta.access.canManageCampaigns?<button disabled={busy} onClick={()=>void action('archive')}><Archive size={17}/>أرشفة</button>:null}{meta.access.canManageCampaigns?<button disabled={busy} className="danger" onClick={()=>void remove()}><Trash size={17}/>حذف</button>:null}</div></header>
    {error?<div className="connection-banner"><WarningCircle size={20}/><span>{error}</span></div>:null}{message?<div className="success-banner">{message}</div>:null}
    <section className="marketing-detail-summary panel"><div><span>الحالة</span><em className={`marketing-status ${statusTone(campaign.status)}`}>{campaign.status}</em></div><div><span>الفترة</span><b>{formatMarketingDate(campaign.starts_at)} — {formatMarketingDate(campaign.ends_at)}</b></div><div><span>الميزانية</span><b>{Number(campaign.budget_total||0).toLocaleString('ar-SA')}</b></div><div><span>اعتماد الهيكل</span><b>{campaign.structure_approved_by_name||'—'}</b></div></section>
    <section className="panel marketing-panel"><header><div><h2>مسار ملفات الحملة</h2><p>المسارات المرجعية لإنشاء فولدرات RAW وOUTPUT على Z.</p></div>{meta.access.canManageCampaigns?<button onClick={()=>void action('create_folders')}><FolderOpen size={17}/>تأكيد تجهيز المسارات</button>:null}</header><div className="marketing-path-row"><code>{campaign.raw_root_path||'—'}</code>{campaign.raw_root_path?<button onClick={()=>void copyText(campaign.raw_root_path!)}><Copy size={16}/></button>:null}</div></section>
    <section className="panel marketing-panel"><header><div><h2>الكرييتيف والهيكل</h2><p>كل نسخة لها instance key مستقل ولا تُدمج مع نسخة أخرى من نفس النوع.</p></div><span>{creatives.length} نسخة</span></header><div className="marketing-creative-detail-list">{creatives.map((creative)=><article key={creative.id}><header><div><b>{creative.instance_key}</b><h3>{creative.name}</h3></div><em className={`marketing-status ${statusTone(creative.status)}`}>{creative.status}</em></header><div className="marketing-creative-meta"><span><b>النوع</b>{creative.creative_type}</span><span><b>الميزانية</b>{Number(creative.budget||0).toLocaleString('ar-SA')}</span><span><b>السيارات</b>{creative.cars.map((car)=>car.name).join('، ')||'—'}</span></div><div className="marketing-path-pair"><span><code>{creative.raw_path}</code><button onClick={()=>void copyText(creative.raw_path||'')}><Copy size={14}/></button></span><span><code>{creative.output_path}</code><button onClick={()=>void copyText(creative.output_path||'')}><Copy size={14}/></button></span></div></article>)}</div></section>
    <section className="panel marketing-panel"><header><div><h2>التاسكات</h2><p>Task Template أولًا، ثم يفتح التنفيذ المرتبط بنفس نسخة الكرييتيف.</p></div><Link to={`/marketing/tasks?campaignId=${id}`}>إدارة التاسكات</Link></header><div className="marketing-detail-task-table"><table><thead><tr><th>التاسك</th><th>القسم</th><th>المسؤول</th><th>الموعد</th><th>الحالة</th></tr></thead><tbody>{tasks.map((task)=><tr key={task.id}><td><strong>{task.title}</strong><small>{task.creative_name}</small></td><td>{meta.departmentLabels[task.department_code]||task.department_code}</td><td>{task.assigned_to_name||'—'}</td><td>{formatMarketingDate(task.due_at,true)}</td><td><em className={`marketing-status ${statusTone(task.status)}`}>{task.status}</em></td></tr>)}</tbody></table></div></section>
    <section className="panel marketing-panel"><header><div><h2>جدول النشر</h2><p>يظهر في تجهيز النشر والتقويم، وأي تعديل ينعكس على نفس العنصر.</p></div><Link to="/marketing/publishing">فتح تجهيز النشر</Link></header><div className="marketing-publish-mini-grid">{publishing.map((item)=><article key={item.id}><b>{item.creative_name}</b><span>{item.platform_name||item.platform_code} · {item.post_type}</span><small>{formatMarketingDate(item.scheduled_at,true)}</small><em className={`marketing-status ${statusTone(item.status)}`}>{item.status}</em></article>)}{publishing.length===0?<div className="marketing-empty">لم تتم إضافة عناصر نشر.</div>:null}</div></section>
  </div>;
}
