import { useEffect, useMemo, useState } from "react";
import { ArrowClockwise, ChartBar, FileXls } from "@phosphor-icons/react";
import { exportXlsx } from "../../operations/excel";
import { formatMarketingDate, marketingFetch, marketingQuery } from "../api";

type ReportsResponse = { ok: true; campaigns: Array<Record<string, unknown>>; employees: Array<Record<string, unknown>> };
const text = (row: Record<string, unknown>, key: string) => String(row[key] ?? "");
const num = (row: Record<string, unknown>, key: string) => Number(row[key] ?? 0) || 0;

export function MarketingReportsPage() {
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [campaigns, setCampaigns] = useState<Array<Record<string, unknown>>>([]);
  const [employees, setEmployees] = useState<Array<Record<string, unknown>>>([]);
  const [error, setError] = useState("");
  const load = async () => { setError(""); try { const payload = await marketingFetch<ReportsResponse>(`/api/marketing${marketingQuery({ action: "reports", from, to })}`); setCampaigns(payload.campaigns); setEmployees(payload.employees); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "تعذر تحميل التقارير"); } };
  useEffect(() => { void load(); }, []);
  const totals = useMemo(() => ({ campaigns: campaigns.length, tasks: campaigns.reduce((sum, row) => sum + num(row, "tasks_count"), 0), completed: campaigns.reduce((sum, row) => sum + num(row, "completed_tasks"), 0), delayed: campaigns.reduce((sum, row) => sum + num(row, "delayed_tasks"), 0), average: campaigns.length ? campaigns.reduce((sum, row) => sum + num(row, "progress"), 0) / campaigns.length : 0 }), [campaigns]);
  const exportReport = () => exportXlsx("marketing-report.xlsx", ["الكود", "الحملة / الأجندة", "المصدر", "الحالة", "البداية", "النهاية", "التاسكات", "المكتملة", "المتأخرة", "التقدم"], campaigns.map((row) => [text(row, "campaign_code"), text(row, "name"), text(row, "source_kind") === "agenda" ? "أجندة" : "حملة", text(row, "status"), text(row, "publish_start"), text(row, "publish_end"), num(row, "tasks_count"), num(row, "completed_tasks"), num(row, "delayed_tasks"), `${Math.round(num(row, "progress"))}%`]), "تقرير التسويق");
  return <div className="marketing-page"><header className="marketing-page-title"><div><h2>التقارير</h2><p>تقارير الحملات والتاسكات والتأخير وأداء الأقسام والموظفين.</p></div><div className="marketing-title-actions"><button onClick={() => void load()}><ArrowClockwise />تحديث</button><button onClick={exportReport}><FileXls />تصدير Excel</button></div></header><section className="marketing-filter-bar"><label><span>من</span><input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label><span>إلى</span><input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><button className="primary" onClick={() => void load()}>عرض التقرير</button></section>{error ? <div className="marketing-error">{error}</div> : null}<div className="marketing-stat-grid five"><article><span>إجمالي الحملات</span><strong>{totals.campaigns}</strong></article><article><span>إجمالي التاسكات</span><strong>{totals.tasks}</strong></article><article><span>التاسكات المكتملة</span><strong>{totals.completed}</strong></article><article><span>التاسكات المتأخرة</span><strong>{totals.delayed}</strong></article><article><span>نسبة الإنجاز</span><strong>{Math.round(totals.average)}%</strong></article></div><div className="reports-grid"><section className="marketing-table-panel"><header><ChartBar /><h3>متابعة الحملات والأجندات</h3></header><div className="marketing-table-scroll"><table><thead><tr><th>الكود</th><th>الاسم</th><th>المصدر</th><th>الحالة</th><th>الفترة</th><th>التاسكات</th><th>المكتملة</th><th>المتأخرة</th><th>التقدم</th></tr></thead><tbody>{campaigns.map((row) => <tr key={text(row, "id")}><td>{text(row, "campaign_code")}</td><td>{text(row, "name")}</td><td>{text(row, "source_kind") === "agenda" ? "أجندة" : "حملة"}</td><td>{text(row, "status")}</td><td>{formatMarketingDate(text(row, "publish_start"))} — {formatMarketingDate(text(row, "publish_end"))}</td><td>{num(row, "tasks_count")}</td><td>{num(row, "completed_tasks")}</td><td>{num(row, "delayed_tasks")}</td><td><div className="marketing-mini-progress"><span style={{ width: `${Math.min(100, num(row, "progress"))}%` }} /><b>{Math.round(num(row, "progress"))}%</b></div></td></tr>)}</tbody></table></div></section><section className="marketing-table-panel"><header><ChartBar /><h3>أداء كل موظف</h3></header><div className="marketing-table-scroll"><table><thead><tr><th>الموظف</th><th>القسم</th><th>التاسكات</th><th>المكتملة</th><th>المتأخرة</th><th>متوسط التقدم</th></tr></thead><tbody>{employees.map((row) => <tr key={`${text(row, "id")}-${text(row, "department_name")}`}><td>{text(row, "full_name")}</td><td>{text(row, "department_name")}</td><td>{num(row, "tasks_count")}</td><td>{num(row, "completed_count")}</td><td>{num(row, "delayed_count")}</td><td>{Math.round(num(row, "average_progress"))}%</td></tr>)}</tbody></table></div></section></div></div>;
}
