import { useEffect, useMemo, useState } from "react";
import { CaretLeft, CaretRight, WarningCircle } from "@phosphor-icons/react";
import { marketingFetch } from "../api";
import type { MarketingAgendaItem, PublishingItem } from "../types";
import { formatMarketingDate, statusTone } from "../utils";

type CalendarEvent={id:string;title:string;date:string;kind:"agenda"|"publish";status:string;subtitle:string};
export function MarketingCalendarPage(){
  const [cursor,setCursor]=useState(()=>new Date()); const [agenda,setAgenda]=useState<MarketingAgendaItem[]>([]); const [publishing,setPublishing]=useState<PublishingItem[]>([]); const [error,setError]=useState("");
  const start=new Date(cursor.getFullYear(),cursor.getMonth(),1); const end=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);
  useEffect(()=>{Promise.all([marketingFetch<{ok:true;rows:MarketingAgendaItem[]}>(`/api/marketing?resource=agenda&from=${start.toISOString()}&to=${end.toISOString()}`),marketingFetch<{ok:true;rows:PublishingItem[]}>("/api/marketing?resource=publishing")]).then(([a,p])=>{setAgenda(a.rows);setPublishing(p.rows.filter((x)=>x.scheduled_at&&new Date(x.scheduled_at)>=start&&new Date(x.scheduled_at)<end));}).catch((f)=>setError(f.message));},[cursor.getFullYear(),cursor.getMonth()]);
  const events=useMemo<CalendarEvent[]>(()=>[...agenda.map((x)=>({id:`a-${x.id}`,title:x.title,date:x.starts_at,kind:'agenda' as const,status:x.status,subtitle:x.owner_name||x.campaign_name||'أجندة'})),...publishing.map((x)=>({id:`p-${x.id}`,title:x.creative_name,date:x.scheduled_at!,kind:'publish' as const,status:x.status,subtitle:`${x.platform_name||x.platform_code} · ${x.post_type}`}))],[agenda,publishing]);
  const firstWeekday=start.getDay(); const days=new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate(); const cells=Array.from({length:firstWeekday+days},(_,i)=>i<firstWeekday?null:i-firstWeekday+1);
  return <div className="module-page marketing-page"><header className="module-page-head"><div><h1>تقويم التسويق</h1><p>الأجندة ومواعيد النشر في عرض شهري موحد.</p></div><div className="marketing-calendar-controls"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><CaretRight size={18}/></button><b>{new Intl.DateTimeFormat('ar-SA',{month:'long',year:'numeric'}).format(cursor)}</b><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><CaretLeft size={18}/></button></div></header>{error?<div className="connection-banner"><WarningCircle size={20}/><span>{error}</span></div>:null}<section className="panel marketing-calendar"><div className="marketing-calendar-week"><b>الأحد</b><b>الاثنين</b><b>الثلاثاء</b><b>الأربعاء</b><b>الخميس</b><b>الجمعة</b><b>السبت</b></div><div className="marketing-calendar-grid">{cells.map((day,index)=><article key={index} className={!day?'empty':''}>{day?<><header><b>{day}</b></header><div>{events.filter((event)=>new Date(event.date).getDate()===day).map((event)=><span key={event.id} className={event.kind}><strong>{event.title}</strong><small>{event.subtitle}</small><em className={`marketing-status ${statusTone(event.status)}`}>{event.status}</em></span>)}</div></>:null}</article>)}</div></section><div className="marketing-calendar-upcoming panel"><h2>مواعيد الشهر</h2>{[...events].sort((a,b)=>a.date.localeCompare(b.date)).map((event)=><article key={event.id}><b>{event.title}</b><span>{event.subtitle}</span><small>{formatMarketingDate(event.date,true)}</small></article>)}</div></div>;
}
