import { useEffect, useState } from "react";
import { ArrowClockwise, Clock, FloppyDisk } from "@phosphor-icons/react";
import { formatMarketingDate, marketingFetch, marketingPost, marketingQuery } from "../api";
import { useMarketing } from "../MarketingContext";
import type { GenericRowsResponse } from "../types";
const text = (row: Record<string, unknown>, key: string) => String(row[key] ?? "");

export function MarketingAttendancePage() {
  const { meta } = useMarketing();
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [rows, setRows] = useState<Array<Record<string, unknown>>>([]);
  const [form, setForm] = useState({ userId: "", date: new Date().toISOString().slice(0, 10), checkIn: "", checkOut: "", status: "present", notes: "" });
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const load = async () => { setError(""); try { const payload = await marketingFetch<GenericRowsResponse>(`/api/marketing${marketingQuery({ action: "attendance", month })}`); setRows(payload.rows); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "تعذر تحميل الحضور والانصراف"); } };
  useEffect(() => { void load(); }, [month]);
  if (!meta) return null;
  const save = async () => { setError(""); setMessage(""); try { const result = await marketingPost<{ ok: true; message: string }>({ action: "save_attendance", ...form }); setMessage(result.message); await load(); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "تعذر حفظ الحضور"); } };
  return <div className="marketing-page"><header className="marketing-page-title"><div><h2>الحضور والانصراف</h2><p>سجل حضور وانصراف موظفي التسويق حسب الشهر.</p></div><div className="marketing-title-actions"><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /><button onClick={() => void load()}><ArrowClockwise />تحديث</button></div></header>{error ? <div className="marketing-error">{error}</div> : null}{message ? <div className="marketing-success">{message}</div> : null}{meta.permissions.admin ? <section className="attendance-form panel"><h3><Clock />تسجيل حضور وانصراف</h3><div className="marketing-form-grid six"><label><span>الموظف</span><select value={form.userId} onChange={(event) => setForm({ ...form, userId: event.target.value })}><option value="">اختر الموظف</option>{meta.users.map((user) => <option key={user.id} value={user.id}>{user.full_name}</option>)}</select></label><label><span>التاريخ</span><input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label><span>الحضور</span><input type="time" value={form.checkIn} onChange={(event) => setForm({ ...form, checkIn: event.target.value })} /></label><label><span>الانصراف</span><input type="time" value={form.checkOut} onChange={(event) => setForm({ ...form, checkOut: event.target.value })} /></label><label><span>الحالة</span><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="present">حاضر</option><option value="absent">غائب</option><option value="leave">إجازة</option><option value="late">متأخر</option></select></label><button className="primary" disabled={!form.userId || !form.date} onClick={() => void save()}><FloppyDisk />حفظ</button><label className="wide"><span>ملاحظات</span><input value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></div></section> : null}<section className="marketing-table-panel"><div className="marketing-table-scroll"><table><thead><tr><th>التاريخ</th><th>الموظف</th><th>الحضور</th><th>الانصراف</th><th>الحالة</th><th>الملاحظات</th></tr></thead><tbody>{rows.map((row) => <tr key={text(row, "id")}><td>{formatMarketingDate(text(row, "attendance_date"))}</td><td>{text(row, "full_name")}</td><td>{text(row, "check_in_at") ? new Date(text(row, "check_in_at")).toLocaleTimeString("ar-SA", { hour: "2-digit", minute: "2-digit" }) : "—"}</td><td>{text(row, "check_out_at") ? new Date(text(row, "check_out_at")).toLocaleTimeString("ar-SA", { hour: "2-digit", minute: "2-digit" }) : "—"}</td><td>{text(row, "status")}</td><td>{text(row, "notes") || "—"}</td></tr>)}</tbody></table></div>{!rows.length ? <div className="marketing-empty">لا توجد سجلات في الشهر المحدد.</div> : null}</section></div>;
}
