import { useEffect, useMemo, useState } from "react";
import { useOutletContext, useSearchParams } from "react-router-dom";
import {
  Archive, CalendarBlank, ChartBar, CheckCircle, CirclesFour, ClockCountdown, Eye, Gift, LinkSimple, ListChecks, Package,
  PaperPlaneTilt, PencilSimple, Printer, Plus, SignIn, SignOut, Trash, UsersThree, Warehouse, WarningCircle,
} from "@phosphor-icons/react";
import type { MarketingOutletContext } from "../MarketingLayout";
import type { MarketingDashboardData, MarketingProjectSummary, MarketingTask, ProjectListRow } from "../types";
import { formatMarketingDate, marketingFetch, marketingQuery, statusLabel } from "../api";
import { Field, MarketingBadge, MarketingEmpty, MarketingError, MarketingLoading, MarketingPageHeader, MarketingSearch, MarketingStat, ProgressBar } from "../components/Common";
import { ProjectDetailsModal } from "../components/ProjectDetailsModal";
import { ProjectWizard } from "../components/ProjectWizard";
import { TaskDetailsModal } from "../components/TaskDetailsModal";

function useMarketing() { return useOutletContext<MarketingOutletContext>(); }
function exportRows(name: string, rows: Array<Array<unknown>>) { const csv = "\ufeff" + rows.map((row) => row.map((cell) => `"${String(cell ?? "").replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); link.download = name; link.click(); URL.revokeObjectURL(link.href); }
function groupTasks(tasks: MarketingTask[], selector: (task: MarketingTask) => string) {
  const groups = new Map<string, MarketingTask[]>();
  for (const task of tasks) {
    const key = selector(task) || "غير محدد";
    groups.set(key, [...(groups.get(key) || []), task]);
  }
  return [...groups.entries()];
}
function DashboardTaskCard({ task, onOpen }: { task: MarketingTask; onOpen: (task: MarketingTask) => void }) {
  return <button type="button" className="marketing-dashboard-task" onClick={() => onOpen(task)}><div className="marketing-dashboard-task-head"><div><strong>{task.task_no}</strong><span>{task.creative_type || "—"} — {task.instance_no || "—"}</span></div><MarketingBadge value={statusLabel(task.status)} /></div><div className="marketing-dashboard-task-meta"><span>{task.project_name}</span><span>{task.assigned_name || "—"}</span><span>{task.content_writer_name ? `كاتب المحتوى: ${task.content_writer_name}` : task.department_name || "قسم المحتوى"}</span><span>{formatMarketingDate(task.due_at, true)}</span></div><ProgressBar value={task.progress} /></button>;
}

export function MarketingDashboardPage() {
  const { meta } = useMarketing();
  const [data, setData] = useState<MarketingDashboardData | null>(null); const [error, setError] = useState(""); const [selectedTask, setSelectedTask] = useState<MarketingTask | null>(null); const [projectId, setProjectId] = useState<string | null>(null);
  async function load() { setError(""); try { setData(await marketingFetch<MarketingDashboardData>("/api/marketing?resource=dashboard")); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل لوحة التحكم"); } }
  useEffect(() => { void load(); }, []);
  const dashboardGroups = useMemo(() => {
    const tasks = data?.tasks || [];
    const required = tasks.filter((row) => !row.received_at && row.project_stage !== "publishing");
    const readiness = tasks.filter((row) => Boolean(row.received_at) && row.project_stage !== "publishing");
    const publishing = tasks.filter((row) => row.project_stage === "publishing");
    return {
      requiredByDepartment: groupTasks(required, (row) => row.department_name || (row.task_kind === "template" ? "قسم المحتوى" : "غير محدد")),
      readinessByProject: groupTasks(readiness, (row) => row.campaign_id),
      publishingByProject: groupTasks(publishing, (row) => row.campaign_id),
    };
  }, [data]);
  async function moveToPublish(projectId: string) {
    try { await marketingFetch("/api/marketing", { method: "POST", body: JSON.stringify({ action: "move_to_publish", id: projectId }) }); await load(); }
    catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر النقل إلى قسم النشر"); }
  }
  return <div className="module-page marketing-page"><MarketingPageHeader title="لوحة تحكم التسويق" description="متابعة Task Template، جاهزية الأقسام، والنقل الفعلي لقسم النشر." />
    {error ? <MarketingError message={error} onRetry={() => void load()} /> : !data ? <MarketingLoading /> : <>
      <div className="marketing-stats-grid"><MarketingStat label="إجمالي المشاريع" value={data.counts.projects} detail="حملات + أجندات" icon={CirclesFour} /><MarketingStat label="الحملات" value={data.counts.campaigns} icon={ChartBar} /><MarketingStat label="الأجندات" value={data.counts.agendas} icon={CalendarBlank} /><MarketingStat label="قسم النشر" value={data.counts.publishing} detail={`${data.pendingReviews} مراجعات معلقة`} icon={PaperPlaneTilt} /></div>
      <div className="marketing-dashboard-flow">
        <section className="panel marketing-flow-card"><header><div><h2>TASK - المطلوب</h2><p>التاسكات التي لم يضغط مسؤولها «تم الاستلام»، مجمعة حسب القسم.</p></div><span>{dashboardGroups.requiredByDepartment.reduce((sum, [, tasks]) => sum + tasks.length, 0)}</span></header>{dashboardGroups.requiredByDepartment.length ? <div className="marketing-dashboard-accordions">{dashboardGroups.requiredByDepartment.map(([department, tasks]) => <details key={department} open><summary><strong>{department}</strong><span>{tasks.length} تاسك</span></summary><div>{tasks.map((task) => <DashboardTaskCard key={task.id} task={task} onOpen={setSelectedTask} />)}</div></details>)}</div> : <MarketingEmpty title="لا توجد تاسكات مطلوبة" description="كل التاسكات المتاحة تم استلامها أو لا توجد بيانات حالية." />}</section>

        <section className="panel marketing-flow-card"><header><div><h2>جاهزية المطلوب</h2><p>الحملات والأجندات التي تحتوي على تاسكات مستلمة، مع الأقسام والتقدم الفعلي.</p></div><span>{dashboardGroups.readinessByProject.length}</span></header>{dashboardGroups.readinessByProject.length ? <div className="marketing-project-readiness-list">{dashboardGroups.readinessByProject.map(([campaignId, tasks]) => { const project = data.projects.find((row) => row.id === campaignId); const departments = groupTasks(tasks, (row) => row.department_name || (row.task_kind === "template" ? "قسم المحتوى" : "غير محدد")); return <article key={campaignId}><header><button type="button" onClick={() => setProjectId(campaignId)}><div><strong>{project?.name || tasks[0]?.project_name}</strong><span>{project?.campaign_code || tasks[0]?.campaign_code} — {project?.source_kind === "agenda" ? "أجندة" : "حملة"}</span></div></button><MarketingBadge value={statusLabel(project?.stage || "required")} />{project ? <ProgressBar value={project.progress} /> : null}{project && project.progress >= 99.99 && meta.permissions["marketing.publish.manage"] ? <button className="marketing-primary-button" type="button" onClick={() => void moveToPublish(project.id)}>نقل الحملة إلى قسم النشر</button> : null}</header><div className="marketing-dashboard-accordions">{departments.map(([department, departmentTasks]) => <details key={department}><summary><strong>{department}</strong><span>{departmentTasks.length} تاسك — {Math.round(departmentTasks.reduce((sum, task) => sum + Number(task.progress || 0), 0) / Math.max(1, departmentTasks.length))}%</span></summary><div>{departmentTasks.map((task) => <DashboardTaskCard key={task.id} task={task} onOpen={setSelectedTask} />)}</div></details>)}</div></article>; })}</div> : <MarketingEmpty title="لا توجد حملات في الجاهزية" description="تظهر هنا الحملات بعد تسجيل الاستلام الفعلي للتاسكات." />}</section>

        <section className="panel marketing-flow-card"><header><div><h2>قسم النشر</h2><p>الحملات والأجندات المنقولة فعليًا بعد اكتمال الأقسام بنسبة 100%.</p></div><span>{dashboardGroups.publishingByProject.length}</span></header>{dashboardGroups.publishingByProject.length ? <div className="marketing-project-readiness-list publishing">{dashboardGroups.publishingByProject.map(([campaignId, tasks]) => { const project = data.projects.find((row) => row.id === campaignId); const departments = groupTasks(tasks, (row) => row.department_name || (row.task_kind === "template" ? "قسم المحتوى" : "غير محدد")); return <article key={campaignId}><header><button type="button" onClick={() => setProjectId(campaignId)}><div><strong>{project?.name || tasks[0]?.project_name}</strong><span>{project?.campaign_code || tasks[0]?.campaign_code}</span></div></button><MarketingBadge value="قسم النشر" /><button type="button" className="marketing-secondary-button" onClick={() => setProjectId(campaignId)}>عرض جدول النشر</button></header><div className="marketing-dashboard-accordions">{departments.map(([department, departmentTasks]) => <details key={department}><summary><strong>{department}</strong><span>{departmentTasks.length} تاسك</span></summary><div>{departmentTasks.map((task) => <DashboardTaskCard key={task.id} task={task} onOpen={setSelectedTask} />)}</div></details>)}</div></article>; })}</div> : <MarketingEmpty title="قسم النشر فارغ" description="لا يتم نقل أي مشروع هنا قبل اكتمال جميع الأقسام." />}</section>
      </div>
    </>}
    <TaskDetailsModal task={selectedTask} meta={meta} onClose={() => setSelectedTask(null)} onChanged={load} /><ProjectDetailsModal projectId={projectId} meta={meta} onClose={() => setProjectId(null)} onChanged={load} />
  </div>;
}

function ProjectsTable({ title, description, defaultKind = "", management = false }: { title: string; description: string; defaultKind?: string; management?: boolean }) {
  const { meta } = useMarketing(); const [searchParams] = useSearchParams();
  const [rows, setRows] = useState<ProjectListRow[]>([]); const [search, setSearch] = useState(""); const [kind, setKind] = useState(defaultKind); const [stage, setStage] = useState(""); const [archived, setArchived] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [projectId, setProjectId] = useState<string | null>(searchParams.get("project"));
  async function load() { setLoading(true); setError(""); try { const result = await marketingFetch<{ ok: true; rows: ProjectListRow[] }>(`/api/marketing${marketingQuery({ resource: "projects", search, kind, stage, archived })}`); setRows(result.rows); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل المشاريع"); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 200); return () => window.clearTimeout(timer); }, [search, kind, stage, archived]);
  return <div className="module-page marketing-page"><MarketingPageHeader title={title} description={description} actions={<button className="marketing-secondary-button" type="button" onClick={() => exportRows("marketing-projects.csv", [["الكود","الاسم","النوع","المرحلة","التقدم","الإنشاء"], ...rows.map((row) => [row.campaign_code,row.name,row.source_kind,statusLabel(row.stage),row.progress,row.created_at])])}>تصدير CSV</button>} />
    <section className="panel marketing-filter-bar"><MarketingSearch value={search} onChange={setSearch} placeholder="بحث بالاسم أو الكود أو الهدف" /><select value={kind} onChange={(event) => setKind(event.target.value)}><option value="">كل المصادر</option><option value="campaign">حملات</option><option value="agenda">أجندات</option></select><select value={stage} onChange={(event) => setStage(event.target.value)}><option value="">كل المراحل</option><option value="required">TASK المطلوبة</option><option value="publishing">قسم النشر</option></select><label className="marketing-inline-check"><input type="checkbox" checked={archived} onChange={(event) => setArchived(event.target.checked)} /><span>الأرشيف</span></label></section>
    {error ? <MarketingError message={error} onRetry={() => void load()} /> : loading ? <MarketingLoading /> : rows.length ? <section className="panel marketing-table-wrap"><table><thead><tr><th>الكود</th><th>المشروع</th><th>المصدر</th><th>الكرييتيف</th><th>التاسكات</th><th>المرحلة</th><th>التقدم</th><th>الفترة</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.campaign_code}</strong></td><td><strong>{row.name}</strong><small>{row.campaign_type || row.objective || "—"}</small></td><td>{row.source_kind === "agenda" ? "أجندة" : "حملة"}</td><td>{row.creative_count}</td><td>{row.task_count}</td><td><MarketingBadge value={statusLabel(row.stage)} /></td><td><ProgressBar value={row.progress} /></td><td>{formatMarketingDate(row.starts_on)} — {formatMarketingDate(row.ends_on)}</td><td><button type="button" className="marketing-icon-button" onClick={() => setProjectId(row.id)}><Eye size={18} /></button></td></tr>)}</tbody></table></section> : <MarketingEmpty title="لا توجد نتائج" description="لم يتم العثور على حملات أو أجندات مطابقة للفلاتر." />}
    {management ? <p className="marketing-page-hint">الحذف والأرشفة والنقل للنشر وإنشاء فولدرات الخام متاحة من نافذة التفاصيل وفق الصلاحيات.</p> : null}<ProjectDetailsModal projectId={projectId} meta={meta} onClose={() => setProjectId(null)} onChanged={load} />
  </div>;
}
export function MarketingDatabasePage() { return <ProjectsTable title="قاعدة بيانات التسويق" description="بحث وعرض وتصفية وتصدير لكل الحملات والأجندات من PostgreSQL." />; }
export function MarketingCampaignsPage() { return <ProjectsTable title="إدارة الحملات والأجندات" description="إدارة دورة المشروع، الأرشفة، المسح الناعم، والتقدم حسب الأقسام." management />; }
export function MarketingCreateCampaignPage() { const { meta } = useMarketing(); return <ProjectWizard kind="campaign" meta={meta} />; }
export function MarketingCreateAgendaPage() { const { meta } = useMarketing(); return <ProjectWizard kind="agenda" meta={meta} />; }

type PackageRow = { id: string; name: string; category_id: string; category_name?: string | null; price: number; cash_discount_percent: number; registration_fee: number; insurance_fee: number; issuance_fee: number; care_items: string[]; delivery_home: boolean; delivery_region?: string | null };
const emptyPackage = { id: "", name: "", categoryId: "", price: 0, cashDiscountPercent: 0, registrationFee: 0, insuranceFee: 0, issuanceFee: 0, careItems: "", deliveryHome: false, deliveryRegion: "" };
export function MarketingPackagesPage() {
  const { meta } = useMarketing(); const [rows, setRows] = useState<PackageRow[]>([]); const [counts, setCounts] = useState<Record<string, number>>({}); const [total, setTotal] = useState(0); const [search, setSearch] = useState(""); const [categoryId, setCategoryId] = useState(""); const [form, setForm] = useState(emptyPackage); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const result = await marketingFetch<{ ok: true; rows: PackageRow[]; counts: Record<string, number>; total: number }>(`/api/marketing${marketingQuery({ resource: "packages", search, categoryId })}`); setRows(result.rows); setCounts(result.counts || {}); setTotal(result.total || 0); }
  useEffect(() => { const timer = window.setTimeout(() => void load().catch((error) => setMessage(error.message)), 200); return () => window.clearTimeout(timer); }, [search, categoryId]);
  async function save() { setBusy(true); setMessage(""); try { const result = await marketingFetch<{ ok: true; message: string }>("/api/marketing", { method: "POST", body: JSON.stringify({ action: "save_package", ...form, careItems: form.careItems.split(/[,،\n]/).map((item) => item.trim()).filter(Boolean) }) }); setMessage(result.message); setForm(emptyPackage); await load(); } catch (failure) { setMessage(failure instanceof Error ? failure.message : "تعذر الحفظ"); } finally { setBusy(false); } }
  async function remove(id: string) { if (!window.confirm("تأكيد حذف الباقة؟")) return; await marketingFetch("/api/marketing", { method: "POST", body: JSON.stringify({ action: "delete_package", id }) }); await load(); }
  function edit(row: PackageRow) { setForm({ id: row.id, name: row.name, categoryId: row.category_id, price: row.price, cashDiscountPercent: row.cash_discount_percent, registrationFee: row.registration_fee, insuranceFee: row.insurance_fee, issuanceFee: row.issuance_fee, careItems: (row.care_items || []).join("، "), deliveryHome: row.delivery_home, deliveryRegion: row.delivery_region || "" }); }
  return <div className="module-page marketing-page"><MarketingPageHeader title="إدارة الباقات" description="تصنيفات ديناميكية وأسعار ورسوم وخصومات وخدمات تسليم من إعدادات التسويق." actions={<button type="button" className="marketing-secondary-button" onClick={() => window.print()}><Printer size={17} />طباعة / PDF</button>} />
    <div className="marketing-package-tabs"><button type="button" className={!categoryId ? "active" : ""} onClick={() => setCategoryId("")}>كل التصنيفات ({total})</button>{meta.categories.filter((row) => row.is_active).map((row) => <button type="button" key={row.id} className={categoryId === row.id ? "active" : ""} onClick={() => setCategoryId(row.id)}>{row.name} ({counts[row.id] || 0})</button>)}</div>
    <div className="marketing-two-column"><section className="panel"><div className="marketing-filter-bar"><MarketingSearch value={search} onChange={setSearch} placeholder="بحث في الباقات" /><select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">كل التصنيفات</option>{meta.categories.filter((row) => row.is_active).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><div className="marketing-package-grid">{rows.map((row) => <article key={row.id}><header><Gift size={24} weight="duotone" /><div><strong>{row.name}</strong><span>{row.category_name || "بدون تصنيف"}</span></div></header><b>{Number(row.price).toLocaleString("ar-SA")} ر.س</b><div><span>خصم كاش {row.cash_discount_percent}%</span><span>تسجيل {row.registration_fee}</span><span>تأمين {row.insurance_fee}</span></div>{row.care_items?.length ? <p>{row.care_items.join("، ")}</p> : null}{meta.permissions["marketing.package.manage"] ? <footer><button type="button" onClick={() => edit(row)}><PencilSimple size={17} />تعديل</button><button type="button" onClick={() => void remove(row.id)}><Trash size={17} />حذف</button></footer> : null}</article>)}</div></section>
      {meta.permissions["marketing.package.manage"] ? <section className="panel marketing-side-form"><h2>{form.id ? "تعديل الباقة" : "إضافة باقة"}</h2><Field label="اسم الباقة"><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="التصنيف"><select value={form.categoryId} onChange={(event) => setForm({ ...form, categoryId: event.target.value })}><option value="">اختر التصنيف</option>{meta.categories.filter((row) => row.is_active).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><div className="marketing-form-grid"><Field label="السعر"><input type="number" min="0" value={form.price} onChange={(event) => setForm({ ...form, price: Number(event.target.value) })} /></Field><Field label="خصم الكاش %"><input type="number" min="0" value={form.cashDiscountPercent} onChange={(event) => setForm({ ...form, cashDiscountPercent: Number(event.target.value) })} /></Field><Field label="رسوم التسجيل"><input type="number" min="0" value={form.registrationFee} onChange={(event) => setForm({ ...form, registrationFee: Number(event.target.value) })} /></Field><Field label="رسوم التأمين"><input type="number" min="0" value={form.insuranceFee} onChange={(event) => setForm({ ...form, insuranceFee: Number(event.target.value) })} /></Field><Field label="رسوم الإصدار"><input type="number" min="0" value={form.issuanceFee} onChange={(event) => setForm({ ...form, issuanceFee: Number(event.target.value) })} /></Field></div><Field label="عناصر العناية"><textarea value={form.careItems} onChange={(event) => setForm({ ...form, careItems: event.target.value })} /></Field><label className="marketing-inline-check"><input type="checkbox" checked={form.deliveryHome} onChange={(event) => setForm({ ...form, deliveryHome: event.target.checked })} /><span>توصيل للمنزل</span></label><Field label="منطقة التوصيل"><input value={form.deliveryRegion} onChange={(event) => setForm({ ...form, deliveryRegion: event.target.value })} /></Field><button className="marketing-primary-button" type="button" disabled={busy} onClick={() => void save()}>{busy ? "جاري الحفظ..." : "حفظ الباقة"}</button>{form.id ? <button className="marketing-secondary-button" type="button" onClick={() => setForm(emptyPackage)}>إلغاء التعديل</button> : null}{message ? <p className="marketing-form-message">{message}</p> : null}</section> : null}</div>
  </div>;
}

type PublishRow = { id: string; task_no: string; status: string; progress: number; final_file_name?: string | null; campaign_id: string; project_name: string; campaign_code: string; source_kind: string; stage: string; instance_no?: string; creative_type?: string; assigned_name?: string; department_name?: string; publications: Array<{ platform_id: string; platform_name: string; post_type: string; publish_date: string; publish_time?: string }>; files: Array<{ id: string; file_name: string; created_at: string }> };
export function MarketingPublishPrepPage() {
  const { meta } = useMarketing(); const [rows, setRows] = useState<PublishRow[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [platformId, setPlatformId] = useState(""); const [task, setTask] = useState<MarketingTask | null>(null); const [projectId, setProjectId] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { const result = await marketingFetch<{ ok: true; rows: PublishRow[] }>(`/api/marketing${marketingQuery({ resource: "publish_prep", search, status, platformId })}`); setRows(result.rows); } finally { setLoading(false); } }
  async function openTask(row: PublishRow) { try { const detail = await marketingFetch<{ ok: true; tasks: MarketingTask[] }>(`/api/marketing?resource=project&id=${encodeURIComponent(row.campaign_id)}`); setTask(detail.tasks.find((item) => item.id === row.id) || null); } catch { setTask(null); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 200); return () => window.clearTimeout(timer); }, [search, status, platformId]);
  return <div className="module-page marketing-page"><MarketingPageHeader title="تجهيز النشر" description="الملفات النهائية ومواعيد ومنصات النشر مرتبطة بالكرييتيف والتاسك الصحيح." /><section className="panel marketing-filter-bar"><MarketingSearch value={search} onChange={setSearch} /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">كل الحالات</option><option value="required">مطلوب</option><option value="active">قيد التنفيذ</option><option value="completed">مكتمل</option></select><select value={platformId} onChange={(event) => setPlatformId(event.target.value)}><option value="">كل المنصات</option>{meta.platforms.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></section>{loading ? <MarketingLoading /> : <div className="marketing-publish-grid">{rows.map((row) => <article className="panel" key={row.id}><header><div><strong>{row.project_name}</strong><span>{row.campaign_code} — {row.instance_no} — {row.creative_type}</span></div><MarketingBadge value={statusLabel(row.status)} /></header><ProgressBar value={row.progress} /><div className="marketing-publication-list">{row.publications.length ? row.publications.map((item, index) => <span key={`${item.platform_id}-${index}`}><b>{item.platform_name}</b>{item.post_type} — {formatMarketingDate(item.publish_date)} {item.publish_time || ""}</span>) : <span>لا يوجد موعد نشر مسجل</span>}</div><footer><button type="button" onClick={() => setProjectId(row.campaign_id)}>تفاصيل المشروع</button><button type="button" onClick={() => void openTask(row)}>فتح التاسك</button></footer></article>)}</div>}<TaskDetailsModal task={task} meta={meta} onClose={() => setTask(null)} onChanged={load} /><ProjectDetailsModal projectId={projectId} meta={meta} onClose={() => setProjectId(null)} onChanged={load} /></div>;
}

type StockRow = { id: string; vin: string; car_name?: string; statement?: string; interior_color?: string; exterior_color?: string; model_year?: string; status_name?: string; location_name?: string; has_active_photo_request: boolean };
type PhotoRequest = { id: string; request_no: string; status: string; requested_by_name: string; requested_at: string; photography_date: string; note?: string; vehicles: Array<{ vehicle_id: string; vin: string; car_name?: string; statement?: string; location_name?: string }>; events: Array<{ id: string; status: string; actor_name?: string; note?: string; created_at: string }> };
export function MarketingStockPage() {
  const { meta } = useMarketing(); const [rows, setRows] = useState<StockRow[]>([]); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [note, setNote] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { const result = await marketingFetch<{ ok: true; rows: StockRow[] }>(`/api/marketing?resource=stock&search=${encodeURIComponent(search)}`); setRows(result.rows); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 180); return () => window.clearTimeout(timer); }, [search]);
  async function requestPhoto() { try { const result = await marketingFetch<{ ok: true; message: string }>("/api/marketing", { method: "POST", body: JSON.stringify({ action: "create_photo_request", vehicleIds: selected, photographyDate: date, note }) }); setMessage(result.message); setSelected([]); setNote(""); await load(); } catch (failure) { setMessage(failure instanceof Error ? failure.message : "تعذر إنشاء الطلب"); } }
  return <div className="module-page marketing-page"><MarketingPageHeader title="الاستوك" description="قراءة مباشرة فقط من استوك العمليات، مع إنشاء طلب تصوير في نفس سجل العمليات." actions={meta.permissions["marketing.photo_request.create"] ? <button className="marketing-primary-button" type="button" disabled={!selected.length} onClick={() => void requestPhoto()}>إنشاء طلب تصوير ({selected.length})</button> : undefined} /><section className="panel marketing-filter-bar"><MarketingSearch value={search} onChange={setSearch} placeholder="VIN أو اسم السيارة" /><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /><input value={note} onChange={(event) => setNote(event.target.value)} placeholder="ملاحظة طلب التصوير" /></section>{message ? <p className="marketing-form-message">{message}</p> : null}{loading ? <MarketingLoading /> : <section className="panel marketing-table-wrap"><table><thead><tr><th>اختيار</th><th>السيارة</th><th>VIN</th><th>الموديل</th><th>الخارجي</th><th>الداخلي</th><th>الموقع</th><th>التصوير</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><input type="checkbox" disabled={row.has_active_photo_request} checked={selected.includes(row.id)} onChange={(event) => setSelected((values) => event.target.checked ? [...values, row.id] : values.filter((id) => id !== row.id))} /></td><td><strong>{row.car_name || row.statement || "—"}</strong></td><td>{row.vin}</td><td>{row.model_year || "—"}</td><td>{row.exterior_color || "—"}</td><td>{row.interior_color || "—"}</td><td>{row.location_name || "—"}</td><td><MarketingBadge value={row.has_active_photo_request ? "طلب نشط" : "متاح"} /></td></tr>)}</tbody></table></section>}</div>;
}
export function MarketingRequestsPage() {
  const { meta } = useMarketing(); const [rows, setRows] = useState<PhotoRequest[]>([]); const [search, setSearch] = useState(""); const [message, setMessage] = useState("");
  async function load() { const result = await marketingFetch<{ ok: true; rows: PhotoRequest[] }>(`/api/marketing?resource=photo_requests&search=${encodeURIComponent(search)}`); setRows(result.rows); }
  useEffect(() => { const timer = window.setTimeout(() => void load().catch((error) => setMessage(error.message)), 180); return () => window.clearTimeout(timer); }, [search]);
  async function update(id: string, status: string) { try { const result = await marketingFetch<{ ok: true; message: string }>("/api/marketing", { method: "POST", body: JSON.stringify({ action: "update_photo_request", id, status }) }); setMessage(result.message); await load(); } catch (failure) { setMessage(failure instanceof Error ? failure.message : "تعذر التحديث"); } }
  return <div className="module-page marketing-page"><MarketingPageHeader title="متابعة طلبات التصوير" description="نفس الطلب ونفس الحالة ظاهرة في التسويق والعمليات بدون نسخ منفصلة." /><section className="panel marketing-filter-bar"><MarketingSearch value={search} onChange={setSearch} placeholder="رقم الطلب أو VIN أو مقدم الطلب" /></section>{message ? <p className="marketing-form-message">{message}</p> : null}<div className="marketing-request-grid">{rows.map((row) => <article className="panel" key={row.id}><header><div><strong>{row.request_no}</strong><span>{row.requested_by_name} — {formatMarketingDate(row.requested_at, true)}</span></div><MarketingBadge value={statusLabel(row.status)} /></header><div className="marketing-request-vehicles">{row.vehicles.map((vehicle) => <span key={vehicle.vehicle_id}><b>{vehicle.car_name || vehicle.statement || "سيارة"}</b>{vehicle.vin} — {vehicle.location_name || "—"}</span>)}</div><p>موعد التصوير: {formatMarketingDate(row.photography_date)} — {row.note || "بدون ملاحظة"}</p>{meta.permissions["marketing.photo_request.manage"] ? <footer><select value={row.status} onChange={(event) => void update(row.id, event.target.value)}>{meta.requestStatuses.filter((item) => item.is_active).map((item) => <option key={item.code} value={item.code}>{item.name}</option>)}</select></footer> : null}{row.events?.length ? <div className="marketing-request-events"><strong>سجل المتابعة</strong>{row.events.slice(0, 5).map((item) => <span key={item.id}><b>{meta.requestStatuses.find((statusItem) => statusItem.code === item.status)?.name || statusLabel(item.status)}</b>{item.actor_name || "النظام"} — {formatMarketingDate(item.created_at, true)}{item.note ? ` — ${item.note}` : ""}</span>)}</div> : null}</article>)}</div></div>;
}

type CalendarResponse = { ok: true; month: string; tasks: Array<{ id: string; task_no: string; status: string; received_at: string; assigned_name?: string; project_name: string; campaign_code: string; instance_no?: string; creative_type?: string; department_name?: string; progress: number }>; publishSchedule: Array<{ id: string; publish_date: string; publish_time?: string; project_name: string; campaign_code: string; instance_no: string; creative_type: string; platform_name: string; post_type_name: string }> };
export function MarketingCalendarPage() {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const [data, setData] = useState<CalendarResponse | null>(null);
  useEffect(() => { void marketingFetch<CalendarResponse>(`/api/marketing?resource=calendar&month=${month}`).then(setData); }, [month]);
  const days = useMemo(() => { if (!data) return []; const map = new Map<string, { tasks: CalendarResponse["tasks"]; posts: CalendarResponse["publishSchedule"] }>(); data.tasks.forEach((row) => { const key = row.received_at.slice(0, 10); const current = map.get(key) || { tasks: [], posts: [] }; current.tasks.push(row); map.set(key, current); }); data.publishSchedule.forEach((row) => { const key = row.publish_date.slice(0, 10); const current = map.get(key) || { tasks: [], posts: [] }; current.posts.push(row); map.set(key, current); }); return [...map.entries()].sort(([a], [b]) => a.localeCompare(b)); }, [data]);
  return <div className="module-page marketing-page"><MarketingPageHeader title="تقويم التسويق" description="تاريخ التاسك هنا هو تاريخ الاستلام الفعلي، مع جدول النشر في نفس التقويم." actions={<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} />} />{!data ? <MarketingLoading /> : <div className="marketing-calendar-grid">{days.length ? days.map(([date, entries]) => <section className="panel" key={date}><header><CalendarBlank size={22} /><div><strong>{formatMarketingDate(date)}</strong><span>{entries.tasks.length} استلام — {entries.posts.length} نشر</span></div></header>{entries.tasks.map((row) => <article className="task" key={row.id}><strong>{row.task_no}</strong><span>{row.project_name} — {row.assigned_name || "—"}</span><MarketingBadge value={statusLabel(row.status)} /></article>)}{entries.posts.map((row) => <article className="post" key={row.id}><strong>{row.platform_name} — {row.post_type_name}</strong><span>{row.project_name} — {row.instance_no}</span><small>{row.publish_time || "—"}</small></article>)}</section>) : <MarketingEmpty title="لا توجد أحداث" description="لا توجد استلامات فعلية أو مواعيد نشر في هذا الشهر." />}</div>}</div>;
}

type ReportsResponse = { ok: true; summary: Record<string, number>; departments: Array<{ id: string; name: string; tasks: number; completed: number; delayed: number; progress: number }>; users: Array<{ id: string; full_name: string; department_name?: string; tasks: number; completed: number; delayed: number; progress: number; nearest_due?: string; last_received?: string }> };
export function MarketingReportsPage() {
  const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [data, setData] = useState<ReportsResponse | null>(null); const [error, setError] = useState("");
  async function load() { try { setData(await marketingFetch<ReportsResponse>(`/api/marketing${marketingQuery({ resource: "reports", from, to })}`)); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل التقارير"); } }
  useEffect(() => { void load(); }, []);
  return <div className="module-page marketing-page"><MarketingPageHeader title="تقارير التسويق" description="مؤشرات الحملات والأجندات والتاسكات والأقسام واليوزرات من قاعدة البيانات." actions={<button type="button" className="marketing-secondary-button" onClick={() => data && exportRows("marketing-report.csv", [["المستخدم","القسم","التاسكات","مكتمل","متأخر","التقدم"], ...data.users.map((row) => [row.full_name,row.department_name,row.tasks,row.completed,row.delayed,row.progress])])}>تصدير CSV</button>} /><section className="panel marketing-filter-bar"><label>من<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>إلى<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><button className="marketing-primary-button" type="button" onClick={() => void load()}>تطبيق</button></section>{error ? <MarketingError message={error} onRetry={() => void load()} /> : !data ? <MarketingLoading /> : <><div className="marketing-stats-grid"><MarketingStat label="المشاريع" value={data.summary.projects || 0} icon={CirclesFour} /><MarketingStat label="التاسكات" value={data.summary.tasks || 0} icon={ListChecks} /><MarketingStat label="المكتملة" value={data.summary.completed_tasks || 0} icon={CheckCircle} /><MarketingStat label="المتأخرة" value={data.summary.delayed_tasks || 0} icon={WarningCircle} /></div><div className="marketing-two-column reports"><section className="panel marketing-table-wrap"><h2>نتائج الأقسام</h2><table><thead><tr><th>القسم</th><th>التاسكات</th><th>مكتمل</th><th>متأخر</th><th>التقدم</th></tr></thead><tbody>{data.departments.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.tasks}</td><td>{row.completed}</td><td>{row.delayed}</td><td><ProgressBar value={row.progress} /></td></tr>)}</tbody></table></section><section className="panel marketing-table-wrap"><h2>نتائج اليوزرات</h2><table><thead><tr><th>المستخدم</th><th>القسم</th><th>التاسكات</th><th>مكتمل</th><th>متأخر</th><th>التقدم</th></tr></thead><tbody>{data.users.map((row) => <tr key={`${row.id}-${row.department_name}`}><td>{row.full_name}</td><td>{row.department_name || "—"}</td><td>{row.tasks}</td><td>{row.completed}</td><td>{row.delayed}</td><td><ProgressBar value={row.progress} /></td></tr>)}</tbody></table></section></div></>}</div>;
}

type AttendanceRow = { id: string; user_id: string; full_name: string; email?: string; attendance_date: string; check_in_at?: string; check_out_at?: string; status: string; late_minutes: number; work_minutes: number; last_seen_at?: string; last_page?: string };
type AttendanceResponse = { ok: true; settings: { work_start_time: string; work_end_time: string; grace_minutes: number }; todayRows: AttendanceRow[]; reportRows: AttendanceRow[]; myRecord: AttendanceRow | null };
export function MarketingAttendancePage() {
  const { meta } = useMarketing(); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [data, setData] = useState<AttendanceResponse | null>(null); const [message, setMessage] = useState("");
  async function load() { setData(await marketingFetch<AttendanceResponse>(`/api/marketing?resource=attendance&date=${date}&from=${date}&to=${date}`)); }
  useEffect(() => { void load(); }, [date]);
  async function action(attendanceAction: "check_in" | "check_out") { try { const result = await marketingFetch<{ ok: true; message: string }>("/api/marketing", { method: "POST", body: JSON.stringify({ action: "attendance_action", attendanceAction, deviceInfo: { userAgent: navigator.userAgent } }) }); setMessage(result.message); await load(); } catch (failure) { setMessage(failure instanceof Error ? failure.message : "تعذر التسجيل"); } }
  return <div className="module-page marketing-page"><MarketingPageHeader title="الحضور والانصراف" description={`الدوام ${data?.settings.work_start_time || meta.attendanceSettings?.work_start_time || "16:00"} إلى ${data?.settings.work_end_time || meta.attendanceSettings?.work_end_time || "21:00"} مع تسجيل الحضور من نفس دخول المنصة.`} actions={<div className="marketing-attendance-actions"><button type="button" className="marketing-primary-button" disabled={Boolean(data?.myRecord?.check_in_at)} onClick={() => void action("check_in")}><SignIn size={18} />تسجيل حضور</button><button type="button" className="marketing-secondary-button" disabled={!data?.myRecord?.check_in_at || Boolean(data?.myRecord?.check_out_at)} onClick={() => void action("check_out")}><SignOut size={18} />تسجيل انصراف</button></div>} />{message ? <p className="marketing-form-message">{message}</p> : null}<section className="panel marketing-filter-bar"><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></section>{!data ? <MarketingLoading /> : <section className="panel marketing-table-wrap"><table><thead><tr><th>المستخدم</th><th>التاريخ</th><th>الحضور</th><th>الانصراف</th><th>الحالة</th><th>التأخير</th><th>دقائق العمل</th><th>آخر نشاط</th></tr></thead><tbody>{data.reportRows.map((row) => <tr key={row.id}><td><strong>{row.full_name}</strong><small>{row.email || "—"}</small></td><td>{formatMarketingDate(row.attendance_date)}</td><td>{formatMarketingDate(row.check_in_at, true)}</td><td>{formatMarketingDate(row.check_out_at, true)}</td><td><MarketingBadge value={statusLabel(row.status)} /></td><td>{row.late_minutes || 0}</td><td>{row.work_minutes || 0}</td><td>{formatMarketingDate(row.last_seen_at, true)}</td></tr>)}</tbody></table></section>}</div>;
}

type ConnectionRow = { platform_id: string; code: string; name: string; connection_status?: string | null; account_name?: string | null; account_external_id?: string | null; token_status?: string | null; connected_at?: string | null; updated_at?: string | null };
export function MarketingConnectionsPage() {
  const { meta } = useMarketing(); const [rows, setRows] = useState<ConnectionRow[]>([]); const [message, setMessage] = useState("");
  async function load() { const result = await marketingFetch<{ ok: true; rows: ConnectionRow[] }>("/api/marketing?resource=connections"); setRows(result.rows); }
  useEffect(() => { void load(); }, []);
  async function save(row: ConnectionRow, connectionStatus: string) { try { const result = await marketingFetch<{ ok: true; message: string }>("/api/marketing", { method: "POST", body: JSON.stringify({ action: "save_connection", platformId: row.platform_id, connectionStatus, accountName: row.account_name, accountExternalId: row.account_external_id, tokenStatus: connectionStatus === "connected" ? "active" : "inactive" }) }); setMessage(result.message); await load(); } catch (failure) { setMessage(failure instanceof Error ? failure.message : "تعذر الحفظ"); } }
  return <div className="module-page marketing-page"><MarketingPageHeader title="ربط المنصات" description="إدارة حالة الحسابات والـOAuth مركزيًا بدون تخزين أسرار داخل الواجهة." />{message ? <p className="marketing-form-message">{message}</p> : null}<div className="marketing-connections-grid">{rows.map((row) => <article className="panel" key={row.platform_id}><header><LinkSimple size={28} weight="duotone" /><div><strong>{row.name}</strong><span>{row.code}</span></div><MarketingBadge value={row.connection_status === "connected" ? "connected" : "غير متصل"} /></header><Field label="اسم الحساب"><input disabled={!meta.permissions["marketing.connections.manage"]} value={row.account_name || ""} onChange={(event) => setRows((values) => values.map((item) => item.platform_id === row.platform_id ? { ...item, account_name: event.target.value } : item))} /></Field><Field label="Account ID"><input disabled={!meta.permissions["marketing.connections.manage"]} value={row.account_external_id || ""} onChange={(event) => setRows((values) => values.map((item) => item.platform_id === row.platform_id ? { ...item, account_external_id: event.target.value } : item))} /></Field><p>حالة التوكن: {row.token_status || "—"}</p><footer>{meta.permissions["marketing.connections.manage"] ? <><button type="button" className="marketing-primary-button" onClick={() => void save(row, "connected")}>حفظ كمتصل</button><button type="button" className="marketing-secondary-button" onClick={() => void save(row, "disconnected")}>فصل</button></> : null}</footer></article>)}</div></div>;
}
