import { useEffect, useState } from "react";
import { ArrowClockwise, LinkSimple, PencilSimple, Plus, Trash } from "@phosphor-icons/react";
import { marketingFetch, marketingPost } from "../api";
import { useMarketing } from "../MarketingContext";
import type { GenericRowsResponse } from "../types";
const text = (row: Record<string, unknown>, key: string) => String(row[key] ?? "");
const blank = () => ({ id: "", platformId: "", connectionName: "", accountLabel: "", status: "disconnected", clientId: "", accessToken: "" });

export function MarketingConnectionsPage() {
  const { meta } = useMarketing();
  const [rows, setRows] = useState<Array<Record<string, unknown>>>([]);
  const [form, setForm] = useState(blank);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const load = async () => { setError(""); try { const payload = await marketingFetch<GenericRowsResponse>("/api/marketing?action=connections"); setRows(payload.rows); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "تعذر تحميل ربط المنصات"); } };
  useEffect(() => { void load(); }, []);
  if (!meta) return null;
  const save = async () => { setError(""); setMessage(""); try { const result = await marketingPost<{ ok: true; message: string }>({ action: "save_connection", id: form.id, platformId: form.platformId, connectionName: form.connectionName, accountLabel: form.accountLabel, status: form.status, credentials: { clientId: form.clientId, accessToken: form.accessToken } }); setMessage(result.message); setForm(blank()); await load(); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "تعذر حفظ الربط"); } };
  const edit = (row: Record<string, unknown>) => setForm({ id: text(row, "id"), platformId: text(row, "platform_id"), connectionName: text(row, "connection_name"), accountLabel: text(row, "account_label"), status: text(row, "status") || "disconnected", clientId: "", accessToken: "" });
  const remove = async (id: string) => { if (!window.confirm("سيتم حذف ربط المنصة. هل أنت متأكد؟")) return; try { await marketingPost({ action: "delete_connection", id }); await load(); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "تعذر حذف الربط"); } };
  return <div className="marketing-page"><header className="marketing-page-title"><div><h2>ربط المنصات</h2><p>إدارة حسابات وربط منصات التسويق من داخل المنصة الموحدة.</p></div><div className="marketing-title-actions"><button onClick={() => void load()}><ArrowClockwise />تحديث</button></div></header>{error ? <div className="marketing-error">{error}</div> : null}{message ? <div className="marketing-success">{message}</div> : null}{meta.permissions.manageSettings ? <section className="connection-form panel"><h3><LinkSimple />{form.id ? "تعديل ربط منصة" : "إضافة ربط منصة"}</h3><div className="marketing-form-grid three"><label><span>المنصة</span><select value={form.platformId} onChange={(event) => setForm({ ...form, platformId: event.target.value })}><option value="">اختر المنصة</option>{meta.platforms.map((platform) => <option key={platform.id} value={platform.id}>{platform.name}</option>)}</select></label><label><span>اسم الربط</span><input value={form.connectionName} onChange={(event) => setForm({ ...form, connectionName: event.target.value })} /></label><label><span>اسم الحساب</span><input value={form.accountLabel} onChange={(event) => setForm({ ...form, accountLabel: event.target.value })} /></label><label><span>الحالة</span><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="connected">متصل</option><option value="disconnected">غير متصل</option><option value="pending">قيد المراجعة</option></select></label><label><span>Client ID</span><input value={form.clientId} onChange={(event) => setForm({ ...form, clientId: event.target.value })} /></label><label><span>Access Token</span><input type="password" value={form.accessToken} onChange={(event) => setForm({ ...form, accessToken: event.target.value })} /></label></div><div className="marketing-modal-actions"><button className="primary" disabled={!form.platformId || !form.connectionName} onClick={() => void save()}>{form.id ? <PencilSimple /> : <Plus />}{form.id ? "حفظ التعديل" : "إضافة الربط"}</button>{form.id ? <button onClick={() => setForm(blank())}>إلغاء</button> : null}</div></section> : null}<section className="connection-cards">{rows.map((row) => <article key={text(row, "id")}><header><LinkSimple /><div><h3>{text(row, "platform_name")}</h3><span>{text(row, "connection_name")}</span></div><b className={`connection-${text(row, "status")}`}>{text(row, "status")}</b></header><p>{text(row, "account_label") || "لا يوجد اسم حساب"}</p>{meta.permissions.manageSettings ? <footer><button onClick={() => edit(row)}><PencilSimple />تعديل</button><button className="danger" onClick={() => void remove(text(row, "id"))}><Trash />حذف</button></footer> : null}</article>)}</section>{!rows.length ? <div className="marketing-empty">لا توجد حسابات منصات مربوطة.</div> : null}</div>;
}
