import { useEffect, useMemo, useState } from "react";
import { ArrowClockwise, FilePdf, PencilSimple, Plus, Trash } from "@phosphor-icons/react";
import { marketingFetch, marketingQuery } from "../api";
import { MarketingAlert, MarketingPage } from "../components/MarketingPage";

const categories = ["العناية", "الفضية", "الذهبية", "VIP"];
const empty = { id: "", name: "", category: "العناية", price: 0, cashDiscount: 0, registrationFees: false, insurance: false, issuanceFees: false, careText: "", deliveryHome: false, deliveryRegion: false };

export function PackagesPage() {
  const [rows, setRows] = useState<any[]>([]);
  const [form, setForm] = useState(empty);
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("");
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  async function load() { try { const payload = await marketingFetch<{ rows: any[] }>(`/api/marketing${marketingQuery({ resource: "packages" })}`); setRows(payload.rows); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل الباقات"); } }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => rows.filter((row) => (!category || row.category === category) && `${row.name} ${row.category}`.toLowerCase().includes(search.toLowerCase())), [rows, search, category]);
  async function save() { setError(""); try { const result = await marketingFetch<{ message: string }>("/api/marketing", { method: "POST", body: JSON.stringify({ action: "save_package", ...form, careFeatures: form.careText.split("\n").map((item) => item.trim()).filter(Boolean) }) }); setMessage(result.message); setForm(empty); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر حفظ الباقة"); } }
  function edit(row: any) { setForm({ id: row.id, name: row.name, category: row.category, price: Number(row.price), cashDiscount: Number(row.cash_discount), registrationFees: row.registration_fees, insurance: row.insurance, issuanceFees: row.issuance_fees, careText: Array.isArray(row.care_features) ? row.care_features.join("\n") : "", deliveryHome: row.delivery_home, deliveryRegion: row.delivery_region }); }
  async function remove(id: string) { if (!window.confirm("تأكيد حذف الباقة؟")) return; try { await marketingFetch("/api/marketing", { method: "POST", body: JSON.stringify({ action: "delete_setting", entity: "package", id }) }); setForm(empty); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر حذف الباقة"); } }
  return <MarketingPage title="إدارة الباقات" description="إنشاء باقة أو تعديلها أو حذفها حسب التصنيف." actions={<div className="marketing-inline-actions"><input className="marketing-search" placeholder="بحث عن باقة" value={search} onChange={(event) => setSearch(event.target.value)} /><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">كل التصنيفات</option>{categories.map((item) => <option key={item}>{item}</option>)}</select><button type="button" className="secondary" onClick={() => window.print()}><FilePdf size={17} />تصدير PDF</button><button type="button" className="secondary" onClick={() => void load()}><ArrowClockwise size={17} />تحديث</button></div>}>
    {error ? <MarketingAlert>{error}</MarketingAlert> : null}{message ? <MarketingAlert type="success">{message}</MarketingAlert> : null}
    <div className="marketing-packages-layout"><section className="panel marketing-package-form"><h2>{form.id ? "تعديل الباقة" : "إنشاء باقة"}</h2><div className="marketing-form-grid"><label><span>اسم الباقة</span><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label><span>التصنيف</span><select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>قيمة الباقة (ر.س)</span><input type="number" min={0} value={form.price} onChange={(event) => setForm({ ...form, price: Number(event.target.value) || 0 })} /></label><label><span>خصم نقدي (%)</span><input type="number" min={0} max={100} value={form.cashDiscount} onChange={(event) => setForm({ ...form, cashDiscount: Number(event.target.value) || 0 })} /></label></div><div className="marketing-check-grid"><label><input type="checkbox" checked={form.registrationFees} onChange={(event) => setForm({ ...form, registrationFees: event.target.checked })} />رسوم التسجيل</label><label><input type="checkbox" checked={form.insurance} onChange={(event) => setForm({ ...form, insurance: event.target.checked })} />التأمين</label><label><input type="checkbox" checked={form.issuanceFees} onChange={(event) => setForm({ ...form, issuanceFees: event.target.checked })} />رسوم الإصدار</label></div><label><span>العناية بالسيارة — كل ميزة في سطر</span><textarea rows={7} value={form.careText} onChange={(event) => setForm({ ...form, careText: event.target.value })} /></label><div className="marketing-check-grid"><label><input type="checkbox" checked={form.deliveryHome} onChange={(event) => setForm({ ...form, deliveryHome: event.target.checked })} />إلى باب البيت</label><label><input type="checkbox" checked={form.deliveryRegion} onChange={(event) => setForm({ ...form, deliveryRegion: event.target.checked })} />إلى المنطقة</label></div><div className="marketing-inline-actions"><button type="button" className="primary" onClick={() => void save()}>{form.id ? <PencilSimple size={17} /> : <Plus size={17} />}{form.id ? "تعديل الباقة" : "إنشاء باقة"}</button>{form.id ? <button type="button" className="secondary" onClick={() => setForm(empty)}>إلغاء التعديل</button> : null}</div></section>
    <section className="marketing-package-cards">{filtered.map((row) => <article key={row.id} className={`marketing-package-card category-${categories.indexOf(row.category)}`}><span>{row.category}</span><h3>{row.name}</h3><strong>{Number(row.price).toLocaleString("ar-SA")} <small>ر.س</small></strong><p>خصم نقدي {Number(row.cash_discount).toLocaleString("ar-SA")}%</p><ul>{row.registration_fees ? <li>رسوم التسجيل</li> : null}{row.insurance ? <li>التأمين</li> : null}{row.issuance_fees ? <li>رسوم الإصدار</li> : null}{Array.isArray(row.care_features) ? row.care_features.map((item: string) => <li key={item}>{item}</li>) : null}</ul><footer><button type="button" onClick={() => edit(row)}><PencilSimple size={16} />تعديل</button><button type="button" className="danger" onClick={() => void remove(row.id)}><Trash size={16} />حذف</button></footer></article>)}{!filtered.length ? <div className="marketing-empty">لا توجد باقات.</div> : null}</section></div>
  </MarketingPage>;
}
