import { useEffect, useState } from "react";
import { CheckCircle, FacebookLogo, InstagramLogo, LinkBreak, LinkSimple, ShieldCheck } from "@phosphor-icons/react";
import { marketingFetch, marketingQuery } from "../api";
import { MarketingAlert, MarketingPage } from "../components/MarketingPage";

const blank = { platform: "facebook", accountId: "", accountName: "", pageId: "", pageName: "", igUserId: "", username: "", accessToken: "", userAccessToken: "", pageAccessToken: "", connected: true };
export function PlatformConnectionsPage() {
  const [connections, setConnections] = useState<any[]>([]);
  const [form, setForm] = useState(blank);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);
  async function load() { try { const payload = await marketingFetch<{ connections: any[] }>(`/api/marketing${marketingQuery({ resource: "platform_connections" })}`); setConnections(payload.connections); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل ربط المنصات"); } }
  useEffect(() => { void load(); }, []);
  function select(platform: "facebook" | "instagram") { const current = connections.find((item) => item.platform === platform); setForm({ ...blank, platform, accountId: current?.accountId || "", accountName: current?.accountName || "", pageId: current?.pageId || "", pageName: current?.pageName || "", igUserId: current?.igUserId || "", username: current?.username || "", connected: current?.connected ?? true }); }
  async function save() { setLoading(true); setError(""); try { const result = await marketingFetch<{ message: string }>("/api/marketing", { method: "POST", body: JSON.stringify({ action: "save_connection", ...form }) }); setMessage(result.message); setForm({ ...blank, platform: form.platform }); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر حفظ الربط"); } finally { setLoading(false); } }
  async function disconnect(platform: string) { if (!window.confirm("تأكيد فصل الربط؟")) return; try { const result = await marketingFetch<{ message: string }>("/api/marketing", { method: "POST", body: JSON.stringify({ action: "disconnect_connection", platform }) }); setMessage(result.message); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر فصل الربط"); } }
  async function migrate() { setLoading(true); setError(""); try { const result = await marketingFetch<{ message: string }>("/api/marketing", { method: "POST", body: JSON.stringify({ action: "migrate_connection_env" }) }); setMessage(result.message); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر نقل التوكنات الحالية"); } finally { setLoading(false); } }
  return <MarketingPage title="ربط المنصات" description="ربط Facebook وInstagram وحفظ التوكنات الحالية داخل PostgreSQL بشكل مشفر." actions={<button type="button" className="secondary" onClick={() => void migrate()} disabled={loading}><ShieldCheck size={17} />نقل التوكنات الحالية</button>}>
    {error ? <MarketingAlert>{error}</MarketingAlert> : null}{message ? <MarketingAlert type="success">{message}</MarketingAlert> : null}
    <div className="marketing-connections-grid">{(["facebook", "instagram"] as const).map((platform) => { const current = connections.find((item) => item.platform === platform); const Icon = platform === "facebook" ? FacebookLogo : InstagramLogo; return <article key={platform} className={`marketing-connection-card ${current?.connected ? "connected" : ""}`}><header><Icon size={32} weight="duotone" /><div><h2>{platform === "facebook" ? "Facebook" : "Instagram"}</h2><span>{current?.connected ? <><CheckCircle size={15} weight="fill" />متصل</> : "غير متصل"}</span></div></header><div className="marketing-connection-data"><p><small>اسم الحساب</small><strong>{current?.accountName || "—"}</strong></p><p><small>{platform === "facebook" ? "اسم الصفحة" : "username"}</small><strong>{platform === "facebook" ? current?.pageName || "—" : current?.username || "—"}</strong></p><p><small>رقم الصفحة</small><strong dir="ltr">{current?.pageId || "—"}</strong></p>{platform === "instagram" ? <p><small>Instagram Business Account</small><strong dir="ltr">{current?.igUserId || "—"}</strong></p> : null}<p><small>التوكن</small><strong>{current?.tokenStored ? "محفوظ ومشفر" : "غير محفوظ"}</strong></p><p><small>آخر تحديث</small><strong>{current?.updatedAtIso ? new Date(current.updatedAtIso).toLocaleString("ar-SA") : "—"}</strong></p></div><footer><button type="button" className="primary" onClick={() => select(platform)}><LinkSimple size={17} />{current?.connected ? "إعادة ربط" : "ربط"}</button>{current?.connected ? <button type="button" className="danger" onClick={() => void disconnect(platform)}><LinkBreak size={17} />فصل الربط</button> : null}</footer></article>; })}</div>
    <section className="panel marketing-connection-form"><h2>{form.platform === "facebook" ? "Facebook" : "Instagram"}</h2><div className="marketing-form-grid"><label><span>accountId</span><input dir="ltr" value={form.accountId} onChange={(event) => setForm({ ...form, accountId: event.target.value })} /></label><label><span>accountName</span><input value={form.accountName} onChange={(event) => setForm({ ...form, accountName: event.target.value })} /></label><label><span>pageId</span><input dir="ltr" value={form.pageId} onChange={(event) => setForm({ ...form, pageId: event.target.value })} /></label><label><span>pageName</span><input value={form.pageName} onChange={(event) => setForm({ ...form, pageName: event.target.value })} /></label>{form.platform === "instagram" ? <><label><span>igUserId</span><input dir="ltr" value={form.igUserId} onChange={(event) => setForm({ ...form, igUserId: event.target.value })} /></label><label><span>username</span><input dir="ltr" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /></label></> : null}<label className="full"><span>accessToken</span><input type="password" dir="ltr" value={form.accessToken} onChange={(event) => setForm({ ...form, accessToken: event.target.value })} /></label><label className="full"><span>userAccessToken</span><input type="password" dir="ltr" value={form.userAccessToken} onChange={(event) => setForm({ ...form, userAccessToken: event.target.value })} /></label>{form.platform === "instagram" ? <label className="full"><span>pageAccessToken</span><input type="password" dir="ltr" value={form.pageAccessToken} onChange={(event) => setForm({ ...form, pageAccessToken: event.target.value })} /></label> : null}</div><button type="button" className="primary" onClick={() => void save()} disabled={loading}><ShieldCheck size={17} />حفظ الربط داخل PostgreSQL</button></section>
  </MarketingPage>;
}
