import { useEffect, useMemo, useState } from "react";
import { CaretLeft, CaretRight } from "@phosphor-icons/react";
import { marketingFetch, queryString } from "../api";
import { DepartmentBadge, MarketingAlert, MarketingLoading, MarketingModal, MarketingPageHeader, ProgressBar, StatusBadge } from "../components/Ui";
import { MonthCalendar, type CalendarEntry } from "../components/MonthCalendar";
import { TaskDetailView } from "../components/TaskDetailView";

type Row = { id: string; due_date: string; task_code: string; task_type: string; status: string; progress_percent: number; department_code: string; department_name: string; campaign_code: string; campaign_name: string; creative_name: string; instance_code: string; assigned_to_name: string; content_user_name: string };
function shift(month: string, amount: number) { const [y, m] = month.split("-").map(Number); const d = new Date(y, m - 1 + amount, 1); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`; }
export function ReceiptCalendarPage() {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const [rows, setRows] = useState<Row[]>([]); const [selected, setSelected] = useState<CalendarEntry | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const payload = await marketingFetch<{ rows: Row[] }>(`/api/marketing?${queryString({ resource: "receipt_calendar", month })}`); setRows(payload.rows); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل تقويم الاستلام"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [month]);
  const entries = useMemo<CalendarEntry[]>(() => rows.map((row) => ({ id: row.id, date: row.due_date, title: `${row.campaign_code} · ${row.creative_name}`, subtitle: `${row.department_name || row.department_code} · ${row.assigned_to_name}`, status: row.status, raw: row })), [rows]);
  const details = selected?.raw as Row | undefined;
  return <div className="marketing-page"><MarketingPageHeader title="تقويم الاستلام" description="مواعيد استلام مهام المحتوى والتنفيذ، منفصلة تمامًا عن مواعيد النشر." />{error ? <MarketingAlert>{error}</MarketingAlert> : null}<section className="marketing-panel"><div className="marketing-calendar-toolbar"><button className="marketing-button" onClick={() => setMonth(shift(month, -1))}><CaretRight />السابق</button><strong>{new Intl.DateTimeFormat("ar-SA", { month: "long", year: "numeric" }).format(new Date(`${month}-01T12:00:00`))}</strong><div><button className="marketing-button small secondary" onClick={() => setMonth(new Date().toISOString().slice(0, 7))}>اليوم</button><button className="marketing-button" onClick={() => setMonth(shift(month, 1))}>التالي<CaretLeft /></button></div></div></section>{loading ? <MarketingLoading /> : <MonthCalendar month={month} entries={entries} onEntry={setSelected} />}<MarketingModal open={Boolean(selected)} title={details ? `${details.task_code} — ${details.creative_name}` : "تفاصيل موعد الاستلام"} subtitle={details ? `${details.campaign_code} · ${details.campaign_name}` : undefined} onClose={() => setSelected(null)} wide>{details ? <div className="marketing-stack"><div className="marketing-review-kv"><div><small>القسم</small><DepartmentBadge code={details.department_code} /></div><div><small>المسؤول</small><strong>{details.assigned_to_name}</strong></div><div><small>كاتب المحتوى</small><strong>{details.content_user_name || "—"}</strong></div><div><small>الحالة</small><StatusBadge status={details.status} /></div></div><ProgressBar value={details.progress_percent} /><TaskDetailView taskId={details.id} onChanged={load} /></div> : null}</MarketingModal></div>;
}
