import { useEffect, useState } from "react";
import { DownloadSimple } from "@phosphor-icons/react";
import { marketingFetch, marketingQuery } from "../api";
import { MarketingPageHeader } from "../components/MarketingPageHeader";
import { MarketingLoading, MarketingError } from "../components/MarketingLoading";
import { MarketingStatusBadge } from "../components/MarketingStatusBadge";

function csv(rows:any[]){const headers=["الكود","الاسم","النوع","الحالة","التقدم","الكرييتيفات","المهام","المنشور"];const lines=rows.map(r=>[r.campaign_code,r.name,r.source_type,r.status,r.progress_percent,r.creative_count,r.task_count,r.published_target_count].map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(","));const blob=new Blob(["\uFEFF"+headers.join(",")+"\n"+lines.join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="marketing-reports.csv";a.click();URL.revokeObjectURL(a.href);}
export function ReportsPage(){const[rows,setRows]=useState<any[]>([]);const[from,setFrom]=useState("");const[to,setTo]=useState("");const[query,setQuery]=useState({from:"",to:""});const[loading,setLoading]=useState(true);const[error,setError]=useState("");async function load(){setLoading(true);setError("");try{const r=await marketingFetch<any>(marketingQuery({resource:"reports",...query}));setRows(r.rows);}catch(f){setError(f instanceof Error?f.message:"تعذر تحميل التقارير");}finally{setLoading(false)}}useEffect(()=>{void load()},[query]);if(loading&&!rows.length)return <MarketingLoading/>;return <div className="marketing-page"><MarketingPageHeader title="قاعدة بيانات وتقارير التسويق" description="نفس معادلة التقدم المستخدمة في لوحة التحكم والمهام." actions={<button className="marketing-button secondary" onClick={()=>csv(rows)}><DownloadSimple size={18}/>تصدير CSV</button>}/><form className="marketing-filter-bar" onSubmit={e=>{e.preventDefault();setQuery({from,to})}}><label><span>من</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label><span>إلى</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="marketing-button compact">تطبيق</button></form>{error?<MarketingError message={error}/>:null}<section className="marketing-panel"><div className="marketing-table-wrap"><table className="marketing-table"><thead><tr><th>الحملة</th><th>النوع</th><th>الحالة</th><th>الكرييتيفات</th><th>المهام</th><th>التقدم</th><th>عناصر النشر</th><th>تم النشر</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.campaign_code}</small></td><td>{r.source_type==="agenda"?"أجندة":"حملة"}</td><td><MarketingStatusBadge status={r.status}/></td><td>{r.creative_count}</td><td>{r.completed_task_count}/{r.task_count}</td><td>{r.progress_percent}%</td><td>{r.publish_item_count}</td><td>{r.published_target_count}</td></tr>)}</tbody></table></div></section></div>}
