import { useCallback, useEffect, useState } from "react";
import { Camera, MagnifyingGlass, Trash } from "@phosphor-icons/react";
import { marketingFetch, marketingQuery, todayIso } from "../api";
import type { VehicleRow } from "../types";
import { Alert, ConfirmButton, Empty, Modal, PageHead } from "../components/Ui";

type Response = { ok: boolean; rows: VehicleRow[] };
export function MarketingStockPage() {
  const [rows, setRows] = useState<VehicleRow[]>([]); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<VehicleRow[]>([]); const [date, setDate] = useState(todayIso()); const [note, setNote] = useState(""); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const data = await marketingFetch<Response>(`/api/marketing${marketingQuery({ resource: "stock", search })}`); setRows(data.rows); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل الاستوك"); } }, [search]); useEffect(() => { void load(); }, [load]);
  function toggle(row: VehicleRow) { setSelected((current) => current.some((item) => item.id === row.id) ? current.filter((item) => item.id !== row.id) : [...current, row]); }
  async function create() { if (!selected.length) return; setBusy(true); setError(""); try { await marketingFetch("/api/marketing", { method: "POST", body: JSON.stringify({ action: "create_photo_request", vehicleIds: selected.map((item) => item.id), photographyDate: date, note }) }); setMessage("تم إنشاء طلب التصوير في التسويق والعمليات من نفس السجل."); setSelected([]); setOpen(false); setNote(""); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر إنشاء طلب التصوير"); } finally { setBusy(false); } }
  return <div className="marketing-page"><PageHead title="الاستوك" description="قراءة مخزن السيارات من نظام العمليات وإنشاء طلب تصوير مشترك." actions={<ConfirmButton onClick={() => setOpen(true)} disabled={!selected.length}><Camera size={18} />إنشاء طلب تصوير ({selected.length})</ConfirmButton>} />{error ? <Alert type="error">{error}</Alert> : null}{message ? <Alert type="success">{message}</Alert> : null}<section className="marketing-filter-bar"><label><MagnifyingGlass size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ابحث برقم الهيكل أو السيارة" /></label></section><section className="marketing-table-card"><div className="marketing-table-wrap"><table className="marketing-table"><thead><tr><th></th><th>الهيكل VIN</th><th>السيارة</th><th>البيان</th><th>اللون الداخلي</th><th>اللون الخارجي</th><th>الموديل</th><th>المكان</th><th>الحالة</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className={selected.some((item) => item.id === row.id) ? "selected" : ""}><td><input type="checkbox" checked={selected.some((item) => item.id === row.id)} onChange={() => toggle(row)} /></td><td><button className="marketing-vin-button" type="button" onClick={() => { if (!selected.some((item) => item.id === row.id)) setSelected([...selected, row]); setOpen(true); }}>{row.vin}</button></td><td>{row.car_name || "—"}</td><td>{row.statement || "—"}</td><td>{row.interior_color || "—"}</td><td>{row.exterior_color || "—"}</td><td>{row.model_year || "—"}</td><td>{row.location_name || "—"}</td><td>{row.status_name || row.status_code || "—"}</td></tr>)}</tbody></table></div>{!rows.length ? <Empty text="لا توجد سيارات مطابقة." /> : null}</section><Modal open={open} title="إنشاء طلب تصوير" subtitle="نفس موديول الطلبات المشترك مع نظام العمليات" onClose={() => setOpen(false)} wide><div className="marketing-photo-request"><div className="marketing-table-wrap"><table className="marketing-table"><thead><tr><th>رقم الهيكل</th><th>السيارة</th><th>المكان الحالي</th><th></th></tr></thead><tbody>{selected.map((row) => <tr key={row.id}><td>{row.vin}</td><td>{row.car_name || row.statement || "—"}</td><td>{row.location_name || "—"}</td><td><button type="button" onClick={() => toggle(row)}><Trash size={16} /></button></td></tr>)}</tbody></table></div><label><span>تاريخ التصوير</span><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label><span>ملاحظات الطلب</span><textarea rows={5} value={note} onChange={(event) => setNote(event.target.value)} placeholder="ملاحظة اختيارية على طلب التصوير" /></label><ConfirmButton onClick={() => void create()} disabled={busy || !selected.length}>{busy ? "جاري الإنشاء..." : "إنشاء طلب تصوير"}</ConfirmButton></div></Modal></div>;
}
