import { useEffect, useState } from "react";
import { FloppyDisk, Megaphone, Plus, WarningCircle } from "@phosphor-icons/react";
import { marketingFetch, marketingMutation } from "../api";
import type { CreativeTypeSetting, PlatformSetting } from "../types";
import { DEPARTMENT_LABELS } from "../utils";

type SettingsData = { ok: true; creativeTypes: CreativeTypeSetting[]; platforms: PlatformSetting[] };
const blankCreative = { code: "", name: "", departmentCodes: ["content"], isActive: true, sortOrder: 0 };
const blankPlatform = { code: "", name: "", postTypes: "", connectionStatus: "غير مربوط", isActive: true, sortOrder: 0 };

export function MarketingSettingsPanel() {
  const [data, setData] = useState<SettingsData | null>(null);
  const [creative, setCreative] = useState(blankCreative);
  const [platform, setPlatform] = useState(blankPlatform);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");

  async function load() { setError(""); try { setData(await marketingFetch<SettingsData>("/api/marketing?resource=settings")); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر تحميل إعدادات التسويق"); } }
  useEffect(() => { void load(); }, []);
  function toggleDepartment(code: string) { setCreative((current) => ({ ...current, departmentCodes: current.departmentCodes.includes(code) ? current.departmentCodes.filter((item) => item !== code || item === "content") : [...current.departmentCodes, code] })); }
  async function saveCreative(event: React.FormEvent) { event.preventDefault(); setError(""); try { await marketingMutation("settings", "PUT", { kind: "creative_type", ...creative }); setCreative(blankCreative); setMessage("تم حفظ نوع الكرييتيف"); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر الحفظ"); } }
  async function savePlatform(event: React.FormEvent) { event.preventDefault(); setError(""); try { await marketingMutation("settings", "PUT", { kind: "platform", ...platform, postTypes: platform.postTypes.split(/[,،\n]/).map((item) => item.trim()).filter(Boolean) }); setPlatform(blankPlatform); setMessage("تم حفظ إعداد المنصة"); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر الحفظ"); } }

  return <div className="marketing-settings-wrap">
    <section className="panel marketing-settings-hero"><Megaphone size={42} weight="duotone"/><div><h2>إعدادات التسويق</h2><p>أنواع الكرييتيف وربط الأقسام ومنصات النشر من صفحة الإعدادات الموحدة.</p></div></section>
    {error?<div className="connection-banner"><WarningCircle size={20}/><span>{error}</span></div>:null}{message?<div className="success-banner">{message}</div>:null}
    <div className="marketing-settings-grid"><section className="panel marketing-settings-card"><header><h2>أنواع الكرييتيف</h2><span>{data?.creativeTypes.length??"—"}</span></header><form onSubmit={saveCreative}><div className="marketing-form-row"><label><span>الكود</span><input required value={creative.code} onChange={(e)=>setCreative({...creative,code:e.target.value.toUpperCase()})}/></label><label><span>الاسم</span><input required value={creative.name} onChange={(e)=>setCreative({...creative,name:e.target.value})}/></label></div><div className="marketing-settings-checks">{Object.entries(DEPARTMENT_LABELS).map(([code,label])=><label key={code}><input type="checkbox" disabled={code==='content'} checked={creative.departmentCodes.includes(code)} onChange={()=>toggleDepartment(code)}/>{label}</label>)}</div><div className="marketing-form-row"><label><span>الترتيب</span><input type="number" value={creative.sortOrder} onChange={(e)=>setCreative({...creative,sortOrder:Number(e.target.value)})}/></label><label><span>الحالة</span><select value={creative.isActive?'1':'0'} onChange={(e)=>setCreative({...creative,isActive:e.target.value==='1'})}><option value="1">نشط</option><option value="0">موقوف</option></select></label></div><button className="marketing-primary-button"><Plus size={16}/>حفظ النوع</button></form><div className="marketing-settings-list">{data?.creativeTypes.map((item)=><button key={item.code} onClick={()=>setCreative({code:item.code,name:item.name,departmentCodes:item.department_codes,isActive:item.is_active,sortOrder:item.sort_order})}><div><b>{item.name}</b><span>{item.code}</span></div><small>{item.department_codes.map((code)=>DEPARTMENT_LABELS[code]||code).join(' + ')}</small></button>)}</div></section>
    <section className="panel marketing-settings-card"><header><h2>منصات النشر</h2><span>{data?.platforms.length??"—"}</span></header><form onSubmit={savePlatform}><div className="marketing-form-row"><label><span>الكود</span><input required value={platform.code} onChange={(e)=>setPlatform({...platform,code:e.target.value.toLowerCase()})}/></label><label><span>الاسم</span><input required value={platform.name} onChange={(e)=>setPlatform({...platform,name:e.target.value})}/></label></div><label><span>أنواع النشر</span><textarea value={platform.postTypes} onChange={(e)=>setPlatform({...platform,postTypes:e.target.value})} placeholder="Post, Reel, Story"/></label><label><span>حالة الربط</span><input value={platform.connectionStatus} onChange={(e)=>setPlatform({...platform,connectionStatus:e.target.value})}/></label><div className="marketing-form-row"><label><span>الترتيب</span><input type="number" value={platform.sortOrder} onChange={(e)=>setPlatform({...platform,sortOrder:Number(e.target.value)})}/></label><label><span>الحالة</span><select value={platform.isActive?'1':'0'} onChange={(e)=>setPlatform({...platform,isActive:e.target.value==='1'})}><option value="1">نشط</option><option value="0">موقوف</option></select></label></div><button className="marketing-primary-button"><FloppyDisk size={16}/>حفظ المنصة</button></form><div className="marketing-settings-list">{data?.platforms.map((item)=><button key={item.code} onClick={()=>setPlatform({code:item.code,name:item.name,postTypes:item.post_types.join(', '),connectionStatus:item.connection_status,isActive:item.is_active,sortOrder:item.sort_order})}><div><b>{item.name}</b><span>{item.code}</span></div><small>{item.connection_status}</small></button>)}</div></section></div>
  </div>;
}
