import { useMemo, useState } from "react";
import { Buildings, CheckCircle, Gear, Gift, Megaphone, PencilSimple, Plus, Stack, Trash, UsersThree } from "@phosphor-icons/react";
import { marketingPost } from "../api";
import { MarketingProvider, useMarketing } from "../MarketingContext";
import type { MarketingAction, MarketingDepartment, MarketingPlatform, MarketingPublishType } from "../types";

type Tab = "departments" | "actions" | "creatives" | "campaignTypes" | "platforms" | "categories" | "statuses";
const tabs: Array<{ key: Tab; label: string }> = [
  { key: "departments", label: "الأقسام" },
  { key: "actions", label: "إجراءات التكليف" },
  { key: "creatives", label: "الكرييتيفات" },
  { key: "campaignTypes", label: "أنواع الحملات" },
  { key: "platforms", label: "المنصات وأنواع النشر" },
  { key: "categories", label: "تصنيفات الباقات" },
  { key: "statuses", label: "حالات الطلب" },
];

type BasicForm = { id: string; name: string; code: string; sortOrder: number; isActive: boolean };
const basic = (): BasicForm => ({ id: "", name: "", code: "", sortOrder: 10, isActive: true });

function MarketingSettingsPanelContent() {
  const { meta, refreshMeta } = useMarketing();
  const [tab, setTab] = useState<Tab>("departments");
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [working, setWorking] = useState(false);
  const [department, setDepartment] = useState({ ...basic(), isContent: false, userIds: [] as string[] });
  const [action, setAction] = useState({ ...basic(), departmentId: "", progressWeight: 0, adminOnly: false });
  const [creative, setCreative] = useState({ ...basic(), shortCode: "", primaryDepartmentId: "" });
  const [campaignType, setCampaignType] = useState({ ...basic(), prefix: "MZJ" });
  const [platform, setPlatform] = useState({ ...basic(), publishTypes: [] as Array<{ id?: string; name: string; dimensions: string; isActive: boolean; sortOrder: number }> });
  const [category, setCategory] = useState(basic);
  const [requestStatus, setRequestStatus] = useState(basic);

  const allActions = useMemo(() => (meta?.departments || []).flatMap((row) => row.actions), [meta]);
  if (!meta) return <div className="marketing-loading">جاري تحميل إعدادات التسويق...</div>;
  if (!meta.permissions.manageSettings) return <div className="marketing-error">لا تملك صلاحية إدارة إعدادات التسويق.</div>;

  const run = async (body: Record<string, unknown>, reset: () => void) => {
    setWorking(true); setError(""); setMessage("");
    try { const result = await marketingPost<{ ok: true; message: string }>(body); setMessage(result.message); reset(); await refreshMeta(); }
    catch (actionError) { setError(actionError instanceof Error ? actionError.message : "تعذر حفظ الإعداد"); }
    finally { setWorking(false); }
  };
  const disable = async (entity: string, id: string) => {
    if (!window.confirm("سيتم تعطيل السجل من القوائم المستخدمة داخل التسويق. هل أنت متأكد؟")) return;
    await run({ action: "disable_setting", entity, id }, () => undefined);
  };

  const resetDepartment = () => setDepartment({ ...basic(), isContent: false, userIds: [] });
  const resetAction = () => setAction({ ...basic(), departmentId: "", progressWeight: 0, adminOnly: false });
  const resetCreative = () => setCreative({ ...basic(), shortCode: "", primaryDepartmentId: "" });
  const resetCampaignType = () => setCampaignType({ ...basic(), prefix: "MZJ" });
  const resetPlatform = () => setPlatform({ ...basic(), publishTypes: [] });

  const editDepartment = (row: MarketingDepartment) => setDepartment({ id: row.id, name: row.name, code: row.code, sortOrder: row.sort_order, isActive: row.is_active, isContent: row.is_content, userIds: row.users.map((item) => item.user_id) });
  const editAction = (row: MarketingAction) => setAction({ id: row.id, name: row.name, code: row.code, sortOrder: row.sort_order, isActive: row.is_active, departmentId: row.department_id, progressWeight: row.progress_weight, adminOnly: row.admin_only });
  const editPlatform = (row: MarketingPlatform) => setPlatform({ id: row.id, name: row.name, code: row.code, sortOrder: row.sort_order, isActive: row.is_active, publishTypes: row.publishTypes.map((type: MarketingPublishType) => ({ id: type.id, name: type.name, dimensions: type.dimensions || "", isActive: type.is_active, sortOrder: type.sort_order })) });

  return <section className="marketing-settings-panel" dir="rtl">
    <header className="marketing-settings-head"><div><span><Gear /></span><div><h2>إعدادات التسويق</h2><p>المصدر المركزي للأقسام والكرييتيفات والإجراءات والمنصات والقوائم المنسدلة.</p></div></div></header>
    {error ? <div className="marketing-error">{error}</div> : null}{message ? <div className="marketing-success">{message}</div> : null}
    <nav className="marketing-settings-tabs">{tabs.map((item) => <button type="button" key={item.key} className={tab === item.key ? "active" : ""} onClick={() => setTab(item.key)}>{item.label}</button>)}</nav>

    {tab === "departments" ? <div className="marketing-settings-grid"><section className="marketing-settings-form panel"><h3><Buildings />{department.id ? "تعديل القسم" : "إضافة قسم جديد"}</h3><div className="marketing-form-grid two"><label><span>اسم القسم</span><input value={department.name} onChange={(event) => setDepartment({ ...department, name: event.target.value })} /></label><label><span>كود القسم</span><input value={department.code} onChange={(event) => setDepartment({ ...department, code: event.target.value })} /></label><label><span>الترتيب</span><input type="number" value={department.sortOrder} onChange={(event) => setDepartment({ ...department, sortOrder: Number(event.target.value) || 0 })} /></label><label className="marketing-check"><input type="checkbox" checked={department.isContent} onChange={(event) => setDepartment({ ...department, isContent: event.target.checked })} /><span>تحديد هذا القسم باعتباره قسم المحتوى</span></label></div><fieldset><legend>ربط مستخدم واحد أو أكثر بالقسم</legend><div className="settings-user-picker">{meta.users.map((user) => <label key={user.id} className={department.userIds.includes(user.id) ? "selected" : ""}><input type="checkbox" checked={department.userIds.includes(user.id)} onChange={() => setDepartment({ ...department, userIds: department.userIds.includes(user.id) ? department.userIds.filter((id) => id !== user.id) : [...department.userIds, user.id] })} /><span>{user.full_name}</span><small>{user.role_names || user.department_names}</small></label>)}</div></fieldset><div className="marketing-modal-actions"><button className="primary" disabled={working || !department.name || !department.code} onClick={() => void run({ action: "save_setting", entity: "department", ...department }, resetDepartment)}>{department.id ? <PencilSimple /> : <Plus />}{department.id ? "حفظ التعديل" : "إضافة القسم"}</button>{department.id ? <button onClick={resetDepartment}>إلغاء</button> : null}</div></section><section className="marketing-settings-list panel"><h3>قائمة الأقسام</h3>{meta.departments.map((row) => <article key={row.id}><div><h4>{row.name}{row.is_content ? <span>قسم المحتوى</span> : null}</h4><p>{row.code}</p><div>{row.users.map((user) => <span key={user.user_id}>{user.full_name}</span>)}</div></div><footer><button onClick={() => editDepartment(row)}><PencilSimple />تعديل</button><button className="danger" onClick={() => void disable("department", row.id)}><Trash />تعطيل</button></footer></article>)}</section></div> : null}

    {tab === "actions" ? <div className="marketing-settings-grid"><section className="marketing-settings-form panel"><h3><CheckCircle />{action.id ? "تعديل إجراء التكليف" : "إضافة إجراء تكليف"}</h3><div className="marketing-form-grid two"><label><span>القسم</span><select value={action.departmentId} onChange={(event) => setAction({ ...action, departmentId: event.target.value })}><option value="">اختر القسم</option>{meta.departments.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label><span>اسم الإجراء</span><input value={action.name} onChange={(event) => setAction({ ...action, name: event.target.value })} /></label><label><span>كود الإجراء</span><input value={action.code} onChange={(event) => setAction({ ...action, code: event.target.value })} /></label><label><span>نسبة الإجراء</span><input type="number" min={0} max={100} value={action.progressWeight} onChange={(event) => setAction({ ...action, progressWeight: Number(event.target.value) || 0 })} /></label><label><span>الترتيب</span><input type="number" value={action.sortOrder} onChange={(event) => setAction({ ...action, sortOrder: Number(event.target.value) || 0 })} /></label><label className="marketing-check"><input type="checkbox" checked={action.adminOnly} onChange={(event) => setAction({ ...action, adminOnly: event.target.checked })} /><span>أدمن فقط</span></label></div><div className="marketing-modal-actions"><button className="primary" disabled={working || !action.departmentId || !action.name || !action.code} onClick={() => void run({ action: "save_setting", entity: "action", ...action }, resetAction)}>{action.id ? <PencilSimple /> : <Plus />}{action.id ? "حفظ التعديل" : "إضافة الإجراء"}</button>{action.id ? <button onClick={resetAction}>إلغاء</button> : null}</div></section><section className="marketing-settings-list panel"><h3>إجراءات التكليف الحالية</h3>{meta.departments.map((departmentRow) => <div key={departmentRow.id} className="settings-list-group"><h4>{departmentRow.name}</h4>{departmentRow.actions.map((row) => <article key={row.id}><div><h4>{row.name}</h4><p>{row.progress_weight}% — {row.admin_only ? "أدمن فقط" : "متاح للمستخدم"}</p></div><footer><button onClick={() => editAction(row)}><PencilSimple />تعديل</button><button className="danger" onClick={() => void disable("action", row.id)}><Trash />تعطيل</button></footer></article>)}</div>)}</section></div> : null}

    {tab === "creatives" ? <div className="marketing-settings-grid"><section className="marketing-settings-form panel"><h3><Stack />{creative.id ? "تعديل الكرييتيف" : "إضافة كرييتيف"}</h3><div className="marketing-form-grid two"><label><span>اسم الكرييتيف</span><input value={creative.name} onChange={(event) => setCreative({ ...creative, name: event.target.value })} /></label><label><span>الكود المختصر</span><input value={creative.shortCode} onChange={(event) => setCreative({ ...creative, shortCode: event.target.value })} /></label><label><span>القسم الأساسي</span><select value={creative.primaryDepartmentId} onChange={(event) => setCreative({ ...creative, primaryDepartmentId: event.target.value })}><option value="">اختر القسم</option>{meta.departments.filter((row) => !row.is_content).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label><span>الترتيب</span><input type="number" value={creative.sortOrder} onChange={(event) => setCreative({ ...creative, sortOrder: Number(event.target.value) || 0 })} /></label></div><div className="marketing-modal-actions"><button className="primary" disabled={working || !creative.name || !creative.shortCode || !creative.primaryDepartmentId} onClick={() => void run({ action: "save_setting", entity: "creative", id: creative.id, name: creative.name, shortCode: creative.shortCode, primaryDepartmentId: creative.primaryDepartmentId, sortOrder: creative.sortOrder, isActive: creative.isActive }, resetCreative)}>{creative.id ? <PencilSimple /> : <Plus />}{creative.id ? "حفظ التعديل" : "إضافة الكرييتيف"}</button>{creative.id ? <button onClick={resetCreative}>إلغاء</button> : null}</div></section><section className="marketing-settings-list creatives panel"><h3>قائمة الكرييتيفات <span>{meta.creatives.length} كرييتيف</span></h3>{meta.departments.filter((departmentRow) => !departmentRow.is_content).map((departmentRow) => <div key={departmentRow.id} className="settings-list-group"><h4>{departmentRow.name}</h4><div className="creative-settings-grid">{meta.creatives.filter((row) => row.primary_department_id === departmentRow.id).map((row) => <article key={row.id}><div><h4>{row.name}</h4><p>{row.short_code}</p></div><footer><button onClick={() => setCreative({ id: row.id, name: row.name, code: "", shortCode: row.short_code, primaryDepartmentId: row.primary_department_id, sortOrder: row.sort_order, isActive: row.is_active })}><PencilSimple />تعديل</button><button className="danger" onClick={() => void disable("creative", row.id)}><Trash />تعطيل</button></footer></article>)}</div></div>)}</section></div> : null}

    {tab === "campaignTypes" ? <div className="marketing-settings-grid"><section className="marketing-settings-form panel"><h3><Megaphone />{campaignType.id ? "تعديل نوع الحملة" : "إضافة نوع حملة وكود"}</h3><div className="marketing-form-grid two"><label><span>اسم نوع الحملة</span><input value={campaignType.name} onChange={(event) => setCampaignType({ ...campaignType, name: event.target.value })} /></label><label><span>الكود</span><input value={campaignType.code} onChange={(event) => setCampaignType({ ...campaignType, code: event.target.value })} /></label><label><span>Prefix</span><input value={campaignType.prefix} onChange={(event) => setCampaignType({ ...campaignType, prefix: event.target.value })} /></label><label><span>الترتيب</span><input type="number" value={campaignType.sortOrder} onChange={(event) => setCampaignType({ ...campaignType, sortOrder: Number(event.target.value) || 0 })} /></label></div><div className="marketing-modal-actions"><button className="primary" disabled={working || !campaignType.name || !campaignType.code} onClick={() => void run({ action: "save_setting", entity: "campaignType", ...campaignType }, resetCampaignType)}>{campaignType.id ? <PencilSimple /> : <Plus />}{campaignType.id ? "حفظ التعديل" : "إضافة نوع الحملة"}</button>{campaignType.id ? <button onClick={resetCampaignType}>إلغاء</button> : null}</div></section><section className="marketing-settings-list panel"><h3>أنواع الحملات</h3>{meta.campaignTypes.map((row) => <article key={row.id}><div><h4>{row.name}</h4><p>{row.prefix}-{row.code}</p></div><footer><button onClick={() => setCampaignType({ id: row.id, name: row.name, code: row.code, prefix: row.prefix, sortOrder: row.sort_order, isActive: row.is_active })}><PencilSimple />تعديل</button><button className="danger" onClick={() => void disable("campaignType", row.id)}><Trash />تعطيل</button></footer></article>)}</section></div> : null}

    {tab === "platforms" ? <div className="marketing-settings-grid"><section className="marketing-settings-form panel"><h3><Megaphone />{platform.id ? "تعديل منصة" : "إضافة منصة"}</h3><div className="marketing-form-grid two"><label><span>اسم المنصة</span><input value={platform.name} onChange={(event) => setPlatform({ ...platform, name: event.target.value })} /></label><label><span>كود المنصة</span><input value={platform.code} onChange={(event) => setPlatform({ ...platform, code: event.target.value })} /></label><label><span>الترتيب</span><input type="number" value={platform.sortOrder} onChange={(event) => setPlatform({ ...platform, sortOrder: Number(event.target.value) || 0 })} /></label></div><fieldset><legend>أنواع النشر والأبعاد</legend>{platform.publishTypes.map((type, index) => <div key={`${type.id || "new"}-${index}`} className="publish-type-form"><input value={type.name} onChange={(event) => setPlatform({ ...platform, publishTypes: platform.publishTypes.map((row, i) => i === index ? { ...row, name: event.target.value } : row) })} placeholder="نوع النشر" /><input value={type.dimensions} onChange={(event) => setPlatform({ ...platform, publishTypes: platform.publishTypes.map((row, i) => i === index ? { ...row, dimensions: event.target.value } : row) })} placeholder="الأبعاد" /><button onClick={() => setPlatform({ ...platform, publishTypes: platform.publishTypes.filter((_, i) => i !== index) })}><Trash /></button></div>)}<button className="marketing-add-inline" onClick={() => setPlatform({ ...platform, publishTypes: [...platform.publishTypes, { name: "", dimensions: "", isActive: true, sortOrder: (platform.publishTypes.length + 1) * 10 }] })}><Plus />إضافة نوع نشر</button></fieldset><div className="marketing-modal-actions"><button className="primary" disabled={working || !platform.name || !platform.code} onClick={() => void run({ action: "save_setting", entity: "platform", ...platform }, resetPlatform)}>{platform.id ? <PencilSimple /> : <Plus />}{platform.id ? "حفظ التعديل" : "إضافة المنصة"}</button>{platform.id ? <button onClick={resetPlatform}>إلغاء</button> : null}</div></section><section className="marketing-settings-list panel"><h3>المنصات</h3>{meta.platforms.map((row) => <article key={row.id}><div><h4>{row.name}</h4><p>{row.code}</p><div>{row.publishTypes.map((type) => <span key={type.id}>{type.name} {type.dimensions}</span>)}</div></div><footer><button onClick={() => editPlatform(row)}><PencilSimple />تعديل</button><button className="danger" onClick={() => void disable("platform", row.id)}><Trash />تعطيل</button></footer></article>)}</section></div> : null}

    {tab === "categories" ? <BasicSettingSection title="تصنيفات الباقات" icon={<Gift />} entity="packageCategory" form={category} setForm={setCategory} rows={meta.packageCategories} working={working} onSave={() => void run({ action: "save_setting", entity: "packageCategory", ...category }, () => setCategory(basic()))} onDisable={(id) => void disable("packageCategory", id)} /> : null}
    {tab === "statuses" ? <BasicSettingSection title="حالات الطلب" icon={<CheckCircle />} entity="requestStatus" form={requestStatus} setForm={setRequestStatus} rows={meta.requestStatuses} working={working} onSave={() => void run({ action: "save_setting", entity: "requestStatus", ...requestStatus }, () => setRequestStatus(basic()))} onDisable={(id) => void disable("requestStatus", id)} /> : null}
  </section>;
}

type BasicRow = { id: string; name: string; code: string; is_active: boolean; sort_order: number };
function BasicSettingSection({ title, icon, form, setForm, rows, working, onSave, onDisable }: { title: string; icon: React.ReactNode; entity: string; form: BasicForm; setForm: (value: BasicForm) => void; rows: BasicRow[]; working: boolean; onSave: () => void; onDisable: (id: string) => void }) {
  return <div className="marketing-settings-grid"><section className="marketing-settings-form panel"><h3>{icon}{form.id ? `تعديل ${title}` : `إضافة ${title}`}</h3><div className="marketing-form-grid two"><label><span>الاسم</span><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label><span>الكود</span><input value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} /></label><label><span>الترتيب</span><input type="number" value={form.sortOrder} onChange={(event) => setForm({ ...form, sortOrder: Number(event.target.value) || 0 })} /></label></div><div className="marketing-modal-actions"><button className="primary" disabled={working || !form.name || !form.code} onClick={onSave}>{form.id ? <PencilSimple /> : <Plus />}{form.id ? "حفظ التعديل" : "إضافة"}</button>{form.id ? <button onClick={() => setForm(basic())}>إلغاء</button> : null}</div></section><section className="marketing-settings-list panel"><h3>{title}</h3>{rows.map((row) => <article key={row.id}><div><h4>{row.name}</h4><p>{row.code}</p></div><footer><button onClick={() => setForm({ id: row.id, name: row.name, code: row.code, sortOrder: row.sort_order, isActive: row.is_active })}><PencilSimple />تعديل</button><button className="danger" onClick={() => onDisable(row.id)}><Trash />تعطيل</button></footer></article>)}</section></div>;
}

export function MarketingSettingsPanel() { return <MarketingProvider><MarketingSettingsPanelContent /></MarketingProvider>; }
