import { useEffect,useMemo,useState } from "react";
import { DownloadSimple,MagnifyingGlass,X } from "@phosphor-icons/react";
import { operationsFetch,formatOperationsError,exportExcelFile } from "../operations/api";
import type { VehicleRow,TransferRow } from "../operations/types";

export type OperationsDashboardSpec =
 | {kind:"vehicles";title:string;locationCode?:string;metric?:string}
 | {kind:"requests";title:string};

export function OperationsDashboardModal({spec,onClose}:{spec:OperationsDashboardSpec|null;onClose:()=>void}){
 const [q,setQ]=useState(''),[rows,setRows]=useState<VehicleRow[]>([]),[requests,setRequests]=useState<TransferRow[]>([]),[requestType,setRequestType]=useState<'transfer'|'photography'>('transfer'),[detail,setDetail]=useState<TransferRow|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!spec)return;setQ('');setRows([]);setRequests([]);setDetail(null);setRequestType('transfer')},[spec]);
 useEffect(()=>{if(!spec)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(detail)setDetail(null);else onClose()}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[spec,detail,onClose]);
 useEffect(()=>{if(!spec)return;const timer=setTimeout(async()=>{setLoading(true);setError('');try{if(spec.kind==='vehicles'){const r=await operationsFetch<any>('dashboard-vehicles',{query:{q,locationCode:spec.locationCode,metric:spec.metric}});setRows(r.rows||[])}else{const r=await operationsFetch<any>('dashboard-requests',{query:{tab:'all',type:requestType}});setRequests(r.requests||[])}}catch(e){setError(formatOperationsError(e));if(spec.kind==='vehicles')setRows([]);else setRequests([])}finally{setLoading(false)}},250);return()=>clearTimeout(timer)},[spec,q,requestType]);
 const filteredRequests=useMemo(()=>requests.filter(r=>!q.trim()||[r.request_no,r.requested_by_name,r.requested_by_branch,...r.vehicles.flatMap(v=>[v.vin,v.carName,v.statement])].some(v=>String(v||'').toLowerCase().includes(q.trim().toLowerCase()))),[requests,q]);
 if(!spec)return null;
 const current=spec;
 const exportRows=()=>{if(current.kind==='vehicles')exportExcelFile(current.title,['رقم الهيكل','السيارة','البيان','موديل','داخلي','خارجي','المكان','الحالة'],rows.map(v=>[v.vin,v.car_name,v.statement,v.model_year,v.interior_color,v.exterior_color,v.location_name,v.status_name]));else exportExcelFile(`${current.title}-${requestType==='transfer'?'النقل':'التصوير'}`,['رقم الطلب','المنشئ','تاريخ الطلب','عدد السيارات'],filteredRequests.map(r=>[r.request_no,r.requested_by_name,new Date(r.requested_at).toLocaleString('ar-SA'),r.vehicle_count]));};
 return <div className="operations-dashboard-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><div className="operations-dashboard-modal"><header><div><span>تفاصيل العمليات</span><h2>{current.title}</h2></div><button type="button" onClick={onClose}><X size={21}/></button></header>{current.kind==='requests'?<div className="operations-dashboard-tabs"><button className={requestType==='transfer'?'active':''} onClick={()=>setRequestType('transfer')}>طلبات النقل</button><button className={requestType==='photography'?'active':''} onClick={()=>setRequestType('photography')}>طلبات التصوير</button></div>:null}<div className="operations-dashboard-toolbar"><label><MagnifyingGlass/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={current.kind==='vehicles'?'بحث برقم الهيكل أو السيارة أو البيان':'بحث برقم الطلب أو المنشئ أو السيارة'}/></label><button type="button" onClick={exportRows}><DownloadSimple/>تصدير Excel</button></div>{error?<div className="operations-error">{error}</div>:null}{loading?<div className="operations-loading">جاري تحميل البيانات...</div>:current.kind==='vehicles'?<div className="operations-dashboard-table"><table><thead><tr><th>رقم الهيكل</th><th>السيارة</th><th>البيان</th><th>موديل</th><th>داخلي</th><th>خارجي</th><th>المكان</th><th>الحالة</th></tr></thead><tbody>{rows.length?rows.map(v=><tr key={v.id}><td><strong>{v.vin}</strong></td><td>{v.car_name||'—'}</td><td>{v.statement||'—'}</td><td>{v.model_year||'—'}</td><td>{v.interior_color||'—'}</td><td>{v.exterior_color||'—'}</td><td>{v.location_name||'—'}</td><td>{v.status_name||v.status_code}</td></tr>):<tr><td colSpan={8}>لا توجد سيارات مطابقة</td></tr>}</tbody></table></div>:<div className="operations-dashboard-table"><table><thead><tr><th>رقم الطلب</th><th>المنشئ</th><th>تاريخ الطلب</th><th>عدد السيارات</th><th>الإجراء</th></tr></thead><tbody>{filteredRequests.length?filteredRequests.map(r=><tr key={r.id}><td><strong>{r.request_no}</strong></td><td>{r.requested_by_name||'—'}</td><td>{new Date(r.requested_at).toLocaleString('ar-SA')}</td><td>{r.vehicle_count}</td><td><button type="button" onClick={()=>setDetail(r)}>تفاصيل</button></td></tr>):<tr><td colSpan={5}>لا توجد طلبات مطابقة</td></tr>}</tbody></table></div>}{detail?<div className="operations-request-detail"><header><div><h3>{detail.request_no}</h3><span>{detail.requested_by_name||'—'} — {new Date(detail.requested_at).toLocaleString('ar-SA')}</span></div><button onClick={()=>setDetail(null)}><X/></button></header><table><thead><tr><th>رقم الهيكل</th><th>السيارة</th><th>البيان</th></tr></thead><tbody>{detail.vehicles.map(v=><tr key={v.id}><td>{v.vin}</td><td>{v.carName||'—'}</td><td>{v.statement||'—'}</td></tr>)}</tbody></table></div>:null}</div></div>
}
