export type OperationsMeta = {
  ok: boolean;
  locations: Array<{ id: string; code: string; name: string; branch_code?: string | null; is_agency: boolean; sort_order?: number }>;
  statuses: Array<{ code: string; name: string; sort_order?: number; is_actual_stock: boolean; is_delivery_status: boolean; is_terminal: boolean }>;
  checkItems: Array<{ code: string; name: string; sort_order: number }>;
  permissions: Record<string, boolean>;
};

export type VehicleRow = {
  id: string;
  vin: string;
  car_name?: string | null;
  statement?: string | null;
  agent_name?: string | null;
  exterior_color?: string | null;
  interior_color?: string | null;
  model_year?: string | null;
  plate_no?: string | null;
  batch_no?: string | null;
  location_id?: string | null;
  location_code?: string | null;
  location_name?: string | null;
  branch_code?: string | null;
  status_code: string;
  status_name: string;
  source_type?: string | null;
  has_notes: boolean;
  notes?: string | null;
  state_note?: string | null;
  shortage_note?: string | null;
  archived_at?: string | null;
  archive_reason?: string | null;
  created_by_name?: string | null;
  updated_by_name?: string | null;
  created_at: string;
  updated_at: string;
  version: number;
  financial_approved?: boolean;
  administrative_approved?: boolean;
  financial_note?: string;
  administrative_note?: string;
  tracking_active_orders?: number;
  tracking_order_id?: string | null;
  tracking_order_no?: string | null;
  tracking_status?: string | null;
  tracking_progress?: number;
  active_transfer_requests?: number;
};

export type VehicleDetail = VehicleRow & {
  checks: Array<{ code: string; name: string; status: string; note?: string | null; updated_by_name?: string | null; updated_at?: string | null }>;
  checkHistory: any[];
  approvals: any[];
  approvalEvents: any[];
  movements: any[];
  transfers: any[];
  tracking: any[];
  archiveEvents: any[];
  statusNotes: any[];
};

export type TransferRow = {
  id: string;
  request_no: string;
  request_kind: string;
  status: string;
  note?: string | null;
  requested_by?: string;
  requested_by_name?: string | null;
  requested_by_role?: string | null;
  requested_by_branch?: string | null;
  source_branch_code?: string | null;
  destination_branch_code?: string | null;
  requested_at: string;
  completed_at?: string | null;
  cancelled_at?: string | null;
  cancellation_reason?: string | null;
  source_location_name?: string | null;
  destination_location_name?: string | null;
  vehicles_count: number;
  vehicles: Array<{ vehicle_id: string; vin: string; car_name?: string | null; statement?: string | null; model_year?: string | null }>;
};
