export type OperationsMeta = {
  ok: boolean;
  locations: Array<{ id: string; code: string; name: string; branch_code: string | null; location_type: string; sort_order: number }>;
  statuses: Array<{ code: string; name: string; sort_order: number; is_inventory: boolean; requires_status_note: boolean; starts_delivery_cycle: boolean; is_final_delivery: boolean }>;
  checkItems: Array<{ code: string; name: string; sort_order: number }>;
  permissions: string[];
  isSystemAdmin: boolean;
  branches: string[];
};

export type OperationsVehicle = {
  id: string;
  vin: string;
  car_name: string | null;
  statement: string | null;
  agent_name: string | null;
  interior_color: string | null;
  exterior_color: string | null;
  model_year: string | null;
  plate_no: string | null;
  batch_no: string | null;
  location_id: string | null;
  location_code?: string | null;
  location_name: string | null;
  branch_code: string | null;
  status_code: string;
  status_name: string | null;
  status_note: string | null;
  notes: string | null;
  reservation_shortage_location_note: string | null;
  has_notes: boolean;
  is_archived: boolean;
  archived_at?: string | null;
  financial_approved?: boolean;
  administrative_approved?: boolean;
  tracking_request_id?: string | null;
  tracking_request_no?: string | null;
  tracking_status?: string | null;
  tracking_progress?: number | null;
  tracking_archived?: boolean | null;
  tracking_deleted?: boolean | null;
  active_requests?: number;
  version: number;
  created_at: string;
  updated_at: string;
  checks?: Array<any>;
  checkHistory?: Array<any>;
  noteHistory?: Array<any>;
  movements?: Array<any>;
  requests?: Array<any>;
  approvals?: Array<any>;
  approvalEvents?: Array<any>;
  tracking?: Array<any>;
};
