import { useCallback,useEffect,useState } from "react";
import { FloppyDisk,MapPin,Plus,WarningCircle } from "@phosphor-icons/react";
import { operationsFetch } from "../api";
import type { OperationsMeta } from "../types";

const empty={id:"",entity:"location",code:"",name:"",branchId:"",notes:"",sortOrder:"0",countsInInventory:true,isFinal:false,requiresApprovals:false};
export function OperationsSettingsPanel() {
  const [meta,setMeta]=useState<OperationsMeta|null>(null);const [form,setForm]=useState({...empty});const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
  const load=useCallback(async()=>{setError("");try{setMeta(await operationsFetch<OperationsMeta>("meta"));}catch(err){setError(err instanceof Error?err.message:"تعذر تحميل الإعدادات");}},[]);
  useEffect(()=>{void load();},[load]);
  async function submit(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");setMessage("");try{const payload=await operationsFetch<{message:string}>("settings",{method:"POST",body:JSON.stringify({...form,sortOrder:Number(form.sortOrder)})});setMessage(payload.message);setForm({...empty});await load();}catch(err){setError(err instanceof Error?err.message:"تعذر الحفظ");}finally{setSaving(false);}}
  return <div className="operations-settings-embedded">
    {error?<div className="connection-banner"><WarningCircle size={19}/><span>{error}</span></div>:null}{message?<div className="success-banner">{message}</div>:null}
    <section className="panel operations-form"><header className="settings-card-title"><div><MapPin size={22}/><h2>مواقع وحالات العمليات</h2></div><button type="button" onClick={()=>setForm({...empty})}><Plus size={16}/>جديد</button></header>
      <form onSubmit={submit} className="operations-form-grid"><label><span>نوع الإعداد</span><select value={form.entity} onChange={e=>setForm({...empty,entity:e.target.value})}><option value="location">مكان</option><option value="status">حالة سيارة</option></select></label><label><span>الكود</span><input required value={form.code} disabled={Boolean(form.id&&form.entity==="status")} onChange={e=>setForm({...form,code:e.target.value})}/></label><label><span>الاسم</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>
      {form.entity==="location"?<><label><span>الفرع المرتبط</span><select value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">بدون فرع</option>{meta?.branches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><label className="wide"><span>ملاحظات</span><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></>:<div className="operations-check-grid wide"><label><input type="checkbox" checked={form.countsInInventory} onChange={e=>setForm({...form,countsInInventory:e.target.checked})}/><span>تدخل في المخزون الفعلي</span></label><label><input type="checkbox" checked={form.isFinal} onChange={e=>setForm({...form,isFinal:e.target.checked})}/><span>حالة نهائية</span></label><label><input type="checkbox" checked={form.requiresApprovals} onChange={e=>setForm({...form,requiresApprovals:e.target.checked})}/><span>تحتاج موافقات</span></label></div>}
      <label><span>الترتيب</span><input type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:e.target.value})}/></label><div className="operations-form-actions wide"><button className="primary" disabled={saving}><FloppyDisk size={17}/>{saving?"جاري الحفظ...":"حفظ الإعداد"}</button></div></form>
    </section>
    <div className="operations-settings-grid"><section className="panel"><h3>المواقع</h3>{meta?.locations.map(item=><button type="button" className="settings-row" key={item.id} onClick={()=>setForm({id:item.id,entity:"location",code:item.code,name:item.name,branchId:item.branch_id||"",notes:item.notes||"",sortOrder:String(item.sort_order),countsInInventory:true,isFinal:false,requiresApprovals:false})}><span>{item.name}<small>{item.branch_name||"بدون فرع"}</small></span><b>{item.code}</b></button>)}</section><section className="panel"><h3>الحالات</h3>{meta?.statuses.map(item=><button type="button" className="settings-row" key={item.code} onClick={()=>setForm({id:"",entity:"status",code:item.code,name:item.name,branchId:"",notes:"",sortOrder:String(item.sort_order),countsInInventory:item.counts_in_inventory,isFinal:item.is_final,requiresApprovals:item.requires_approvals})}><span>{item.name}<small>{item.is_final?"نهائية":item.counts_in_inventory?"ضمن المخزون":"خارج المخزون"}</small></span><b>{item.code}</b></button>)}</section></div>
  </div>;
}
