import { useState } from "react";
import { CheckCircle, FloppyDisk, MapPin, ShieldCheck, WarningCircle } from "@phosphor-icons/react";
import { operationsFetch } from "../api";
import { useOperationsMeta } from "../useOperationsMeta";

export function OperationsSettingsPanel(){
  const {meta,loading,error,refresh}=useOperationsMeta();const [busy,setBusy]=useState("");const [message,setMessage]=useState("");const [actionError,setActionError]=useState("");
  async function save(kind:"location"|"status",row:any){const key=kind==="location"?row.id:row.code;setBusy(`${kind}:${key}`);setActionError("");setMessage("");try{await operationsFetch("/api/operations",{method:"POST",body:JSON.stringify({action:"update_settings",kind,id:row.id,code:row.code,name:row.name,sortOrder:row.sort_order,requiresStatusNote:row.requires_status_note,isInventory:row.is_inventory,branchIds:row.branch_ids||[]})});setMessage("تم حفظ إعدادات العمليات");await refresh();}catch(reason){setActionError(reason instanceof Error?reason.message:"تعذر حفظ الإعدادات");}finally{setBusy("");}}
  if(loading)return <section className="panel operations-settings-panel">جاري تحميل إعدادات العمليات...</section>;
  return <div className="operations-settings-wrap">{error||actionError?<div className="connection-banner"><WarningCircle size={20}/><span>{error||actionError}</span></div>:null}{message?<div className="success-banner operations-success-banner"><CheckCircle size={20}/>{message}</div>:null}<section className="panel operations-settings-panel"><header><div><MapPin size={24}/><span><h2>المواقع والفروع</h2><p>المواقع التشغيلية تأتي من PostgreSQL وترتبط بنطاق الفروع.</p></span></div></header><div className="operations-settings-list">{meta?.locations.map((row)=><div key={row.id}><input defaultValue={row.name} onChange={(e)=>{row.name=e.target.value;}}/><input type="number" defaultValue={row.sort_order} onChange={(e)=>{row.sort_order=Number(e.target.value);}}/><select multiple value={row.branch_ids||[]} onChange={(e)=>{row.branch_ids=Array.from(e.target.selectedOptions).map((option)=>option.value);}} aria-label="الفروع المرتبطة بالموقع">{meta?.branches?.map((branch)=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><button type="button" disabled={busy===`location:${row.id}`} onClick={()=>void save("location",row)}><FloppyDisk size={17}/>حفظ</button></div>)}</div></section><section className="panel operations-settings-panel"><header><div><ShieldCheck size={24}/><span><h2>حالات السيارات</h2><p>الحالات ليست Hardcoded داخل صفحات الحركة.</p></span></div></header><div className="operations-settings-list statuses">{meta?.statuses.map((row)=><div key={row.code}><input defaultValue={row.name} onChange={(e)=>{row.name=e.target.value;}}/><input type="number" defaultValue={row.sort_order} onChange={(e)=>{row.sort_order=Number(e.target.value);}}/><label><input type="checkbox" defaultChecked={row.is_inventory} onChange={(e)=>{row.is_inventory=e.target.checked;}}/>ضمن المخزون</label><label><input type="checkbox" defaultChecked={row.requires_status_note} onChange={(e)=>{row.requires_status_note=e.target.checked;}}/>تتطلب ملاحظة</label><button type="button" disabled={busy===`status:${row.code}`} onClick={()=>void save("status",row)}><FloppyDisk size={17}/>حفظ</button></div>)}</div></section><section className="panel operations-settings-panel"><header><div><ShieldCheck size={24}/><span><h2>صلاحيات العمليات</h2><p>كل Endpoint يتحقق من الصلاحية Server-side، ومدير النظام يحصل عليها مركزيًا.</p></span></div></header><div className="operations-permissions-grid">{meta?.permissions.filter((row)=>row.system_code==="operations").map((row)=><div key={row.code}><code>{row.code}</code><span>{row.name}</span></div>)}</div></section></div>;
}
