import { useEffect, useRef, useState } from "react";
import { Archive, CheckCircle, ClockCounterClockwise, LinkSimple, SpinnerGap, Truck, X } from "@phosphor-icons/react";
import { useEscapeToClose } from "../../components/useEscapeToClose";
import { formatOperationsDate, operationsFetch, statusLabel } from "../api";
import type { VehicleDetail } from "../types";

type Props={vehicleId:string|null;onClose:()=>void;onArchived?:()=>void};
export function VehicleDetailDrawer({vehicleId,onClose,onArchived}:Props){
  const [detail,setDetail]=useState<VehicleDetail|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[archiveReason,setArchiveReason]=useState("");const[archiving,setArchiving]=useState(false);const abortRef=useRef<AbortController|null>(null);
  const close=()=>{abortRef.current?.abort();setDetail(null);setError("");setArchiveReason("");onClose();}; useEscapeToClose(Boolean(vehicleId),close);
  useEffect(()=>{if(!vehicleId){setDetail(null);return;}abortRef.current?.abort();const c=new AbortController();abortRef.current=c;setDetail(null);setError("");setLoading(true);operationsFetch<{detail:VehicleDetail}>(`/api/operations?resource=vehicle&id=${encodeURIComponent(vehicleId)}`,{signal:c.signal}).then((p)=>setDetail(p.detail)).catch((e)=>{if((e as Error).name!=="AbortError")setError((e as Error).message);}).finally(()=>setLoading(false));return()=>c.abort();},[vehicleId]);
  if(!vehicleId)return null;const v=detail?.vehicle;
  const archive=async()=>{if(!archiveReason.trim())return;setArchiving(true);setError("");try{await operationsFetch("/api/operations",{method:"POST",body:JSON.stringify({action:"archive_vehicle",vehicleId,reason:archiveReason})});close();onArchived?.();}catch(e){setError((e as Error).message);}finally{setArchiving(false);}};
  return <div className="drawer-backdrop" onMouseDown={close}><aside className="operations-detail-drawer" onMouseDown={(e)=>e.stopPropagation()}>
    <header><div><span>تفاصيل السيارة</span><h2>{v?.vin||"جاري التحميل..."}</h2><p>{v?[v.car_name,v.statement,v.model_year].filter(Boolean).join(" · "):"عرض البيانات من مصدر العمليات المعتمد"}</p></div><button type="button" className="icon-button" onClick={close}><X size={20}/></button></header>
    <div className="operations-detail-body">{loading?<div className="operations-loading"><SpinnerGap className="spin" size={24}/>جاري تحميل التفاصيل...</div>:null}{error?<div className="operations-error">{error}</div>:null}{v?<>
      <section className="operations-detail-grid">{[
        ["VIN",v.vin],["السيارة",v.car_name],["الوصف",v.statement],["الوكيل",v.agent_name],["الموديل",v.model_year],["اللون الداخلي",v.interior_color],["اللون الخارجي",v.exterior_color],["اللوحة",v.plate_no],["اسم الدفعة",v.batch_no],["المكان الحالي",v.location_name],["الفرع الحالي",v.branch_code||v.location_branch_code],["الحالة",v.status_name||statusLabel(v.status_code)],["ملاحظات السيارة",v.notes],["ملاحظات الحالة",v.status_notes],["حجز - نواقص - تحديد مكان",v.missing_reservation_location],["آخر تعديل",formatOperationsDate(v.updated_at)]
      ].map(([label,value])=><div key={label}><small>{label}</small><strong>{String(value||"—")}</strong></div>)}</section>
      <section className="operations-detail-section"><h3><CheckCircle size={19}/> التشيك</h3><div className="operations-checklist-readonly">{detail.checklist.map((item)=><div key={item.code} className={item.is_present?"done":""}><span>{item.name}</span><b>{item.is_present?"موجود":"غير موجود"}</b>{item.note?<small>{item.note}</small>:null}</div>)}</div></section>
      <section className="operations-detail-section"><h3><CheckCircle size={19}/> الموافقات</h3><div className="operations-approval-summary"><div><span>الموافقة المالية</span><b className={Boolean(detail.approval?.financial_approved)?"ok":"pending"}>{Boolean(detail.approval?.financial_approved)?"تمت":"لم تتم"}</b><small>{String(detail.approval?.financial_note||"بدون ملاحظة")}</small></div><div><span>الموافقة الإدارية</span><b className={Boolean(detail.approval?.administrative_approved)?"ok":"pending"}>{Boolean(detail.approval?.administrative_approved)?"تمت":"لم تتم"}</b><small>{String(detail.approval?.administrative_note||"بدون ملاحظة")}</small></div></div></section>
      <section className="operations-detail-section"><h3><ClockCounterClockwise size={19}/> آخر الحركات</h3>{detail.movements.length?<div className="operations-timeline">{detail.movements.slice(0,10).map((m)=><article key={String(m.id)}><b>{String(m.from_location_name||"—")} ← {String(m.to_location_name||"—")}</b><span>{statusLabel(String(m.old_status||""))} ← {statusLabel(String(m.new_status||""))}</span><small>{String(m.performed_by_name||"—")} · {formatOperationsDate(String(m.created_at||""))}</small>{m.note?<p>{String(m.note)}</p>:null}</article>)}</div>:<p className="operations-empty-inline">لا توجد حركات مسجلة.</p>}</section>
      <section className="operations-detail-section"><h3><Truck size={19}/> الطلبات</h3>{detail.requests.length?<div className="operations-mini-list">{detail.requests.map((r)=><div key={String(r.id)}><b>{String(r.request_no)}</b><span>نقل · {String(r.status)}</span><small>{formatOperationsDate(String(r.requested_at||""))}</small></div>)}</div>:<p className="operations-empty-inline">لا توجد طلبات مرتبطة.</p>}</section>
      <section className="operations-detail-section"><h3><LinkSimple size={19}/> التراكينج</h3>{detail.trackingOrders.length?<div className="operations-mini-list">{detail.trackingOrders.map((t)=><div key={String(t.id)}><b>{String(t.sales_order_no||"—")}</b><span>{String(t.status||"—")} · {String(t.progress_percent||0)}%</span><small>{formatOperationsDate(String(t.updated_at||""))}</small></div>)}</div>:<p className="operations-empty-inline">لا يوجد طلب تتبع مرتبط.</p>}</section>
      {!v.is_archived?<section className="operations-archive-box"><h3><Archive size={19}/> أرشفة السيارة</h3><p>تُنفذ فقط بعد حالة «مباع تم التسليم»، اكتمال الموافقتين، واكتمال التراكينج 100%.</p><textarea value={archiveReason} onChange={(e)=>setArchiveReason(e.target.value)} placeholder="سبب الأرشفة"/><button type="button" disabled={archiving||!archiveReason.trim()} onClick={()=>void archive()}>{archiving?"جاري الأرشفة...":"أرشفة السيارة"}</button></section>:null}
    </>:null}</div>
  </aside></div>;
}
