import { useEffect,useState } from "react";
import { ArrowSquareOut,Check,X } from "@phosphor-icons/react";
import { operationsFetch } from "../api";
import type { VehicleDetail } from "../types";
import { Modal } from "./Modal";

const show=(value:unknown)=>value===null||value===undefined||value===""?"—":String(value);
const date=(value?:string|null)=>value?new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";
const noteType:Record<string,string>={vehicle:"ملاحظة السيارة",status:"ملاحظة الحالة",booking_shortage_location:"حجز - نواقص - تحديد مكان",place:"ملاحظة المكان"};
const approvalAction:Record<string,string>={approved:"اعتماد",revoked:"تراجع",note_updated:"تحديث الملاحظة",initialized:"تهيئة الموافقة",cleared:"مسح الحالة التشغيلية"};
export function VehicleDetailsModal({vehicleId,onClose}:{vehicleId:string|null;onClose:()=>void}) {
  const [detail,setDetail]=useState<VehicleDetail|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{if(!vehicleId){setDetail(null);return;}let active=true;const load=()=>{setLoading(true);setError("");return operationsFetch<{vehicle:VehicleDetail}>("vehicles",{query:{id:vehicleId}}).then(payload=>{if(active)setDetail(payload.vehicle)}).catch(err=>{if(active)setError(err instanceof Error?err.message:"تعذر تحميل التفاصيل")}).finally(()=>{if(active)setLoading(false)})};void load();const refresh=()=>void load();window.addEventListener("operations:data-changed",refresh);return()=>{active=false;window.removeEventListener("operations:data-changed",refresh)};},[vehicleId]);
  return <Modal open={Boolean(vehicleId)} title={detail?`تفاصيل السيارة ${detail.vin}`:"تفاصيل السيارة"} subtitle="كل البيانات والحركات والموافقات والتشيك محفوظة في سجل واحد" onClose={onClose} className="wide">
    {loading?<div className="operations-loading">جاري تحميل التفاصيل...</div>:error?<div className="operations-inline-error">{error}</div>:detail?<div className="operations-detail">
      <div className="operations-detail-summary"><div><span>VIN</span><strong className="mono">{detail.vin}</strong></div><div><span>السيارة</span><strong>{show(detail.car_name)}</strong></div><div><span>المكان الحالي</span><strong>{show(detail.location_name)}</strong></div><div><span>الحالة الحالية</span><strong>{show(detail.status_name)}</strong></div></div>
      <section><h3>بيانات السيارة</h3><div className="operations-detail-grid"><p><span>البيان</span>{show(detail.statement)}</p><p><span>الوكيل</span>{show(detail.agent_name)}</p><p><span>اللون الداخلي</span>{show(detail.interior_color)}</p><p><span>اللون الخارجي</span>{show(detail.exterior_color)}</p><p><span>الموديل</span>{show(detail.model_year)}</p><p><span>اللوحة</span>{show(detail.plate_no)}</p><p><span>اسم الدفعة بالتاريخ</span>{show(detail.batch_no)}</p><p><span>الفرع</span>{show(detail.branch_name)}</p><p className="wide"><span>ملاحظات السيارة</span>{show(detail.notes)}</p><p className="wide"><span>ملاحظات الحالة</span>{show(detail.status_note)}</p><p className="wide"><span>حجز - نواقص - تحديد مكان</span>{show(detail.booking_shortage_location_notes)}</p><p><span>منشئ السيارة</span>{show(detail.created_by_name)}</p><p><span>آخر مستخدم عدّل</span>{show(detail.updated_by_name)}</p><p><span>تاريخ الإنشاء</span>{date(detail.created_at)}</p><p><span>آخر تعديل</span>{date(detail.updated_at)}</p></div></section>
      <section><h3>Tracking</h3>{detail.trackingHistory.length?<div className="operations-timeline">{detail.trackingHistory.map(item=><article key={item.tracking_vehicle_id}><b>{item.request_no} — {item.progress}%</b><span>{item.current_stage||item.status} • {date(item.updated_at)}</span><p>{item.is_deleted?"محذوف":item.is_cancelled?"ملغي":item.is_rejected?"مرفوض":item.is_archived||item.progress===100?"مكتمل":"طلب نشط"}</p><a href="/tracking" className="inline-link"><ArrowSquareOut size={15}/>فتح نظام التراكينج</a></article>)}</div>:<p className="operations-empty">لا يوجد طلب تراكينج مرتبط</p>}</section>
      <section><h3>التشيك الحالي</h3><div className="operations-check-grid readonly">{detail.checks.map(item=><div key={item.code} className={item.is_present?"checked":""}>{item.is_present?<Check size={16}/>:<X size={16}/>}<span>{item.name}</span><small>{item.updated_by_name?`${item.updated_by_name} • ${date(item.updated_at)}`:"لم يُعدّل"}</small></div>)}</div></section>
      <section><h3>سجل تغييرات التشيك</h3><div className="operations-timeline">{detail.checkHistory.length?detail.checkHistory.map(item=><article key={item.id}><b>{item.item_name||item.item_code}: {item.old_value===null?"غير مسجل":item.old_value?"موجود":"غير موجود"} ← {item.new_value?"موجود":"غير موجود"}</b><span>{item.changer_name} • {date(item.created_at)}</span><p>{show(item.note)}</p></article>):<p className="operations-empty">لا يوجد سجل تغييرات</p>}</div></section>
      <section><h3>الموافقات</h3><div className="operations-detail-grid"><p><span>الموافقة المالية</span>{detail.financial_approved?`مكتملة — ${show(detail.financial_approved_by_name)}`:"غير مكتملة"}</p><p><span>الموافقة الإدارية</span>{detail.administrative_approved?`مكتملة — ${show(detail.administrative_approved_by_name)}`:"غير مكتملة"}</p></div><div className="operations-timeline">{detail.approvals.length?detail.approvals.map(item=><article key={item.id}><b>{item.approval_type==="financial"?"مالية":"إدارية"} — {approvalAction[item.action]||item.action}</b><span>{item.performer_name} • {item.performer_branch||"—"} • {date(item.created_at)}</span><p>{show(item.note)}</p></article>):<p className="operations-empty">لا يوجد سجل موافقات</p>}</div></section>
      <section><h3>سجل الملاحظات</h3><div className="operations-timeline">{detail.notes.length?detail.notes.map(item=><article key={item.id}><b>{noteType[item.note_type]||item.note_type}</b><span>{item.creator_name} • {date(item.created_at)}</span><p>{item.note}</p></article>):<p className="operations-empty">لا توجد ملاحظات تاريخية</p>}</div></section>
      <section><h3>الحركات</h3><div className="operations-timeline">{detail.movements.length?detail.movements.map(item=><article key={item.id}><b>{show(item.from_location_name)} ← {show(item.to_location_name)}</b><span>{show(item.performer_name)} • {date(item.created_at)}{item.request_no?` • ${item.request_no}`:""}</span><p>{[item.note,item.status_note,item.shortage_note].filter(Boolean).join(" — ")||"—"}</p></article>):<p className="operations-empty">لا توجد حركات مسجلة</p>}</div></section>
      <section><h3>طلبات النقل والتصوير</h3><div className="operations-timeline">{detail.requests.length?detail.requests.map(item=><article key={item.id}><b>{item.request_no} — {item.transfer_type==="transfer"?"نقل":"تصوير"}</b><span>{item.status} • {date(item.requested_at)}</span><p>{item.cancellation_reason||item.notes||"—"}</p></article>):<p className="operations-empty">لا توجد طلبات مرتبطة</p>}</div></section>
      {detail.archive?<section><h3>الأرشيف</h3><div className="operations-detail-grid"><p><span>منفذ الأرشفة</span>{detail.archive.archived_by_name}</p><p><span>تاريخ الأرشفة</span>{date(detail.archive.archived_at)}</p><p className="wide"><span>السبب</span>{detail.archive.reason}</p></div></section>:null}
      {detail.audit?.length?<section><h3>Audit Trail</h3><div className="operations-timeline">{detail.audit.map(item=><article key={item.id}><b>{item.action}{item.is_override?" — تجاوز إداري":""}</b><span>{show(item.actor_name)} • {show(item.actor_branch)} • {date(item.created_at)}</span><p>{show(item.reason)}</p></article>)}</div></section>:null}
    </div>:null}
  </Modal>;
}
